### ISSUE TITLE
Cup Water Level line

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#101]
This issue will track design choices and development implementations for the cup water level line and checkbox.

**Comment by marlitas** [comment]
The `cupWaterLevelLine` is ready for design feedback and review. I know you were wanting to change the coloring, or some other aspects of the line @amanda-phet, so just let me know what you're thinking. 

This is the current implementation.
<img width="821" alt="Screen Shot 2022-08-25 at 4 43 45 PM" src="https://user-images.githubusercontent.com/42476338/186781543-05db58b9-d704-4dff-b766-714db654c3d9.png">

**Comment by amanda-phet** [comment]
I made the line slightly darker and I think it works well. Can you change it to #85BBCC?

**Comment by marlitas** [comment]
Color changed! Here's a screenshot. @amanda-phet let me know if there is any additional feedback or changes, if not feel free to close.
<img width="1102" alt="Screen Shot 2022-08-26 at 1 04 29 PM" src="https://user-images.githubusercontent.com/42476338/186974602-04a921fe-2129-480a-bba3-18a96e714aa6.png">

**Comment by amanda-phet** [comment]
@catherinecarter what do you think?

**Comment by catherinecarter** [comment]
> @catherinecarter what do you think?

I like it. The color is similar enough to make it look like a water line, but different enough that it's easier to see when the mean water line is above the initial water line. I played around with it in PhET Test, and I think it's really nice.

**Comment by amanda-phet** [comment]
Thanks! Closing.
