### ISSUE TITLE
Table & Notebook Paper Cup Spaces

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#102]
This issue will track changes, design decisions, and feedback for the two data spaces in the intro screen. 

Initial Mock-Up for the separate data spaces:
<img width="631" alt="Screen Shot 2022-08-26 at 8 45 47 AM" src="https://user-images.githubusercontent.com/42476338/186931226-7844cd8c-cec6-44e3-adf8-6a64c6ae7dfb.png">

**Comment by marlitas** [comment]
I added in the artwork for the notebook paper and table. Below are screenshots of what that's looking like:
<img width="1261" alt="Screen Shot 2022-09-13 at 4 06 22 PM" src="https://user-images.githubusercontent.com/42476338/190024750-30d94ef5-26c8-4624-bb06-6ffeda9a3d9b.png">
<img width="1261" alt="Screen Shot 2022-09-13 at 4 06 28 PM" src="https://user-images.githubusercontent.com/42476338/190024763-23bdf626-2b0b-4594-9a43-b169cccd6f78.png">

I scaled the paper down so that it would fit all the cup and chocolate representations while keeping a small but decent margin on the sides, however in the LevelingOut screen this begins to infiltrate the people and table area. My current suggestion would be to see if we can make the paper a bit shorter, but we can also play with the sizing of objects. 

Sending to @amanda-phet for feedback!

**Comment by marlitas** [comment]
@amanda-phet I saw a partyTable.png was added to images. I added that to the licenses json to avoid CT errors, and wanted to confirm that the artist is Mariah Hermsmeyer

**Comment by marlitas** [comment]
I referenced the wrong issue in the above commits "Expand no-simple-type-checking-assertions regex". The correct issue is: https://github.com/phetsims/chipper/issues/1344

**Comment by marlitas** [comment]
@amanda-phet I wanted to check and see if there are any other lines in the paper area you would like to look like pencil strokes? I switched the 2D cup strokes and pipe strokes to the pencil pattern you provided, but was unsure if you wanted something similar for the meanLine, waterLine, and tickMarks (in their respective colors).

Here is a screenshot showing the current state as it is now:
<img width="1086" alt="Screen Shot 2022-10-27 at 12 51 52 PM" src="https://user-images.githubusercontent.com/42476338/198374741-332613a3-1901-4d84-8d83-ccc250c430e1.png">

**Comment by marlitas** [comment]
@samreid and I met with @mariahmaephet today and were able to add in the notepad artwork with a combination of code and png. Here's a screenshot of what it's looking like. Personally I think it's fun without being distracting. @amanda-phet let me know your thoughts. We are going to be pushing forward with an RC for this in the coming week.

<img width="1260" alt="Screenshot 2022-10-31 at 10 24 50 PM" src="https://user-images.githubusercontent.com/42476338/199274893-a24d84b6-32c7-4e11-b029-9f657df6e6dd.png">

**Comment by amanda-phet** [comment]
The style of the notebook looks good to me. I think we should use more spiral loops, though. Can you use 8 instead of 6? 

![image](https://user-images.githubusercontent.com/7852916/200892394-e87e64f0-8057-4588-8da1-45797b6a6e96.png)

**Comment by amanda-phet** [comment]
I also want to note that I'd like a softer color for the paper and not pure white. Did you try #F0F0F0? That's what the paper was previously.

**Comment by marlitas** [comment]
@amanda-phet we can definitely make these changes. Do you want these changes to be included in the prototype for the Intro Screen, or just as we move forward?

**Comment by marlitas** [comment]
On Slack:
@amanda-phet 
> If you're going to do another RC anyway, can we include this as a change?

@marlitas 
> Yeah for sure! I’ll make that change and ping you when it’s done. :slightly_smiling_face:

**Comment by marlitas** [comment]
Those changes are applied and pushed up. @amanda-phet can you confirm this change or not? If yes, I can mark this for cherry-pick for RC 2.

**Comment by KatieWoe** [comment]
Looks good in rc.2. Closing
