### ISSUE TITLE
Omit options that a subclass is responsible for

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#103]
Notices while reviewing #44 ...

There are a number of places where Nodes are responsible for setting `children` and other options.  Those options should be omitted from the superclass options.

Here are the ones that I notices, possibly not a complete list:

- [x] SyncButton.ts:  omit 'children' | 'baseColor' | 'accessibleName' from RectangularPushButtonOptions? `children` certainly should not be overrideable by the caller. I'm not sure about the other two options.

- [x] PipeNode.ts: omit `'visibleProperty' | 'children' from NodeOptions

- [x] PredictMeanSlider.ts: omit `'children' from ParentOptions

- [x] WaterCup2DNode.ts: omit `'children' from NodeOptions

- [x] WaterCup3DNode.ts: omit `'children' from NodeOptions

- [x] LevelingOutScreenViewOptions.ts: omit `'children' from MeanShareAndBalanceScreenViewOptions

**Comment by marlitas** [comment]
Went through all implementations I could find of subclass setting parent options. @pixelzoom can you review, and close if all looks good?

**Comment by pixelzoom** [comment]
👍🏻 closing
