### ISSUE TITLE
Can we use the same people art as Center-and-variability?

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#105]
@samreid and I looked through the `playerStanding` pngs in Center and Variability, and they look very similar to the people in the Leveling Out Screen mockup. Can we use the same art and just copy them over?

Here are some examples of the people:

<img width="275" alt="Screen Shot 2022-08-30 at 10 55 36 AM" src="https://user-images.githubusercontent.com/42476338/187509117-9e8d58db-344a-4cc5-99bb-ecab7a0f598a.png">
<img width="308" alt="Screen Shot 2022-08-30 at 10 55 52 AM" src="https://user-images.githubusercontent.com/42476338/187509168-2147cb19-b51e-43ef-8538-01fb90d1619f.png">
<img width="308" alt="Screen Shot 2022-08-30 at 10 55 45 AM" src="https://user-images.githubusercontent.com/42476338/187509158-d1594316-4f8b-40fc-8b4b-aeed37ce6fbd.png">

The mockup from our latest meeting:
<img width="622" alt="Screen Shot 2022-08-30 at 10 56 59 AM" src="https://user-images.githubusercontent.com/42476338/187509345-863ce786-fafc-41f4-b486-135a23b743f0.png">

**Comment by marlitas** [comment]
@amanda-phet We also noticed they face in different directions, but that is very easy to fix in code.

**Comment by amanda-phet** [comment]
Yes! I was planning to reuse those people. I might use slightly different stances, so let me review the different iterations that we have and pick 7 for this sim. 

It's very easy for me to flip the artwork to face either direction, so we can decide what we like best and do that- person to the left or to the right of their plate.

**Comment by marlitas** [comment]
Okay great. We'll hold off on implementing that artwork until then. Would you want it to be the same person associated with each place in line, or have that be random?

**Comment by amanda-phet** [comment]
I think it is simplest to keep the same people in positions 1-7 every time you use the sim.

**Comment by amanda-phet** [comment]
Here are some people to use! The artboards are the same width and should have the people aligned so you can put them all in the same places with respect to the plates, but their heights vary. Let me know if you have any issues and I'll try to figure it out. 

![person-01](https://user-images.githubusercontent.com/7852916/188234153-53d4e294-a406-4a59-a808-135faf598475.png)
![person-02](https://user-images.githubusercontent.com/7852916/188234150-3f68203e-6341-4720-bb47-d8f53e74f158.png)
![person-03](https://user-images.githubusercontent.com/7852916/188234154-15e14390-401b-4bc6-af2d-29a2ec8ce6fc.png)
![person-04](https://user-images.githubusercontent.com/7852916/188234155-e31b8c48-a218-4883-b118-0720dd6e47ec.png)
![person-05](https://user-images.githubusercontent.com/7852916/188234157-ea8e1af1-97f3-4aff-bf62-5a0dc582ded0.png)
![person-06](https://user-images.githubusercontent.com/7852916/188234158-ea04d431-c9be-401b-897c-ea751fc69334.png)
![person-07](https://user-images.githubusercontent.com/7852916/188234160-7aa49fd6-6d3e-4b34-b859-98a56b130e9b.png)

**Comment by marlitas** [comment]
All the people art is added in. Sending back to @amanda-phet for feedback. Feel free to close if all seems well with the placement and look of the people art.

**Comment by jbphet** [comment]
@marlitas and I were just reviewing this issue and we'd like to try to draw the images from the soccer-common repo to avoid duplication.  That will be our next step.

**Comment by marlitas** [comment]
@amanda-phet Can we get exports of the soccer-common artwork as svgs so I don't have to redo all the imports later?

**Comment by marlitas** [comment]
Perfect. I'll go ahead and unassign myself and mark on hold until we get artwork back from Mariah. Thanks!

**Comment by marlitas** [comment]
Fixed here: https://github.com/phetsims/soccer-common/issues/13
