### ISSUE TITLE
Allocation of chocolate bars

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#106]
In https://github.com/phetsims/mean-share-and-balance/issues/60 @pixelzoom said:

> I would strongly reconsider this approach. There is a well-know maximum number of cups, and it's not a large number (7). So it would be much simpler to allocate the max cups once, then use the ones that are needed.

@marlitas and I have discussed using the same static allocation for the chocolate bars.  We got such a big benefit from this strategy on the water screen and we thought it would be OK here as well. It seems the main distinguishing factor is the number of items, but I don't think that needs to be the deciding factor.  Also, if necessary, we could experiment with a studio pattern where it only shows the values in the tree where `isActiveProperty` is true.

@pixelzoom @amanda-phet @kathy-phet OK to start with static allocation here?

Also mentioning @marlitas so she is aware.

**Comment by pixelzoom** [comment]
How many chocolate bars are there?

**Comment by samreid** [comment]
I believe it maxes out at 7 people * 10 bars each = 70.  (Just talking about the chocolate in the "top representation" paper at the moment).

**Comment by pixelzoom** [comment]
70 still seems like a fine number to allocated statically.  I'd make sure they are under a "chocolateBars" tandem, so that they can be collapsed and won't obscure other elements.

You might consider grouping pipes, 2Dcups, and 3Dcups under a parent tandem similarly.

**Comment by marlitas** [comment]
It has been decided to use static allocation and this issue now seems vestigial. I will close, but feel free to reopen if I missed something.
