### ISSUE TITLE
Can no longer press and hold to change number of cups

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#109]
**Test device**
MacBook Air m1 chip

**Operating System**
12.5.1

**Browser**
safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/835, I can't press and hold to change the number of cups, unlike in earlier versions of the sim. 

**Visuals**

https://user-images.githubusercontent.com/87318828/191058334-e068afbf-f525-47d6-8931-c0172ebad2a9.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.8/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.8 2022-09-16 20:09:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1324x717
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
Change applied in the above commit. @Nancy-Salpepi can you confirm this is fixed?

**Comment by Nancy-Salpepi** [comment]
Looks good on master @marlitas! Sorry I missed this issue yesterday! I don't know why I didn't see it.

**Comment by marlitas** [comment]
No worries! Thanks for checking back. Closing as completed.
