### ISSUE TITLE
2D cups off center

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#110]
**Test device**
MacBook Air m1 chip

**Operating System**
macOS 12.5.1

**Browser**
safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/835, the cups aren't centered on the notebook paper. The 2D cups are loser to the right side. Perhaps, the shadow on the right was taken into account?

**Visuals**
<img width="779" alt="Screen Shot 2022-09-19 at 12 17 17 PM" src="https://user-images.githubusercontent.com/87318828/191065359-4c258234-22dd-4445-b384-fb88710e710b.png">
<img width="779" alt="Screen Shot 2022-09-19 at 12 17 46 PM" src="https://user-images.githubusercontent.com/87318828/191065382-84139c21-0d38-4487-8cd1-aa371790ca7a.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.8/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.8 2022-09-16 20:09:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1324x717
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
I also noticed that they looked off center on the table, but that seemed to be because the arrow was also taken into account with the cup width.

**Comment by marlitas** [comment]
@amanda-phet I would like to get your input on this before moving forward. 

- I remember we talked about removing one or both of the red lines... if that's the case do we still want the cups to center on the paper without including the shadow? Right now both the cups and the paper are centered on that play area, but I can shift one or both over to compensate for the shadow portion.
- Would you like cups centering on the table to include or exclude the water level arrow? Currently it is including the arrow.

**Comment by amanda-phet** [comment]
Discussed 10/17/22 and we're going to revise the paper artwork to address this and https://github.com/phetsims/mean-share-and-balance/issues/111, and we are going to nudge thing around so they look more centered. 

I'll leave this assigned to me to deliver new artwork.

**Comment by KatieWoe** [comment]
The 3D cups are also seemingly off center on the table. Should this be looked at as well? For https://github.com/phetsims/qa/issues/848
<img width="587" alt="offsides" src="https://user-images.githubusercontent.com/41024075/199317963-ea112663-7755-47bd-9bf4-95d3b66e1760.png">

**Comment by marlitas** [comment]
I think when we looked at this we thought the centering on the table was fine but now I'm questioning if I'm remembering correctly? @amanda-phet thoughts? 

I think bringing this up for https://github.com/phetsims/qa/issues/848 is reasonable, especially if it feels off center from the top as well.

**Comment by Nancy-Salpepi** [comment]
They might not be centered on the table, but they are perfectly aligned with the 2D cups above. Moving them might make things looks more off.

**Comment by marlitas** [comment]
This issue feels vestigial now that we have the notepad artwork... I'm going to close but feel free to reopen if there's anything I missed.
