### ISSUE TITLE
Water level lines blend in with notebook paper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#111]
**Test device**
MacBook Air m1 chip

**Operating System**
macOS 12.5.1

**Browser**
safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/835, the line color for the cup water levels and the lines on the paper are very similar in color. It is easy to miss that the water level lines are even there--especially since the default amount of 1/2 cup is exactly where the paper line is. Do you agree that the water level lines get lost?

**Steps to reproduce**
Here is an example:
1. Click the valve or toggle to share the water
2. Check the Cup Water Level checkbox
3. Add more cups

**Visuals**

https://user-images.githubusercontent.com/87318828/191069421-0478efc5-7725-4fcf-a5f7-81ab72dec931.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.8/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.8 2022-09-16 20:09:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1324x717
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by amanda-phet** [comment]
I commented in a duplicate issue: 
>I'm starting to think the notebook lines are doing more harm than good. I know we discussed changing the line spacing to line up with the tick marks, but this issue seems like it would still need addressing. I might want to try notebook paper with no lines and see how that feels. 

I will need to think about what to do here, because the water level line should be blue. I think changing the paper is going to be part of the solution.

**Comment by amanda-phet** [comment]
Discussed 10/17/22 and we're going to try removing the lines that intersect with the cups so there is no interference.

**Comment by marlitas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Screen 2 Feature Complete](https://trello.com/c/TjWnLVXn/11-screen-2-feature-complete)

**Comment by marlitas** [comment]
The prototype was published with notepad artwork that does not have any lines on it. I believe this issue can be closed.
