### ISSUE TITLE
table looks like it is missing legs with narrow window size

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#114]
**Test device**
MacBook Air m1 chip

**Operating System**
macOS 12.5.1

**Browser**
safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/835, if I narrow the window size, space is added between the table top and the bottom nav bar of the sim making the table look odd. I compared this to Energy Forms and Changes, which also has objects on a table top. There, space was only added to the top of play area.

**Visuals**

<img width="600" alt="Screen Shot 2022-09-19 at 2 27 57 PM" src="https://user-images.githubusercontent.com/87318828/191089205-9a0aeef3-5993-4ff4-a651-06169b99b19f.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.8/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.8 2022-09-16 20:09:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1324x717
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
Hmmm... So I implemented the same functionality that energy forms and changes has to this screen and I'm not sure I'm a fan... maybe because we have a paper representation in the upper portion of the play area that is very different to Energy Forms and Changes. 

I keep having issues with github allowing me to upload videos so I will send this through Slack/Try again in an hour.

**Comment by amanda-phet** [comment]
Maybe we could ask Mariah to provide a full desk for the artwork.

**Comment by marlitas** [comment]
@amanda-phet I sent you the videos through Slack. I also wanted to put my comments from Slack here so that we can keep a record of them. 

> Here are two videos showcasing the Energy Forms and Changes method of dealing with the table bottom, and I also tried a version that makes the table look infinite with a rectangle the same color as the table. Not sure if either are the right approach.

> I saw you also mentioned having Mariah add legs, but I wanted to check in on wether those legs would have an ending spot, or they would be infinite? If they have an ending spot would the table look likes it’s floating in the air?

**Comment by marlitas** [comment]
The videos uploaded! Here they are:

https://user-images.githubusercontent.com/42476338/194962415-a3848793-6c3d-471e-b557-8a4134f35589.mov


https://user-images.githubusercontent.com/42476338/194962444-b314e21b-8bb3-418c-a3c4-4a289501c020.mov

**Comment by amanda-phet** [comment]
Thanks for uploading these videos and our conversation. Here is more: 

> Amanda McGarry
> I was suggesting Mariah provide the entire desk. So, it wouldn’t exactly have “legs” and would still be floating at a certain point, but it would at least look like a complete piece of furniture.
> 
> These situations are rare, so I’m not really worried about this extreme case, but I do think we need something to address a slightly narrower window (perhaps an iPad in vertical orientation as the worst case that we still want to look acceptable)
> 
> Marla Schulz
> Okay sounds good. I’ll wait for new artwork for the table then. Thanks Amanda!
> 
> Amanda McGarry
> I haven’t asked Mariah for it yet (still waiting on the other artwork anyway), but just offered it as an option. Do you think it is a good idea? Or should we go with one of the options you showed in yourvideos?
> 
> Marla Schulz
> Mmm I think it could work... I'm not sure what the usual policy is with stuff like that on phet sims. There is a point where a floating table might look weird but like you mentioned maybe that display range isn't common enough for it to matter? I'm not a fan of the keeping the table at the bottom option. I think our best options right now are the infinite rectangle or finishing the table off to look like one piece of furniture.


I agree with Marla- either the infinite rectangle approach, or just have a desk that could possibly look like it's floating if the window is extremely narrow (such as a vertical phone or iPad). 

For now, @marlitas could you keep the "infinite rectangle" on master so I can play with it a bit?

**Comment by marlitas** [comment]
@amanda-phet the "infinite rectangle" is on master so should be good to go for you to mess with it and see what you think. I'm going to assign you to this issue as well so that it's on our radar for next week.

**Comment by Nancy-Salpepi** [comment]
@marla the changes you made to the desk look really good in 1.0.0-rc.1!

**Comment by marlitas** [comment]
@Nancy-Salpepi that's great to hear! That sounds like this issue is ready to close then. @amanda-phet feel free to re-open if you have other thoughts.
