### ISSUE TITLE
Prediction control placement in focus order

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#117]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/835
I noticed that the control for the prediction line is after all the checkboxes and the add/remove cup controls. This makes some sense since you need to add it with a checkbox and you may want to be after that box in ordering, but visually it is a bit odd since the line itself is in the play area. I had a bit of confusion when trying to find the control during testing. May be the best solution, but I thought it would be good to keep an eye out.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.8/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.8 2022-09-16 20:09:53 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
@amanda-phet what are your thoughts on this? I know we briefly discussed and in the moment it made sense to place the prediction line after all the checkboxes, but if this is a confusing UX perhaps we need to change it?

**Comment by marlitas** [comment]
This is discussed in the issue: https://github.com/phetsims/mean-share-and-balance/issues/76

We decided to move the predictMeanSliders placement in the traversal order so that it comes at the end of the play area. Closing as completed in https://github.com/phetsims/mean-share-and-balance/issues/76 commits.
