### ISSUE TITLE
artifacts seen with latest macOS + safari

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#122]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0

**Browser**
Safari 16.1

**Problem description**
https://github.com/phetsims/qa/issues/848 
I am noticing artifacts when changing water levels. Going back to earlier dev versions, I see them there too. On my mac desktop, macOS 10.15.7 + safari 15.6.1, I don't see them. Thus, it seems due to this newest version of MacOS + safari. 

I also see them on the iPad with the newest iOS if changing water levels while zoomed in. 

**Steps to reproduce**
Using the newest macOS + safari, change the water levels of the 3D cups.
Fill the cup completely before reducing the water level. 
Repeat several times until lines appear.

**Visuals**
<img width="449" alt="Screenshot 2022-11-02 at 1 27 49 PM" src="https://user-images.githubusercontent.com/87318828/199562540-487876d9-afe5-4cf9-9c97-dce90cc6c4da.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-rc.1/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-rc.1 2022-11-01 17:03:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Language: en-US
Window: 1328x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
Here's a patch that might not work:

<details>

```diff
Index: js/BeakerNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/BeakerNode.ts b/js/BeakerNode.ts
--- a/js/BeakerNode.ts	(revision 2a50e6082a144a994109c41829030185f11adc22)
+++ b/js/BeakerNode.ts	(date 1667842418417)
@@ -11,10 +11,11 @@
 import { Shape } from '../../kite/js/imports.js';
 import SceneryPhetColors from './SceneryPhetColors.js';
 import sceneryPhet from './sceneryPhet.js';
-import { Color, TColor, Node, NodeOptions, Path } from '../../scenery/js/imports.js';
+import { Color, TColor, Node, NodeOptions, Path, Rectangle } from '../../scenery/js/imports.js';
 import optionize from '../../phet-core/js/optionize.js';
 import { RangedProperty } from '../../axon/js/NumberProperty.js';
 import StrictOmit from '../../phet-core/js/types/StrictOmit.js';
+import Bounds2 from '../../dot/js/Bounds2.js';
 
 type SelfOptions = {
   emptyBeakerFill?: TColor;
@@ -102,6 +103,15 @@
       fill: options.solutionFill,
       pickable: false
     } );
+
+    const solutionSideAntiArtifactRectangle = new Path( null, {
+      fill: 'red',
+      opacity: 0,
+      pickable: false,
+      stroke: 'black',
+      lineWidth: 4
+    } );
+
     const solutionTop = new Path( null, {
       fill: options.solutionFill,
       pickable: false
@@ -187,6 +197,7 @@
 
       solutionTop.shape = solutionTopShape;
       solutionSide.shape = solutionSideShape;
+      solutionSideAntiArtifactRectangle.shape = Shape.bounds( new Bounds2( -xRadius + 2, centerTop, xRadius - 2, centerBottom ) );
       solutionFrontEdge.shape = solutionFrontEdgeShape;
       solutionBackEdge.shape = solutionBackEdgeShape;
       solutionGlare.shape = solutionCrescentShape;
@@ -222,6 +233,7 @@
       beakerBack,
       beakerBottom,
       solutionSide,
+      solutionSideAntiArtifactRectangle,
       solutionBackEdge,
       solutionTop,
       solutionGlare,
```
</details>

**Comment by marlitas** [comment]
@Nancy-Salpepi  We pushed up a solution to master. Can you check on your end that this has fixed artifacts in Safari? Thanks!

**Comment by Nancy-Salpepi** [comment]
I wasn't able to produce any artifacts with mac/iPad + safari on master.

**Comment by marlitas** [comment]
Great. I'll keep this open for the next RC round so we can keep an eye on the behavior. Marking this for cherry picking.

**Comment by marlitas** [comment]
@samreid and I decided to revert the commit that fixes this issue, since a general fix is on it's way from @jonathanolson.

**Comment by marlitas** [comment]
@Nancy-Salpepi we reverted the commit that fixed this for the RC since a maintenance fix will be needed for all sims. I will double check that commit got reverted on master too.

**Comment by marlitas** [comment]
This got fixed and addressed in another issue correct? @Nancy-Salpepi, I believe this can be closed now?

**Comment by Nancy-Salpepi** [comment]
I'm not seeing any artifacts with macOS 14.2.1 + safari 17.2.1 or iPadOS 17.2
Closing!
