### ISSUE TITLE
Water Level Arrow location seems off

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#123]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0

**Browser**
Safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/848, the location of the water level arrows seems off. 

Here they are in the last dev test:

<img width="242" alt="Screenshot 2022-11-02 at 1 58 13 PM" src="https://user-images.githubusercontent.com/87318828/199566891-c3830eb6-5aa6-4808-b564-86ef59c8b92c.png">

And here they are in RC.1:
<img width="229" alt="Screenshot 2022-11-02 at 1 58 49 PM" src="https://user-images.githubusercontent.com/87318828/199566999-88425ca9-9580-48b8-8ade-e5b12a3fd258.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-rc.1/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-rc.1 2022-11-01 17:03:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Language: en-US
Window: 1328x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
@Nancy-Salpepi This should be corrected on master now, can you confirm? Will mark for cherry-pick if all looks good.

**Comment by Nancy-Salpepi** [comment]
Looks good on master @marlitas!

**Comment by KatieWoe** [comment]
Looks good in RC 2
