### ISSUE TITLE
Should dropped chocolate bars animate or instant-jump?

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#128]
Currently in the Leveling Out screen, a dropped chocolate bar instantly jumps to the target location.  That was easiest to program first and seems like a good user experience.  It seems very clear what is happening and has a "feel" of animation.  However, in other sims, we do show an animation sequence while things fly around.  It would not be trivial to implement and we are uncertain whether that would be worthwhile here.

**Comment by jbphet** [comment]
@marlitas and I discussed this, and we vaguely recall that we collectively decided to make these animate in a recent design meeting.

**Comment by jbphet** [comment]
This has been superseded by https://github.com/phetsims/mean-share-and-balance/issues/139.  Closing.
