### ISSUE TITLE
Improve multitouch support when adding/removing cups/people

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#129]
In https://github.com/phetsims/mean-share-and-balance/issues/91 we agreed to interrupt subtree input when a cup or person is added or removed.  That was a straightforward solution to avoid bugs related to changing a non-existent object.  However, multitouch support could be improved by making it so that input is only interrupted on the removed cup/person.  That way one touch event can keep mutating cup_0 while cup_4 is added and removed.  This is a proposed enhancement, and should only be implemented if it can be done without excessive effort.

Perhaps review each occurrence of `interruptSubtreeInput` to see which are appropriate.

**Comment by jbphet** [comment]
@marlitas and I just reviewed this issue and evaluated the current multi-touch behavior, and we feel like adding the ability to add or remove cups while interacting with other cups wouldn't add much value to the user experience.  Based on that evaluation, we are deciding to close this issue as "won't fix".
