### ISSUE TITLE
Animate the candy bar movements in the notepad on the 2nd screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#139]
In issue #128 we decided that the dropping of the candy bars (previously chocolate bars) should be animated.  As we discussed this further, we realized that there are several cases that should be animated.  Here is a list (which may not be complete):

- Dropping the candy bars and having them move to the appropriate stack
- Pressing the "Sync" button and moving the bars to other plates
- Removing a person and having them "take their candy bars and go home"
- Grabbing bars out of the middle or bottom of the stack (the other bars should animate downward)

**Comment by jbphet** [comment]
@marlitas and I reviewed the list above, and we're estimating that it will take a significant effort to implement all of these.  We have an alternative and much simpler proposal.  Leave the animation out, and add an offset to the dragging of the bars in the notepad so that it is more apparent when one is grabbed.  This will help with the 4th item on the list.

The other three items sound challenging to implement, and after playing with it for a bit, they don't seem like they'd be particularly helpful.  Also, the recent addition of the dotted lines to the notepad stacks to have them better match the plates on the table seems to make it easier to keep track of what is going where.

@amanda-phet - can you please offer your thoughts on this?  Please set up a meeting if you'd like to discuss with @marlitas and me.

**Comment by amanda-phet** [comment]
I just played with this on phettest and I'd say the lack of animations is working out fine. IMO, adding animations can make things feel like a high-end simulation, but aren't necessary when the cost is really high. With that said, the first item in the bullet list (Dropping the candy bars and having them move to the appropriate stack) is the one I think would add the most impact and would feel similar to other sims with drag and drop behaviors. Bullets 2-4 can be nixed. I am fine with coming back to bullet 1 as a "polish" to this sim, and leaving things as they are now to see how quickly we can get the sim feature-complete.

**Comment by jbphet** [comment]
I went ahead and added animation for the basic drop situation since @marlitas and I had done some initial investigation, and I thought I might as well do it while it was fresh in my mind.  @amanda-phet - please try it out and let us know what you think.

**Comment by amanda-phet** [comment]
It looks great!! Thanks for adding that. 

Should we go ahead and close this issue? If we want to make tweaks maybe we open another polishing issue, but I think it looks great.

**Comment by marlitas** [comment]
Great! The above commit cleans up some of the code. Behavior remains the same. I think we're ready to close.
