### ISSUE TITLE
Clean up phet-io instrumentation for Screens 2 & 3

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#140]
It is obvious that the LevelingOut screen was left in a half baked state for phet-io. There are a couple of weirdnesses that would be good to keep track of as we're cleaning up other parts of the model first, so this issue will track those questions and TODOs.

**Comment by marlitas** [comment]
On hold until refactor is complete.

**Comment by marlitas** [comment]
Refactor is done. Starting this up again.

**Comment by marlitas** [comment]
This commit accidentally snuck into another issue but should actually be tied here: https://github.com/phetsims/mean-share-and-balance/commit/befb17c1f36d8182e58c46bafc15f71364c05bfd

**Comment by marlitas** [comment]
I think this is ready to close... @jbphet do you want to review this, or just assume it will be covered by an upcoming self-code review of the full sim?

**Comment by jbphet** [comment]
I spot checked several commits, and they looked fine, so I'm okay to close this and review all the phet-io behavior and code once we're a little closer to publication.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by jbphet** [comment]
Looks like there are still some TODOs associated with this issue.

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/2059a433-b90e-4075-9181-38a6abbf05a8)

Back to you @marlitas to have a look at them.

**Comment by marlitas** [comment]
Some were vestigial, and I addressed the animation one. This is ready to close again.
