### ISSUE TITLE
TablePlateNode layout is really convoluted

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#145]
I attempted to quickly update the position of the numberPicker in relationship to the TablePlate and it was not a straightforward procedure. The layout should be reworked to make maintenance and adjustments easier in the future. Most of the layout seems to be happening through a combination of `TablePlateNode` and `LevelingOutScreenView`.

**Comment by marlitas** [comment]
I got the layout to be a bit more intuitive, but I had some questions about the partyTable asset we have vs. the one in the design doc. 

The table cloth doesn't go as far down as the design doc version. We can draw it in code to do that, but wanted to see if that was the desire first.
Layout with current table:
<img width="949" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/88f4f8bf-1d85-4c60-b2a5-7a972acdb319">

**Comment by amanda-phet** [comment]
I have the updated table. Since we are going to do svgs, I was waiting on re-exporting everything, but the table I went ahead and did so you could wrap up this issue. 


![partyTable](https://github.com/phetsims/mean-share-and-balance/assets/7852916/752c521e-c578-4b62-aa11-e510d3f2e9f7)
