### ISSUE TITLE
Should CandyBars have a drop shadow?

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#147]
According to design doc candy bars should have a drop shadow:
<img width="629" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/bb8c0469-7887-466c-9e34-51608537049c">

@jbphet and I tried this and we're not sure...
<img width="611" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/b4de4979-8559-4b65-a8d0-089bb710d15a">

@amanda-phet what are your thoughts here?

**Comment by marlitas** [comment]
The shadow is now committed on main.

**Comment by jbphet** [comment]
Over to you @amanda-phet for review and feedback on the feature.

**Comment by marlitas** [comment]
Checked in with @amanda-phet, and we liked it. Closing.

**Comment by marlitas** [comment]
We talked more and actually want to do this:
- Only show drop shadow when dragging.

**Comment by marlitas** [comment]
@amanda-phet, the behavior is now on main. Over to you to review. Go ahead and close if all looks well.

**Comment by jbphet** [comment]
@marlitas and I reviewed this synchronously with @amanda-phet, made some adjustments, and it's now approved.  Closing.
