### ISSUE TITLE
Leveling Out screen polishes

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#148]
- [x] Ideally the notepad  should be in same place on all screens, and right now it shifts slightly between Intro and Leveling Out 
- [x] accordion box artwork should be drawn rectangles, not the candy bar artwork
- [x] mean dialog could use polishing- title and text are currently very small
- [x] number pickers should be black, not blue

The rest of my polishes already got handled! 

I do still need to provide the updated table artwork, people, candy bars, and will likely handle all artwork at once.

**Comment by jbphet** [comment]
@amanda-phet - We've taken a shot at the list of items above.  Please review and let @marlitas and I know if you'd like any refinements on these items or close the issue if you're good with the changes.

**Comment by amanda-phet** [comment]
These look good, thanks!
