### ISSUE TITLE
Fair Share Screen Sprint

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#149]
This issue will tackle the initial commits for the Fair Share Screen.

**Comment by marlitas** [comment]
To Do:

- [ ] Generalize things that need to be generalized from LevelingOut https://github.com/phetsims/mean-share-and-balance/issues/138
- [ ] Get artwork for apple
- [ ] People, plates, and apples appearing/stacking on the party table.
- [ ] Generalize mean accordion box and use fractions and circle graphic
- [ ] Sync, Collect, Share states in model and view
- [ ] Implement redistribution algorithms for the Sync, Collect, and Share states
- [ ] Animation between the Sync, Collect, and Share states


**This is not a fully comprehensive list... just a starting point

**Comment by marlitas** [comment]
We are wanting to do a self code review of the Fair Share screen code before closing.

**Comment by jbphet** [comment]
Self review complete, closing.
