### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#15]
As @samreid and I were working on animating the water levels, Sam pointed out that adding some  water sounds and valve turning sounds to this sim may be a good addition. 

We are wondering if sound is a consideration at this point for the Sim?

A couple of thoughts:
- Sound could help students with an aural understanding of the water discrepancies.
- Currently the animation is non-linear which would make programming how long a water sound should last complicated.
- A sound to indicate a pipe has been clicked/ is turning.
- A different sound for opening or closing? We don't know.

**Comment by amanda-phet** [comment]
This is a question for @kathy-phet and if sound design is a priority for this sim or not. My understanding is that there is a process that is usually followed, and it does add time to design/development, and I am not positive about the total funding for this sim. 

I would love to incorporate more sound into all of our sims though!

**Comment by jbphet** [comment]
It has been decided that yes, we are doing sound for this sim (it is in the list of supported features in the spec).  We'll close this issue and open a new one with the Checklist for Adding Sound.
