### ISSUE TITLE
Consolidate `NotepadNode` and `NotepadWithReadoutNode`

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#150]
`NotepadNode` and `NotepadWithReadoutNode` are currently two separate types (one that uses the other through composition).  @marlitas and I are thinking it would be better to consolidate these and to control the behavior (i.e. the presence of the readout, among other future things) through options.

**Comment by marlitas** [comment]
We reviewed these changes synchronously. Closing!
