### ISSUE TITLE
Alt-Input traversal order for Leveling Out & Fair Share

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#151]
We are starting to implement alt-input for the Leveling Out Screen. What would you like the traversal order to be @amanda-phet?

**Comment by marlitas** [comment]
I started working on Fair Share as well. There's a prototype traversal order on main now for the first three screens, but we can change things as feels best.

**Comment by amanda-phet** [comment]
This is looking good to me. One thing I'm torn about is when additional cups/people get added. I'd like to consider moving the number cups/people spinner to right after playing with the data (so, right after the water level triangles and right after the number pickers).

**Comment by marlitas** [comment]
Great! The traversal order has been updated to match the request. Over to @amanda-phet for review.

**Comment by catherinecarter** [comment]
I played with the tab order a bit, and I'm not sure of the ideal order, but I did expect the notebook area would come right before or after changing the number of objects (people or number of chocolate bars) in the bottom area. 

For example, on the Leveling Out screen, when I tabbed forward after changing the number of people at the table, the next stop was the mean accordion box. To get back to the notebook where I could try and figure out the mean myself, I had to back-tab through all the people before getting to the play area. Having the mean accordion box be the first tab stop after changing the number of people inspired me to open the accordion box and see the mean before I had the chance to guess for myself. So the order that my brain was expecting was something like: 
- people first to change the number of chocolate bars, if desired
- number of people spinner
- notebook so I can predict the mean
- Mean accordion box to check my work

Or, maybe 
- the notebook would come first
- then the people spinner
- then the people 
- then the mean accordion box? 

My goal in either situation would be to have the number of people spinner be between the notebook and the people so you could tab/back tab between the people and the notebook with just one stop in between.

**Comment by marlitas** [comment]
Mmm... We should have a conversation about this. The people spinner is currently in the `pdomControlArea`, and with layout it's bundled in with the other controls... I may be able to do some finagling to pull it out to be in the `pdomPlayArea` instead but it feels odd. Maybe it's just cause I'm not used to that pattern yet?

I'm marking for an in person check-in tomorrow so that we don't uproot the code if we don't need to.

**Comment by marlitas** [comment]
2/21/24 Meeting:
- @amanda-phet  is going to check with @terracoda on the current traversal order. 
- We also talked about how the NumberSpinner should live in the pdomPlayArea instead of pdomControlArea.

**Comment by terracoda** [comment]
When determining traversal order/Play Area/ Control Area, I think it is helpful to look at the sim with thA11y View Tool. 

In addition to order, it points out odd things, like on screen one, why there are 2 separate Tab Stops (two different buttons) controlling the same thing - the flow between the water in the notebooks. In one case the button is in the Play Area and in the second case, the button is at the end of the Control Area. I personally feel there is no need for a secondary switch-like button. If students are not clicking on the icon connecting the bottles, I think the Interactive Highlights feature and/or visual changes to the connected bottle buttons could solve that issue.

Here's a screenshot of the Intro Screen with the A11y View Tool:
![Screenshot 2024-03-22 at 10 10 02](https://github.com/phetsims/mean-share-and-balance/assets/1902116/5e71c630-42e9-485e-b341-e5ac01389a85)

Not knowing much about the learning goals, it seems to seems to me the number of cups (or people and plates) is pretty essential to "playing", so the Number of cups number spinner should be in the Play Area. 

On the Intro Screen, I think it would be best to put the Number of cups in the Play Area and remove the additional switch-like toggle button all together from the screen.

On screens 2 and 3, you have the notebook stuff first. I am not sure why you have flipped it? You have to shift Tab backwards to sort the Chocolate bars or play with the radio buttons.

I am not sure what the Sync button is supposed to do on screen 2, so not sure where it should go.

On both 2 and 3, the people and plates are very "connected" to the number spinners that control the servings of chocolate bars/apples, so I think it would make sense for the people/plates were in the Play Area.

I like that you have already included some accessible names at this stage (Awesome!). I challenge you to think about what you might call the stacks of chocolate bars in the Notebook on screen 2 or the group of radiobuttons in the Notebook on screen 3? It might be good to think of those now - it might help conceptually with the interactions and even for lesson design.

You said not to look at screen 4.

**Comment by amanda-phet** [comment]
Thanks for your review @terracoda ! 

>Not knowing much about the learning goals, it seems to seems to me the number of cups (or people and plates) is pretty essential to "playing", so the Number of cups number spinner should be in the Play Area.

That is the plan, but I think the developers were waiting on confirming the traversal order. Do you think that the order makes sense? 

>On the Intro Screen, I think it would be best to [...] remove the additional switch-like toggle button all together from the screen.

That's an interesting thought. I have wondered about this too, and if it's confusing in the PDOM that's a good indication it's not a wise choice to have the two controls. 

>On screens 2 and 3, you have the notebook stuff first. I am not sure why you have flipped it? You have to shift Tab backwards to sort the Chocolate bars or play with the radio buttons.

In those screens I think leveling out the bars/apples is a reasonable first action, but I agree that it should be consistent. Depending on what I see in interviews I will make a change so all of the screens are consistent.

**Comment by amanda-phet** [comment]
I was waiting on interviews and the changes to the interface. We should probably discuss these points brought up by Taliesin: 

1. Should the first screen go to the valve first, to be consistent with the other screens? 
2. Should we remove the extra toggle with the valve, and just make the valve more appealing with a cue of some sort? 
3. Once we finalize it, let's confirm that the appropriate things are in the "play area" and "control panel"

**Comment by amanda-phet** [comment]
OK final change to make: On the Level Out screen, I think the order needs to start with the valve on the notebook, then go to the cup sliders. Everything else can stay the same.

**Comment by marlitas** [comment]
Updated. Over to @amanda-phet for final review.

**Comment by amanda-phet** [comment]
Great, thank you!
