### ISSUE TITLE
What should the calculation dialog look like when there are 0 balls?

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#154]
The mean calculation info dialog in Balance Point has a different scenario than the other screens because we can have 0 balls on the field while the minimum amount of plates in Leveling Out and Fair Share is one. Dividing by zero is obviously a no-no, so what do we want the dialog to look like when there aren't any data points on the field?

<img width="1053" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/17e0ae13-ae9f-4a6d-bd13-d8c85142264e">

**Comment by marlitas** [comment]
This affects the mean readout as well:
<img width="273" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/99d3b57b-b5bf-4b7f-bbae-d1e8a105fbaf">

**Comment by amanda-phet** [comment]
For the dialog: could we show something like "Kick some balls to calculate the mean" or "Need at least one kick" 

For the readout: let's just show Mean = ? as we do in CaV

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/dfe35d5f-1933-4433-9af4-59e7d3c5cf2d)

**Comment by marlitas** [comment]
This is ready for your review @amanda-phet. Feel free to close if all looks good!

**Comment by marlitas** [comment]
Met with @amanda-phet, we need to update the decimal reading in the info dialog to round to the nearest tenth. Everything else was reviewed and we will be good to close once that change is implemented.

**Comment by marlitas** [comment]
Decimal rounding updated. This is ready to close!
