### ISSUE TITLE
Improve look of the plates

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#155]
The plates on the Leveling Out and Fair Share screens look highly aliased on my main and auxiliary monitors.  Here is a screenshot from one of them:

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/bca85e8d-fe2f-45cd-9ae6-02706d55e550)

The artwork is currently a PNG file that is 551 pixels wide.  I think this is just getting scaled down too much to look good.  I'd suggest we either go with a smaller PNG or an SVG file that scales better.

**Comment by amanda-phet** [comment]
These will be SVG. I'll make a new issue to handle artwork so we can close this.
