### ISSUE TITLE
Artwork needed

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#156]
Artwork will be SVG. 

Here's a list that I think covers everything we need in SVG, but I'm not sure as some things may actually be in code, so I'll check with @marlitas 

- [x] party table 
- [x] desk
- [x] plates
- [x] candy bars
- [x] apples
- [x] people standing (all regions)
- [x] people kicking (all regions)
- [x] notepad ring
- [x] soccer ball (provide new svg asset)
- [x] collection box
- [x] sketched "plates"
- [x] screen icons (in the works)

**Comment by amanda-phet** [comment]
I just uploaded some new artwork! Let me know if there are issues integrating it. If all is good then feel free to unassigned. 

Also, it seems like we aren't using notepadPaperBackground.png and pencil.png. Can you delete those and update the license file?

**Comment by marlitas** [comment]
I deleted `notepadPaperBackground.png`, but `pencil.png` is being used by the prediction slider in the Intro Screen.

**Comment by amanda-phet** [comment]
Thanks! I thought you drew that pencil but now I see it's just rotated. Should I also make that an svg? It's pretty crisp when zoomed all the way in, but I am betting that it could be a smaller file if I make it an svg.

**Comment by marlitas** [comment]
I say go for it. SVG is the way of the future! 👽

**Comment by amanda-phet** [comment]
I just realized the people standing on the Leveling Out and Fair Share screens aren't coming from soccer-common. Can you use kickerxxStanding.svg for those people?

**Comment by amanda-phet** [comment]
More artwork was shared in https://github.com/phetsims/mean-share-and-balance/issues/175

**Comment by amanda-phet** [comment]
soccer ball was uploaded today to soccer-common. 

Here are the screen icons!
![balance-point-navbar-icon](https://github.com/phetsims/mean-share-and-balance/assets/7852916/8e54a121-0627-492e-9840-cf3caa040099)
![fair-share-navbar-icon](https://github.com/phetsims/mean-share-and-balance/assets/7852916/ca544872-8452-47eb-b945-f34cb794d602)
![distribute-navbar-icon](https://github.com/phetsims/mean-share-and-balance/assets/7852916/875ea0ec-11fc-4e8a-83f3-986ac7b29d9e)
![meansharescreens-05](https://github.com/phetsims/mean-share-and-balance/assets/7852916/6df60e4f-9fb4-4f76-93c1-3218dd03be0d)
![fair-share-screen-icon](https://github.com/phetsims/mean-share-and-balance/assets/7852916/ae7679ce-d2d5-4f29-b4e8-82b47f1f28b7)
![balance-point-screen-icon](https://github.com/phetsims/mean-share-and-balance/assets/7852916/4518494d-2a99-4399-9d7b-0c7fde066c2d)
![distribute-screen-icon](https://github.com/phetsims/mean-share-and-balance/assets/7852916/50e09492-36df-40bb-bb77-82899e0ead1d)
![level-out-screen-icon](https://github.com/phetsims/mean-share-and-balance/assets/7852916/18fb1d81-a521-4bab-8adc-c2d1ee707150)
 

Could you also update the artwork so that all of the people in the Distribute and Fair Share screens are pulling from soccer-common? We should be using the first 7 people named regionKickerNNStanding.

**Comment by jbphet** [comment]
The artwork above is integrated.  @amanda-phet - please have a look and make sure you like it in context.

@marlitas pointed out that there is a little line coming out of one of the apples.  I thought it might be a fruit fly ;-), but we thought we should point it out in case you want to revise.

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/20c118e0-9616-4ded-9ee6-bacc03c7895e)

**Comment by amanda-phet** [comment]
I noticed that too! And I remember seeing it in an export but thought I removed it, so I'll try again.

**Comment by amanda-phet** [comment]
@marlitas this got missed: 

>Could you also update the artwork so that all of the people in the Distribute and Fair Share screens are pulling from soccer-common? We should be using the first 7 people named regionKickerNNStanding.

**Comment by amanda-phet** [comment]
Updated the Fair Share home screen icon, so hopefully that looks better now.

**Comment by marlitas** [comment]
I believe everything in this issue has been addressed. The standing people in the Distribute and Fair Share screens now update with the Region and Culture selection as well. 

Over to @amanda-phet to review and close if all looks good.

**Comment by amanda-phet** [comment]
Yay, I'm glad the other regions are in there now. All looks good!
