### ISSUE TITLE
Mean mode should always balance the beam.

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#160]
It looks like it's probably a rounding error:

<img width="1034" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/cf66c190-d75a-47ac-a310-5a09bbafe2ab">

**Comment by jbphet** [comment]
Fixed.  It now looks like this when there is one ball at 5 and two at 10:

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/2f7f401a-7b59-4451-92ba-9c6c444e68eb)

I'll review with @marlitas before closing.

**Comment by marlitas** [comment]
We fixed this and reviewed synchronously. Closing!
