### ISSUE TITLE
Add animation for the tipping of the balance beam

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#164]
@amanda-phet, @marlitas, and I met this morn to discuss a few design aspects for this sim, and we decided to try animating some situations related to the balance beam in the 3rd screen.  Animation would be used when the supports are removed and potentially used when a new ball is kicked onto the field.  Animation will *not* be used when the movable fulcrum is being adjusted by the user, since the changes are small and quick and it almost looks animated already.

**Comment by amanda-phet** [comment]
This is really nice! I like it a lot. I'll go ahead and close since I don't have any change requests.
