### ISSUE TITLE
Add the clipping of the balance beam

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#165]
In the current main version the balance beam can be placed into a situation where it goes off the notepad, like this:

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/66587b16-c8ab-4a1c-ac1a-21e9d7c421a2)

We should add the clipping area for this, and we should try to layer things such that the edge of the clipping region is at the edge of the full notepad, and the line of the beam goes under (in the z-order) the notebook rings.  This matches what is currently shown in the design doc.

**Comment by jbphet** [comment]
I've added this, here's a screenshot of the current look:

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/b4d567cb-c86a-4759-b446-35ea0d5dc5dd)

**Comment by marlitas** [comment]
@jbphet and I reviewed together, and this is ready to close.
