### ISSUE TITLE
Dropped candy bar not animating

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#167]
In certain situations the candy bar immediately jumps to the plate when dropped instead of animating. The quickest way to reproduce:

- Load Leveling Out screen
- Grab candy bar from second plate
- Drag to the left and drop so that it lands on the first plate.

**Comment by jbphet** [comment]
@marlitas and I did some detective work and found that this was related to the sorting and ordering of the candy bars on the plates.  We added code to consistently sort the list of candy bars assigned to the plate, and this seems to have resolved the issue.  We also fixed a multi-touch issue where dropping multiple candy bars at the same time could cause them to land on top of one another.  This all seems to be working reasonably well at this point, so I'll close this issue, and will reopen if it's not truly fixed.
