### ISSUE TITLE
Add yellow cueing arrows to movable fulcrum

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#168]
After a ball has been kicked, yellow cueing arrows should appear on either side of the movable fulcrum until the fulcrum is moved by a user.

<img width="377" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/71cc3aa1-a982-4132-9ee2-af185239965a">

**Comment by jbphet** [comment]
@amanda-phet - the cueing arrows have been added.  Please check the behavior and appearance and let us know if you'd recommend any changes.
