### ISSUE TITLE
Self test multi-touch for screens 2-4.

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#169]
@amanda-phet will be using an ipad for interviews, so we want to confirm that multi-touch is working as expected in the sim.

**Comment by jbphet** [comment]
I found several cases where it was a bit tricky to interact with certain components, so I made some adjustments of touch areas.  Other than that, the sim seemed to handle touch pretty well, including multi-touch situations.  I also did some multi-touch fuzzing, and the sim didn't crash and didn't appear to get into any bad states.

Assigning to @amanda-phet in case there is anything else she'd like to have us test, or in case she'd like to try it out on an iPad prior to interviews.

**Comment by amanda-phet** [comment]
Not finding any issues with multi-touch! I did find a bug on Fair share when I was trying to be tricky, and can't reproduce it. I was changing a number picker while going from collect -> sync, and ended ups with floating apples. Can't get it to happen again though, and I'm sure QA will have fun with this screen :)
