### ISSUE TITLE
Should fractions be reduced on the "Fair Share" screen?

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#174]
While doing some testing I created the following state, and was wondering if it was what we want.  It shows 2/6 as the fractional value in the "Mean" accordion box, which could be reduced to 1/3.  I scanned through the design doc and didn't find anything specific about situations like this, so perhaps it wasn't anticipated. Should fractions be reduced when possible?

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/c28afd8d-1cb3-4e25-ac85-6a2aed3e57f6)

**Comment by marlitas** [comment]
We talked with @amanda-phet and we would like to reduce the fractions in both the mean accordion box and the info dialog. Over to @jbphet

**Comment by jbphet** [comment]
I've implemented reduction of fractions, here is what it looks like now:

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/19eec22d-dcfd-47e8-8094-fe8cb11937a3)

and

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/2d84f23a-ced7-4f7a-84b7-3d6c4473869a)

**Comment by jbphet** [comment]
This has been done, closing.
