### ISSUE TITLE
Integrate new artwork for sketch plates, sketch apples, and collection area

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#175]
@amanda-phet has been working on some new artwork for the notepad area in the sim. We want to integrate it in before interviews.

@jbphet will add in:
- apples
- collection area

@marlitas will add in:
- plates

**Comment by amanda-phet** [comment]
![collection](https://github.com/phetsims/mean-share-and-balance/assets/7852916/01c9d240-e523-4bce-bf02-e1906abef793)
![pencil-plate](https://github.com/phetsims/mean-share-and-balance/assets/7852916/acd2a3d6-84e7-4c67-b798-580b5a8ef88a)
![apple-fill](https://github.com/phetsims/mean-share-and-balance/assets/7852916/956705f5-3df4-4581-8a00-1f3e644cc25a)

**Comment by jbphet** [comment]
The updated artwork has been integrated.  Over to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Things look great! If we want to make further pixel polishes let's do that in another issue. These are great for interviews.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by marlitas** [comment]
Moved the TODOs to another issue: https://github.com/phetsims/mean-share-and-balance/issues/186
