### ISSUE TITLE
Add kick button below kicker

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#177]
We would like to add a Kick button (only kicks one ball at a time) to the Balance Point screen. This would be similar to CAV.

We are also considering clicking the kicker so that triggers a ball kick.

**Comment by marlitas** [comment]
I added the kick button... @amanda-phet would you like me to also add the functionality that a user could click on the Kicker?

**Comment by amanda-phet** [comment]
Button looks good! 

>would you like me to also add the functionality that a user could click on the Kicker?

Let's wait and see what happens in interviews.

**Comment by amanda-phet** [comment]
Actually- the kick button touches the navbar, which I didn't realize until I was on the iPad and confirmed on my laptop that resizing the browser window causes that to happen. 
![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/ca9ed8eb-76b2-4f26-ab6c-6954f30c6304)

Should the grass be taller? Or the button smaller?

**Comment by jbphet** [comment]
We discussed this, and @marlitas is going to keep the button size the same, since it matches the one used in Center & Variability, and will move the grass up just a little.

**Comment by marlitas** [comment]
Grass height adjusted. @amanda-phet feel free to close if all looks well.

<img width="1474" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/666c389f-ab72-4387-a31c-04b83a957042">

**Comment by amanda-phet** [comment]
Looks great! Thanks!
