### ISSUE TITLE
Use sketch line pattern for candy bars

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#180]
We want to use the same pattern for the notepad candy bar outline.

**Comment by marlitas** [comment]
This has been done, but I think we will want to tweak. It might work better if the pencil line is darker... I'm not sure. 

<img width="528" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/09c5feef-df1d-49c4-b358-e0f5e7a0958e">

**Comment by amanda-phet** [comment]
This is fine for now. I will leave it assigned to me to provide updated hex codes, but at a later date.

**Comment by amanda-phet** [comment]
Should we try a fill similar to the apples? 

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/c95c313c-01d6-4f5a-94cd-7be79656d630)

Once we have the cue to move these, it probably doesn't matter what they look like, so I can still work on picking a good solid fill color. But if we like the look of the circles on Fair Share we could do something similar here.

**Comment by marlitas** [comment]
Oh I like that! I say let's try it. I think it makes sense for them to match.

**Comment by amanda-phet** [comment]
OK here is a fill (it's darker brown to match the bars). I'd like to keep the gray sketchy outline too. Let's see how it looks!

![candy fill](https://github.com/phetsims/mean-share-and-balance/assets/7852916/c431bf85-3a7d-4672-b792-59418b5ea2a1)

**Comment by marlitas** [comment]
The sketch fill is added in!

**Comment by amanda-phet** [comment]
It's quite busy with all the sketchy rectangles, and harder to see when the stacks are the same height. I'm torn, because in theory I like this idea, but it just doesn't work as well here given the interactivity and goals. I could try something a bit less sketchy, but if the edges don't look solid I'm not sure it will work. 

Sorry, but let's revert this and go back to the solid fill. I liked the lighter brown we were using.

**Comment by amanda-phet** [comment]
I just saw my initial mockup isn't matching the svg I provided, so let me try one more time to make an svg that looks more like this: 
![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/2914162c-13b2-4cd6-8746-423bdca4ab64)

**Comment by amanda-phet** [comment]
Can we try this fill? 

![candy-fill](https://github.com/phetsims/mean-share-and-balance/assets/7852916/2c7cab60-1bdc-4f88-8b15-39473aaea408)

**Comment by amanda-phet** [comment]
Discussed this over slack and zoom and decided on this one, which @marlitas already put in. When it's ready to review on my end let me know! 

![candyBarFill](https://github.com/phetsims/mean-share-and-balance/assets/7852916/1df6a869-f78e-40bd-82fb-d449db6d3a88)

**Comment by marlitas** [comment]
This is ready for final approval! Over to @amanda-phet.

**Comment by amanda-phet** [comment]
I'm very happy with this. Closing!
