### ISSUE TITLE
Add cueing indicator for soccer balls

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#181]
We want the drag cue indicator to appear after all seven balls have been kicked. It should appear on the last kicked ball.

**Comment by marlitas** [comment]
This has been added. Over to @amanda-phet for review. 

One thing to note. The keyboard interaction for the soccer balls hasn't been fully implemented, and does affect the mouse cue logic at some points, so those tweaks will need to adjusted later.

**Comment by amanda-phet** [comment]
Looks good!
