### ISSUE TITLE
Implement a crossover of these two sounds for the water levels in the the seven glasses on screen one

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/mean-share-and-balance#182]
I have added these sounds in our shared audio folder for this sim.

- MSaBGlassLevelCrossfadeSound1.mp3
- MSaBGlassLevelCrossfadeSound2.mp3

We intend to try a crossfade between these sounds and use them for the pitch of the individual cups. Cup 1 would be 100% MSaBGlassLevelCrossfadeSound1.mp3, Cup 7 would be 100% MSaBGlassLevelCrossfadeSound2.mp3 and all of the cups in between would play somewhere in the middle as the crossfade shifts between.

**Comment by jbphet** [comment]
This appears to be duplicated in #183, so we're going to close this one.
