### ISSUE TITLE
Look in to this bug that caused the apples not to go back exactly to place

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/mean-share-and-balance#184]
Here is the video I took in action.

https://github.com/phetsims/mean-share-and-balance/assets/34492870/5b32194b-fa39-4633-9ed9-1c5b68212079

**Comment by jbphet** [comment]
This was fixed (I believe) when https://github.com/phetsims/mean-share-and-balance/issues/179 was addressed.  Closing.
