### ISSUE TITLE
Validate RangeProperty values

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#187]
We noticed that numberOfPlatesRange is a Property. Assuming this is so that clients can adjust the range if they'd like we would like to set up validators than make sure the min of the range can never change, and the max never goes above 7.

**Comment by marlitas** [comment]
I did the initial validation for the first three screens, but the fourth screen is a bit more involved since it interfaces with soccer-common. I would like to confirm the behavior for this before doing more work. There are a couple TODOs in the code that highlight some of the open questions. 

This isn't a focus right now before interviews so I'll mark as deferred until we hit that milestone.

**Comment by jbphet** [comment]
@marlitas and I just discussed this issue, and we're thinking that the next move is to meet with @amanda-phet to get clear on how much flexibility we want to give phet-io users for customizing ranges for the number of plates and soccer balls.

**Comment by marlitas** [comment]
This is now a duplicate of https://github.com/phetsims/mean-share-and-balance/issues/246. Closing
