### ISSUE TITLE
Changes to first screen (Intro / Level Out)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#198]
- [x] Remove "Mean" checkbox
- [x] Remove "Cup water level" checkbox
- [x] Move "Number of cups" down to the same location as the spinner on other screens
- [x] Add more variability to additional cups that are added - start with "random" values. If it doesn't feel it's working, or it's an issue with PhET-iO, I think this set could work: 0.2, 0.65, 0.9, 0.35, 0.75
- [x] Indicate "success" if the prediction line is close to the mean (within 0.1 ?) – only visible if valve is open – with a yellow 50% opacity rectangle behind the dashed line
- [x] Indicate "success" if the prediction line is exactly on the mean – only visible if valve is open – with a purple dashed line

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/d39c5581-52db-4d33-bb4f-2d5c08eacf28)

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/3afc4fe2-55f3-47d0-a23c-26cf7f97424c)

**Comment by marlitas** [comment]
All of these requests are implemented. @amanda-phet over to you for design review.

@jbphet over to you for code review.

**Comment by marlitas** [comment]
At the 4/16 sound meeting, we want to investigate how difficult it would be to have the "success" indicators for predict mean turn on when the water has fully leveled out, rather than when the pipes open.

**Comment by marlitas** [comment]
Okay this is ready for review again! New slider functionality in and the success range was updated. Over to @amanda-phet and @jbphet.

**Comment by amanda-phet** [comment]
Everything looks great! Thanks!

**Comment by amanda-phet** [comment]
Look good. Thanks!!
