### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#2]
Commits as part of running through the new sim checklist https://github.com/phetsims/phet-info/blob/05c54e5d7d2f1c99320d8f9e169f83ec5bb427e0/checklists/new_repo_checklist.md

# New Repository Checklist

These steps contain the following placeholders that you'll need to fill in:

- `{{AUTHOR}}}` - the name that will appear in `@author` code annotations, e.g. `Jane Doe`
- `{{REPO}}` - the repository name, e.g. `gas-properties`. This should be composed of lower-case characters and dashes, and should have <=214 characters (see naming constraints in https://docs.npmjs.com/cli/v7/configuring-npm/package-json).
- `{{TITLE}}` - the simulation's title, e.g. `Gas Properties`

## Steps to create a new simulation repo

At https://github.com/phetsims:
- [x] Press the "New" button.
- [x] In "Repository' text field, enter the repository name.
- [x] In the Description field, enter `"{{TITLE}}" is an educational simulation in HTML5, by PhET Interactive Simulations.`
- [x] Set visibility to "Public".
- [x] Do not check the "Initialize this repository with a README" checkbox.
- [x] Do not check "Add .gitignore".
- [x] Do not check "Add a license".

In your working copy of perennial repo:
- [x] Run `grunt create-sim --repo="{{REPO}}" --author="{{AUTHOR}}" --title="{{TITLE}}"` to create the file structure and skeleton code for the sim.

In your working copy of the sim repo:
- [x] `git init`
- [x] `git add * .gitignore`
- [x] `git commit -m "Initial commit"`
- [x] `git remote add origin https://github.com/phetsims/{{REPO}}.git`
- [x] `git push -u origin master`

At https://github.com/phetsims/{{REPO}}:
- [x] Go to _Settings => Collaborators and teams_. Press the "Add teams" button. See [team assignment.md](https://github.com/phetsims/phet-info/blob/master/policies/team%20assignment.md) for assignments by repo type.
- [x] Create a Sim Checklist issue using template [sim_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_checklist.md). Use "{{TITLE}} Master Checklist" as the issue name. Assign to @ariel-phet.

In your working copy of perennial repo:
- [x] Add the new repo to `perennial/data/active-repos`. Commit and push. Then pull perennial-alias so these two checkouts stay in sync. If needed immediately, run `cd perennial/ && grunt generate-data` and commit and push to update data lists. Otherwise it is done every night as part of daily grunt work.  _Note that your sim won't run in phetmarks until this is done._

Other:
- [x] Navigate to https://bayes.colorado.edu/dev/phettest/ and click the "Refresh perennial, perennial-alias, and chipper" button. If you do not know the password, please ask another developer.
- [x] Apply GitHub labels. See [github-labels/README.md](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md).
- [x] Apply branch protection rules using [protect-branches-for-repo.js](https://github.com/phetsims/perennial/blob/master/js/scripts/protect-branches-for-repo.js). Follow the instructions in the documentation at the top of the script.
- [x] Notify Slack channel dev-public that the repo has been created. E.g. "I just added a new repository, {{REPO}}. Please pull perennial and perennial-alias and run `clone-missing-repos.sh` at your convenience."
- [x] If using IDEA/Webstorm (pre-2018), add the git source root for the repository.
- [x] Follow any remaining "Implementation" tasks in the Master Checklist issue that you created above.
- [x] If applicable, add any needed dependencies to `phetLibs` in package.json. If you change package.json, run `grunt update`.
- [x] Add the sim to [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json).
- [x] Add the sim to chipper/tsconfig/all/tsconfig.json
- [x] If applicable, add corresponding dependencies from `phetLibs` in package.json to "references" in tsconfig.json. 

## Steps to create a different type of repo

At https://github.com/phetsims:
- [ ] Press the "New" button.
- [ ] Fill in the Description field.  (Ask other developers if you need suggestions.)
- [ ] Decide on visibility. (Ask other developers if you're not sure.)
- [ ] Typically do not select options that would initialize the repo by creating files (README, .gitignore, LICENSE).

In your working copy of the sim repo:
- [ ] Create the file structure locally. It's best to start (currently) by copying from a similar repository (but without the `.git` directory). Make sure to keep `.gitignore`, etc.
- [ ] `git init`
- [ ] `git add * .gitignore`
- [ ] `git commit -m "Initial commit"`
- [ ] `git remote add origin https://github.com/phetsims/{{REPO}}.git`
- [ ] `git push -u origin master`

At https://github.com/phetsims/{{REPO}}:
- [ ] Go to Settings => Collaborators and Teams, add the teams used in another public sims (currently Design, Development, and Quality Assurance) with "Write" permissions. _NOTE: If the repo is private, it is REQUIRED to add the Machine User collaborator (so automated processes can clone/pull the repo). CT will break otherwise._

In your working copy of perennial repo:
- [ ] If applicable: Add the new repo to `perennial/data/active-repos`. Commit and push. Pull perennial-alias. If needed immediately, run `cd perennial/ && grunt generate-data` and commit and push to update data lists. Otherwise it is done every night as part of daily grunt work.

If this repo is a common code dependency for all sims:
- [ ] Add it to the list of `clone` commands in [phet-development-overview.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md)
- [ ] Update all sim published README files (because the "Quick Start" section has these git clone commands too).

Other:
- [ ] Notify Slack channel dev-public that the repo has been created. E.g. "I just added a new repository, {{REPO}}. Please pull perennial and perennial-alias and run `clone-missing-repos.sh` at your convenience."
- [ ] Apply GitHub labels. See [github-labels/README.md](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md).
- [ ] Apply branch protection rules. Use [this script to do so](https://github.com/phetsims/perennial/blob/master/js/scripts/protect-branches-for-repo.js).
- [ ] If using IDEA/Webstorm (pre-2018), add the git source root for the repository.
- [ ] Add the sim to [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json).
- [ ] Add the sim to chipper/tsconfig/all/tsconfig.json

## Steps for renaming a repo
- [ ] Make sure all commits are pushed to that repo.
- [ ] On Github.com, go to repo -> Settings -> Options -> "Repository name"  and rename.
- [ ] Rename in `perennial/data/active-repos` and any other perennial data files it occurs in, like `active-runnables`, `active-sims`, `phet-io`, etc. Push the change to perennial and then pull perennial-alias.
- [ ] Delete the old repo
- [ ] Run `perennial/bin/clone-missting/repos.sh`.
- [ ] Update `package.json` accordingly. Including but not necessarily limited to:
  * `name`
  * `repository.url`
  * `phet.requirejsNamespace`
- [ ] Change entry in [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json).
- [ ] If applicable, "refresh perennial" on phettest.
- [ ] Add the sim to chipper/tsconfig/all/tsconfig.json
- [ ] Remove old repo directories in `chipper/dist/js`, `chipper/dist/declarations`, and `chipper/dist/js-cache-status.json` and and restart your transpiler.
- [ ] Notify Slack channel dev-public that the repo has been renamed. E.g. "I just renamed repository {{OLD_REPO}} to {{NEW_REPO}}. Please pull perennial and perennial-alias, run `clone-missing-repos.sh` at your convenience, remove {{OLD_REPO}} in `chipper/dist/js`, `chipper/dist/declarations`, and `chipper/dist/js-cache-status.json` and restart your transpiler."

### If this is a simulation. . .
  - [ ] Rename many files:
    * `*en.json` string file
    * `main.js` file
    * Screens/Views/Models?
    * Namespace file
  - [ ] Make sure to update the title in the `*en.json` string file and update its usage in the main js file
  - [ ] Run `grunt modulify`
  - [ ] update usages of the Namespace file
  - [ ] Looks through all usages in the repo of the previous name to make sure issues links, comments and code are updated.
  This especially applies to imports for the namespace and strings.

**Comment by samreid** [comment]
I added @marlitas to responsible dev JSON file, but I want to check on that.

**Comment by marlitas** [comment]
Using correct github account. Everything looks good!
