### ISSUE TITLE
Changes to Fair Share screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#200]
- [x] Remove the mean accordion box and put the info button in that space
- [x] Add a "Total" checkbox that displays the total on the notepad
 - [x] Move total back to the center of the notepad
 - [x] Set the initial values of people to be as follows: 2, 1, 6, 2, 10, 5, 8

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/1b3bf453-d342-4ae7-91e9-15caff341f15)

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/247baa3a-0271-483e-8c26-409f112242d5)

**Comment by marlitas** [comment]
All the commits happened through changes to https://github.com/phetsims/mean-share-and-balance/issues/199, so no need for code review here. Over to @amanda-phet for design review!

**Comment by amanda-phet** [comment]
This all looks great!
