### ISSUE TITLE
Changes to Balance Point screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#201]
- [x]  Remove the mean checkbox
- [x]  Add a "Total" checkbox that displays the total on the notepad
- [x]  Move total back to the center of the notepad
- [x] Add some logic so that if the fulcrum is close to the mean, it looks close to being balanced (I am not including details here because I'm not entirely sure how this will work, but John and Marla indicated they have a plan) 
- [x] Consider an indication of "success" when the user successfully balances the beam. Perhaps when there are no pillars, if it is balanced, the fulcrum temporarily fills in with solid purple. We might also want a message like "You balanced the data!" similar to CaV. 

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/4d8544aa-973c-49d4-ab06-137d77fa9d07)

**Comment by jbphet** [comment]
@amanda-phet - I've implemented a version of the feature where the beam tilts more gradually as the fulcrum approaches the mean.  Please try it out and let us know what you think.

**Comment by amanda-phet** [comment]
Nice! I think it's a nice improvement. Now that we can get the beam looking *close* to balanced, it's a bit hard to tell when you are precisely at the balance point. I think the goal isn't to be precisely there, but I also am not sure if there will be confusion. Definitely something I want to see how students respond in interviews. 

The reason we made this change is because being close is the point of the exercise... so maybe it's working exactly as intended! But I think we still need some messaging that you are spot on (which is in the initial comment for this issue). The question is, which visual indicator to go with the sound makes sense? I almost want the plank to turn purple, so maybe it should start out black and turn purple when it's perfectly balanced? I'll tag this for design so it can be discussed with others on the team! We already have two ideas proposed but I don't love either enough to move ahead with it.
