### ISSUE TITLE
Support state for notepadModeProperty changes

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#204]
Connected to https://github.com/phetsims/phet-io/issues/1661. Currently ObservableArray listeners are firing unexpectedly before the notepadModeProperty value has been set in state.

**Comment by zepumph** [comment]
I'll report back here once we have progress on https://github.com/phetsims/phet-io/issues/1661. Just to be clear, for this specific MSAB case, the order dependency is:

`meanShareAndBalance.fairShareScreen.model.notepadModeProperty` needs to have its new value, before `meanShareAndBalance.fairShareScreen.model.plate1.snacksOnNotepadPlate` fires its listeners from adding new snacks.

**Comment by zepumph** [comment]
https://github.com/phetsims/phet-io/issues/1661 has been completed. @marlitas can you please review and ensure that MSAB PhET-iO state is working.

**Comment by marlitas** [comment]
Yes this is great! Thanks for turning that assertion on and doing this work. Ready to close!
