### ISSUE TITLE
Add Collect and Share Sounds for screen three

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/mean-share-and-balance#206]
I have a mockup video of what we [discussed here.
](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974&id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FMockup%20Videos&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa)
- MSaBCollectAndShareMockup.mp4

[I have also uploaded these sound files.](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974)

- MSaBCollectSound.mp3
- MSaBCollectWooshSound.mp3
- MSaBCollectTearOrFractionalizeSound.mp3
- MSaBShareSound.mp3
- MSaBShareSoundSeperateNotesC3.mp3
- MSaBShareSoundSeperateNotesE3.mp3
- MSaBShareSoundSeperateNotesG3.mp3
- MSaBShareSoundSeperateNotesC4.mp3
- MSaBShareSoundSeperateNotesE4.mp3
- MSaBShareSoundSeperateNotesG4.mp3
- MSaBShareSoundSeperateNotesC5.mp3
- MSaBShareSoundSeperateNotesE5.mp3

There are two ways we discussed trying the Share sound: 

1. Just play the **MSaBShareSound.mp3** file when the animation starts
2. Play one of the **MSaBShareSoundSeperateNotes** files for each apple as it animates. I have up to seven files which creates a major C chord, providing relief from the G7 that plays for the collect animation.

**Comment by marlitas** [comment]
@jbphet and I talked through a strategy for firing the sound when apples split, and then land:

View is looking for:
- Collect => Share:
- Emitters can exist for lifetime of sim. No need to unhook.
-   1. Play "woosh" sound when mode changes.
-   2. Wait... listen for apple split (emitter fires)
-   3. Wait... listen for all apples landing (emitter fires when Map has only one apple left)
- All other mode transitions: Play sound when mode changes. (but not when setting PhET-iO state)
- use option `enabledDuringPhetioStateSetting` to make sure sound doesn't play during state setting. (defaults to false)

**Comment by marlitas** [comment]
This has been addressed above. @jbphet I didn't quite know what to do with any code that connected a `mainGainNode`, so I added a TODO about that and some commented out code. Otherwise I think it's sounding good. My one critique may be that the landing sound feels a little late right now, but wanted to get other opinions before really investigating that.

**Comment by Ashton-Morris** [comment]
In our last meeting we discussed playing three different densities of "share" chords depending on how many apples was shared.

I am assuming that dividing the possible apples into thirds would be enough. So  1 of 1/3 = small, 2 of 1/3 = medium, and. 3 of 1/3 = large in terms of amounts. Here are the [sounds I have made for that. ](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974)

- MSaBShareSoundSmallAmount.mp3
- MSaBShareSoundMediumAmount.mp3
- MSaBShareSoundLargeAmount.mp3

**Comment by jbphet** [comment]
The initial implementation of this is complete.  Assigning to the sound design team for review of the behavior and additionally to @marlitas for code review.

**Comment by jbphet** [comment]
Reviewed in the 4/30/2024 sound design meeting, and one piece of feedback is that the "share complete" sounds seem late since they are not being triggered until the animation finishes.  We'd like to try just a single, delayed play of this sound instead to see if it works better.

**Comment by jbphet** [comment]
I've modified the behavior to trigging the "share compete" sound earlier.  I'd like @Ashton-Morris and @emily-phet to review this aspect to see if they are now good with it.

Also - @Ashton-Morris - please assign this issue back to me once we have the changes you wanted to try with the "wider chords" for this sound.

**Comment by amanda-phet** [comment]
I had the same thought- glad it came up today. The timing is better to me.

**Comment by Ashton-Morris** [comment]
[I am adding these](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974) to files to replace the medium and large sounds, hopefully this is subtle enough but more distinct than what we have currently.

- MSaBShareSoundMediumAmountv2.mp3
- MSaBShareSoundLargeAmountv2.mp3

**Comment by jbphet** [comment]
The timing is approved as of today's design meeting, so all that is left is to integrate the new chords.

**Comment by marlitas** [comment]
New sounds are in. @Ashton-Morris do you want to take a listen before closing?

**Comment by Ashton-Morris** [comment]
Sounds good - Closing
