### ISSUE TITLE
Can't get fulcrum at mean value

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#213]
I have the fulcrum at 3.1, but it's not showing up as balanced (just barely not balanced). I confirmed using the other scene and the info dialog, and moved the fulcrum, and this is as close as I can get to balanced, and it should register as balanced. 

https://github.com/phetsims/mean-share-and-balance/assets/7852916/de4efa90-c469-4881-b2b5-a509469f4458

**Comment by marlitas** [comment]
This was happening due to a need to round both the fulcrum and mean values to the same precision. Fixed above. Over to @amanda-phet to confirm, and @jbphet for code review.

**Comment by marlitas** [comment]
We reviewed this together, so @amanda-phet feel free to close once you confirm.

**Comment by marlitas** [comment]
We reviewed synchronously. Ready to close!
