### ISSUE TITLE
Create and Listen to the sounds for the Pillars on Screen Four

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/mean-share-and-balance#214]
I have recorded three options. We didn't get to it on Tuesday so I am made a video.

https://github.com/phetsims/mean-share-and-balance/assets/34492870/6a8ad584-b6a6-42bd-979f-71c841d49f6d

**Comment by amanda-phet** [comment]
I think the 3rd one should be called Pillar Sound Option 3, right? The text color changed so I assume it's a typo :) 

Two things. 
1. I like option 1 the best, by far. 
2. I just want to clarify that this sound will happen when someone presses the Check and Reset buttons, not when they change scenes. Changing scenes adjusts the view so that the fulcrum isn't movable and it moves to reflect the actual mean while the data is updating/changing.

**Comment by jbphet** [comment]
@marlitas and I just listened to and watched the vid, and also much preferred option 1.  We will move ahead with the implementation of that option.  And we concur that these will be associated with the Check/Reset button and not the scene selector.

**Comment by Ashton-Morris** [comment]
> I think the 3rd one should be called Pillar Sound Option 3, right? The text color changed so I assume it's a typo :) - AM ahh yes I missed this
> 
> Two things.
> 
> 1. I like option 1 the best, by far. - AM I also like this one
> 2. I just want to clarify that this sound will happen when someone presses the Check and Reset buttons, not when they change scenes. Changing scenes adjusts the view so that the fulcrum isn't movable and it moves to reflect the actual mean while the data is updating/changing. - **AM  I did realize this after I made the recording but wanted to use the video anyways instead of re-record this.**

**Comment by Ashton-Morris** [comment]
@jbphet  Adding these sounds to[ this folder now.](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974)

- MSaBCheckPillarButton.mp3
- MSaBResetPillarButton.mp3

**Comment by marlitas** [comment]
This is ready for people to listen and give feedback! Over to @jbphet for code review as well.

**Comment by amanda-phet** [comment]
I think these are in correctly, but the volume needs to be lower. I'm guessing the tuning of volumes comes later, but wanted to write it while I was thinking of it.

**Comment by Ashton-Morris** [comment]
I like how these are sounding in the sim. Of course they will be much quieter in the end and I think I'll enjoy them even more. What I like about current disappear sound is that it sounds like it could be the pillars crumbling or turning in to sand as they disappear.

**Comment by Ashton-Morris** [comment]
[I have added this sound, which is the reverse sound.](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974)

- MSaBResetPillarButtonv2.mp3

**Comment by marlitas** [comment]
The new sound has been applied above. Ready to review and close if all sounds good.

**Comment by amanda-phet** [comment]
This sound is working for me!

**Comment by Ashton-Morris** [comment]
Sounds good!

**Comment by jbphet** [comment]
At today's review meeting we determined that we are good with these sounds, but would like to turn down that one that is played when the pillars come back, and should only play the sound for when the pillars go away if no balls have been kicked.

**Comment by jbphet** [comment]
The changes described just above have been implemented.  Assigning to @amanda-phet for review and possibly closure.

**Comment by amanda-phet** [comment]
This is working nicely!
