### ISSUE TITLE
Cueing arrow behavior/design for Distribute Screen

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#215]
This is related to https://github.com/phetsims/mean-share-and-balance/issues/207 and https://github.com/phetsims/mean-share-and-balance/issues/141. 

We recently added the yellow cueing arrows to the Distribute screen to match the cueing arrows used for the fulcrum in the Balance Point Screen.
<img width="271" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/1fb3e93c-66d8-4f31-bd6a-3aca49b2cffc">
<img width="183" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/5a0dfc31-624d-4b8e-ad01-0f28a149891a">

However in the Distribute Screen these cueing arrows also need to be part of the larger conversation surrounding keyboard cueing. For the "groupSortInteraction" we are using the below cues for mouse and keyboard:
<img width="178" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/6c6500c1-3245-4141-ad38-73646bdc74cf">
<img width="198" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/66eb3e4c-1cea-4a97-b9d0-313c404c08fc">

There are also specific cueing behavior questions that need to be answered:

- When switching between keyboard and mouse, should the cue follow keyboard focus, or follow different logic for it's placement?
- Are we using two different cues for mouse and keyboard or the same?
- When candy bars are added and removed how do we want to handle the placement of the cueing arrow? For example currently the cueing arrow appears on the first stack as soon as that plate has any candy bars. However, this can be jarring if it had previously lived on a different stack.

I believe a synchronous meeting with @amanda-phet and @jbphet will be most helpful in answering these questions.

**Comment by marlitas** [comment]
Meeting 4/29:
- @amanda-phet suggested that we place the cueing arrow on the tallest stack. We like that, let's do it.
- Unless... there was keyboard focus, then we follow that.
- Use the same yellow mouse cueing arrows for the keyboard interaction.
- For Balance Point, keep the cue visible after all 7 balls have been kicked and as long as there is at least one visible ball on the field.

**Comment by marlitas** [comment]
I addressed the above recommendations. Over to @amanda-phet and @jbphet for review.

**Comment by amanda-phet** [comment]
All looks good to me!

**Comment by jbphet** [comment]
Based on some feedback from the recent interviews and subsequent design discussions, we're revisiting how to improve the cues to make them more effective.  Assigning to @amanda-phet.

**Comment by amanda-phet** [comment]
Thanks Marla! 

1. I don't really like the arrowhead above, but I'm fine using it if it's just a package deal. I thought we were trying _not_ to use an arrow because that cue isn't super obvious, and technically you can't move it both directions you can only move it to the right. 
2. Most importantly, and this is not a new issue I just haven't had a chance to make an issue for it-- the cue stays behind once you move the candy bar. As soon as you move it, I think the cue needs to go away. 
![Screenshot 2024-05-17 at 1 49 42 PM](https://github.com/phetsims/mean-share-and-balance/assets/7852916/41f15d5b-1b94-4bd4-814e-654305211688)

3. There is a bug, in case you didn't know about this. If you go down to one person, this happens: 

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/135c050b-a2fe-4c4f-99e2-2735ac104bfc)

**Comment by marlitas** [comment]
Yeah there's some bugginess I definitely still need to fix. But if you like the concept then I can go ahead and address those scenarios.

**Comment by marlitas** [comment]
I believe the bugs have been addressed and this is now ready for design and code review.

**Comment by jbphet** [comment]
Code looks good.  Closing.

**Comment by amanda-phet** [comment]
I discovered this behavior recently and wanted to share it here. I'm sure QA would have found it too. Should we do something about this? 

<img width="184" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/7852916/8debe6e0-1c20-4031-ad8c-31074416b806">

**Comment by marlitas** [comment]
Hmmm. Yeah that doesn't seem ideal, but I'm not sure how to fix it... Right now the logic we have is that the cue will appear on the tallest stack. We can switch that to the lowest stack, but that feels a bit odd with what the cue is trying to accomplish.

**Comment by KatieWoe** [comment]
Things look pretty good in dev-lite

**Comment by amanda-phet** [comment]
@KatieWoe you think it's ok to have the cue cover the text?

**Comment by KatieWoe** [comment]
I don't like it very much, but since it was brought up in this issue and so was known, I didn't have anything to add to it. Sorry, better to say that I have nothing new to add to this issue

**Comment by amanda-phet** [comment]
I'm making another issue for this and will close this one. I know what to do.
