### ISSUE TITLE
Add "subtle pop" sound when decreasing number of balls on field in screen 4

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#217]
For the number spinner that controls the quantity of balls on the field in the 4th screen, the sound design spec says "Decrease: subtle “pop” sound...There is a similar sound in PDL that we can use".  This needs to be implemented.

**Comment by marlitas** [comment]
- [ ] Take PDL sound and copy over to MSaB
- [ ] Add TODO to make common if we like that sound

**Comment by marlitas** [comment]
I added what @jbphet and I had thought was the "pop" sound from PDL. I identified it as `cannonballTone`. It feels like it might be a bit aggressive to me... almost like I did something wrong by removing a ball.

Over to others to review though.

**Comment by marlitas** [comment]
Meeting 4/29
- @amanda-phet agreed with @jbphet and I that it sounds like an "error" sound you get from computers sometimes.
- We liked the release sound used for grab and release.

**Comment by marlitas** [comment]
The new sound has been pushed up. Over to @jbphet for code review, and others for design.

**Comment by emily-phet** [comment]
Sounds good to me.
