### ISSUE TITLE
Move MeanPredictionChangeSoundGenerator to PredictMeanSlider

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#220]
From https://github.com/phetsims/mean-share-and-balance/issues/199, @jbphet recommended we move the `MeanPredictionChangeSoundGenerator` to Predict Mean Slider, since it is now used in multiple places.

**Comment by marlitas** [comment]
Done above. Over to @jbphet to confirm that I did what he was thinking of.

**Comment by jbphet** [comment]
No, that isn't quite what I was thinking, but I wasn't aware of this issue's existence so I logged a new one with my thoughts on how to straighten it out, see https://github.com/phetsims/mean-share-and-balance/issues/225.  I'll close this one, and we can follow up in the other.
