### ISSUE TITLE
Provide a dev version with sound for some interviews

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#221]
@amanda-phet is about to do the 2nd round of interviews, so we need to provide a new dev version for this, and this version needs to include sound.  We've discussed this a bit, and decided that we should have it ready at around 11 AM tomorrow, 5/3/2024 so that some review can happen prior to the interviews.  The interviews are scheduled for Sat 5/4.

**Comment by jbphet** [comment]
A candidate dev version has been built for this, please see https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-dev.4/phet/mean-share-and-balance_all_phet.html.  @amanda-phet - please try this out and let @marlitas and I know if there are any last-minute changes needed prior to the interview.

**Comment by amanda-phet** [comment]
This is working great! 

I opened one issue so far, and think we might want to try to at least address the bug before Saturday, but it's not too terrible if it sticks around. https://github.com/phetsims/mean-share-and-balance/issues/224

**Comment by jbphet** [comment]
Okay, there's a new dev version that, we believe, addresses the problems pointed out in #224.  Back to you @amanda-phet.

**Comment by amanda-phet** [comment]
This version looks great to me! Thanks!!
