### ISSUE TITLE
Predict Mean on Distribute needs updates

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#224]
- [x] When checked, this should be at the bottom of the stacks, and right now it starts somewhere in the middle. Here is what I think is a good starting point: 

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/f1299359-e5dc-4349-a14b-8ede69ad5bb3)

- [x] (Bug) I also noticed that even after pressing reset-all the location of the predict mean line doesn't reset, and starts right where you left it. 

- [x] Lastly, I thought we discussed showing the yellow and purple feedback after someone had moved blocks (but I can't find that in the issue where I requested we add it). Right now it's very hard to actually make a prediction since it shows the mean before moving any blocks. Is this something we can implement?

**Comment by jbphet** [comment]
@marlitas and I have committed code for all of the above mentioned problems/requests.  However, we had to put a bit of a hack into place to get the initial positioning of the mean prediction lines to be correct.  We will leave this issue open and assigned to us for investigation.

**Comment by amanda-phet** [comment]
Thanks, it is working great!

**Comment by marlitas** [comment]
Found and fixed the bug. Over to @jbphet to review and close if all looks good.

**Comment by amanda-phet** [comment]
I think this might actually need some refinement.. 

Instead of giving the yellow/purple feedback once someone has moved blocks, we might want to only show it if someone has actually leveled out the blocks. I had it up as a prediction, moved one block, and got the feedback, and I hadn't finished moving the blocks to their level positions. So I think it would be good to discuss how this really needs to behave before closing the issue.

**Comment by marlitas** [comment]
I think a merge brought the workaround and TODO back somehow... removed again above.

**Comment by marlitas** [comment]
The above commit should have been attached to this issue: https://github.com/phetsims/mean-share-and-balance/issues/226

**Comment by jbphet** [comment]
Assigning back to @amanda-phet for resolution of the design/behavior questions [raised above](https://github.com/phetsims/mean-share-and-balance/issues/224#issuecomment-2093939698).  @marlitas and I are happy to discuss with you whenever you're ready.

**Comment by marlitas** [comment]
Meeting 5/8
- We decided that we want to show success once candy bars have been leveled out as much as possible.
- @jbphet came up with a plan of just checking that all stacks match the floor of the mean or +1.

**Comment by marlitas** [comment]
This is ready for design and code review!

**Comment by amanda-phet** [comment]
This is working great now!

**Comment by marlitas** [comment]
@jbphet and I talked through a strategy to reduce duplication and we are excited! I will go ahead and move forward with that.

**Comment by marlitas** [comment]
The refactor has been applied. @jbphet can you review?

**Comment by jbphet** [comment]
This looks great, much better.  I think it can be closed.
