### ISSUE TITLE
Separate `MeanPredictionChangeSoundGenerator` from `PredictMeanSlider`

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#225]
In one of the recent issues assigned to me for review I suggested that `PredictMeanSlider` should probably take over its own sound generation, but I didn't word it very clearly, and it was interpreted as moving the sound generation code into `PredictMeanSlider.ts`.  What I meant to convey was that the sound generation should be set up within `PredictMeanSlider` instead of in parallel with it in the view.  So, I think we should pull the sound generator out of `PredictMeanSlider` and back into its own file.

@marlitas and I have discussed this, I just wanted to make sure we didn't forget.

**Comment by marlitas** [comment]
I reverted the commit and moved the creation of the generator into PredictMeanSlider. Over to @jbphet to confirm and close.

**Comment by jbphet** [comment]
Looks great @marlitas - thanks.  Closing.
