### ISSUE TITLE
mouseSortCueVisibleProperty re-entry during reset

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#228]
The start-up value for `mouseSortCueVisibleProperty` is `false` in the `GroupSortInteractionModel`. This means that during reset a sim that wants to show the mouseSortCue from the beginning will hit a re-entry scenario. This did not happen in center-and-variability, because the mouseSortCue doesn't appear until all balls have been kicked out.

**Comment by marlitas** [comment]
I created an option in `GroupSortInteractionModel` so that the client can determine the startup value of the visibleProperty as needed. Over to @zepumph for review.

**Comment by zepumph** [comment]
Yeah, looks great thanks.

**Comment by marlitas** [comment]
Great! This is ready to close.
