### ISSUE TITLE
Instrument visibility of yellow/purple prediction feedback

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#242]
Create a successIndicatorsAreActive, or successIndicatorsActivated, or successIndicatorsVisible Property. Naming TBD.

**Comment by marlitas** [comment]
I decided to call it successIndicatorsOperatingProperty.

**Comment by marlitas** [comment]
This is ready for design and code review. I did think after the fact that `areSuccessIndicatorsOnProperty` might be a good name too... Easy to change if we have a better name. 

Over to @amanda-phet and @jbphet

**Comment by amanda-phet** [comment]
Should `meanShareAndBalance.levelOutScreen.model.successIndicatorsOperatingProperty` be linked under `meanShareAndBalance.levelOutScreen.view.meanPredictionSlider`?

**Comment by amanda-phet** [comment]
Looks good!
