### ISSUE TITLE
Unify names of meanPredictionProperty and predictMeanSlider

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#244]
meanShareAndBalance.levelOutScreen.view.predictMeanSlider ⇒ meanPredictionSlider

Add meanShareAndBalance.levelOutScreen.model.meanPredictionProperty as a linked property in the view

Check with MK about why this isn’t a linked property by default

**Comment by marlitas** [comment]
In doing some investigation, the reason we need to manually link the valueProperty is because we are extending `AccessibleSlider` instead of `VSlider`. However this makes sense for our use case. The predictMeanSlider does not have a traditional thumbNode (changes size according to the amount of cups/plates in the view), does not have a track, and we want to use an `ns-resize` cursor instead of a `pointer`. 

I changed the name and linked the value. Over to @amanda-phet and @jbphet for review.

**Comment by jbphet** [comment]
Looks good to me.

**Comment by amanda-phet** [comment]
Looks good to me.
