### ISSUE TITLE
Setting the max for the number of cups/plates

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#246]
Related to: https://github.com/phetsims/mean-share-and-balance/issues/187

Just be able to set the max. Call it maxCupsProperty and maxPlatesProperty.
min: 1 
max: 7

When we set this property, sim resets. Keep this consistent.

**Comment by jbphet** [comment]
I've got a few comments and observations on these changes.  First, `maxKicksProperty` is created in `BalancePointModel` like this:

```js
    const maxKicksProperty = new NumberProperty( MeanShareAndBalanceConstants.MAXIMUM_NUMBER_OF_DATA_SETS, {
      range: new Range( 0, 7 ),
      tandem: options.tandem.createTandem( 'maxKicksProperty' )
    } );
```

The use of a hard-coded '7' seems odd.  Why not use `MeanShareAndBalanceConstants.MAXIMUM_NUMBER_OF_DATA_SETS` for the max value?  It might make sense to change the name to now include `DEFAULT`.

Second, it is created here, then passed into `BalancePointSceneModel` and never directly used again in `BalanceModel`.  Why create it in `BalanceModel` and not in `BalancePointSceneModel`?

Next, there is the following linkage in `BalancePointSceneModel:
```js
    maxKicksProperty.link( maxKicks => {
      this.clearData();
      MeanShareAndBalanceConstants.NUMBER_OF_KICKS_RANGE_PROPERTY.value = new Range(
        MeanShareAndBalanceConstants.NUMBER_OF_KICKS_RANGE_PROPERTY.value.min,
        maxKicks
      );
    } );
```

This appears to be changing a value of what is presumably a constant from another file (`MeanShareAndBalanceConstants`).  I don't think we should do this.  There should just be an instance of `numberOfKicksRangeProperty` somewhere that can be accessed by all, but it shouldn't be presented as a constant if it isn't.  If it needs to be fairly global, the pattern used for `isResettingAllProperty` in `ResetAllButton` might be helpful.

Back to @marlitas for next steps.

**Comment by amanda-phet** [comment]
This is working well on my end!

**Comment by jbphet** [comment]
Looks good to me.  Closing.
