### ISSUE TITLE
Remove unnecessary node instrumentation

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#248]
Uninstrument view notepadPlates
(meanShareAndBalance.distributeScreen.view.notepadPlate*)

Uninstrument people (meanShareAndBalance.distributeScreen.view.person*)

meanShareAndBalance.levelOutScreen.view.notepadCups.notepadCupNode*.tickMarks - unistrument this

**Comment by marlitas** [comment]
This was straightforward. Over to @amanda-phet for design review. Can be closed if all looks well.

**Comment by amanda-phet** [comment]
Looks good.
