### ISSUE TITLE
Create MeanWithRemainderProperty

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#249]
Call this meanWithRemainderProperty and make it an object
{
wholeNumber: 4
remainder: 1
}

**Comment by marlitas** [comment]
Done above. Over to @amanda-phet for design review.

@jbphet I decided not to use the meanWithRemainderProperty in `MeanCalculationPanel` since it would require Distribute screen specific passing through of the Property, and it's working well as is right now. Let me know if you disagree through.

**Comment by jbphet** [comment]
For the most part this seems fine, but...can't the `meanWithRemainderProperty` value be derived from just the number of plates and the total snacks?  It seems a little overcomplicated to have `meanProperty` as one of the dependencies to the derivation, since it is itself a derived property.

**Comment by marlitas** [comment]
Yeah you're totally right. My brain did not track that. I updated the derivation. @amanda-phet feel free to close if all looks well.

**Comment by amanda-phet** [comment]
Looks great!
