### ISSUE TITLE
NumberSpinner Arrow Options

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#25]
While implementing NumberSpinner I discovered that the default is for both arrows to be on the right side of the number display:
<img width="89" alt="Screen Shot 2022-06-02 at 4 03 28 PM" src="https://user-images.githubusercontent.com/42476338/171746082-512f6ff4-9fe7-4361-addc-2c13e7bcefa6.png">
I know we discussed various orientations of the arrows for the NumberSpinner but these options were not discussed and wanted to present them in case we like them better. The following are the possible options for arrow placement that NumberSpinner provides:

- Left Right (what we had discussed)
<img width="174" alt="Screen Shot 2022-06-02 at 4 07 11 PM" src="https://user-images.githubusercontent.com/42476338/171746431-512f7f9e-f4ba-4e06-8f4a-c52538184f35.png">

- Top Bottom
<img width="86" alt="Screen Shot 2022-06-02 at 4 08 13 PM" src="https://user-images.githubusercontent.com/42476338/171746517-e2ac917d-2016-4bc8-b027-982b1fe357b8.png">

- Both Right ( the default)
<img width="105" alt="Screen Shot 2022-06-02 at 4 08 53 PM" src="https://user-images.githubusercontent.com/42476338/171746631-cac58f19-c1a1-4246-8237-a9432925de4f.png">

- Both Bottom
<img width="106" alt="Screen Shot 2022-06-02 at 4 10 51 PM" src="https://user-images.githubusercontent.com/42476338/171746825-95fa72d8-52fc-4c7d-8f24-27b06cc60273.png">

Do we want to use one of these other orientations instead of the Left-Right that was discussed during our meeting?
I will use Left-Right until further notice.

**Comment by amanda-phet** [comment]
Both buttons on the right could be interesting. However at this point I'm indifferent to the options. Leaving open for a design discussion with more folks present.

**Comment by amanda-phet** [comment]
I've played with it and am really liking the left right spinner! Closing.
