### ISSUE TITLE
Inconsistent naming of checkbox Properties

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#256]
Inconsistent naming of properties related to checkboxes. For example, Total Checkbox  is sometimes powered by totalVisibleProperty, sometimes isTotalVisibleProperty. 

Want to be consistent, so we should look at soccer-common naming and be consistent with the Balance Point screen.

**Comment by marlitas** [comment]
I think I got all the checkbox Properties in the above commit, but I also was looking into changing all of our `isActiveProperty` => `activeProperty`, however I saw other usages of `isActiveProperty` in the code base, so it's not a completely unusual pattern, and I am partial towards how explicitly boolean it is... @amanda-phet what would you like me to do? This will affect Cups, Plates, Pipes, and Snacks. 

I confirmed that whatever we choose on the above does not affect Soccer Common.

**Comment by jbphet** [comment]
I would vote for changing to `activeProperty` for the sake of consistency.  The 'is' is assumed, such as in the change you just made from `isTotalVisibleProperty` to `totalVisibleProperty`.

**Comment by amanda-phet** [comment]
the naming looks good (and consistent) to me.
