### ISSUE TITLE
Model.md

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#259]
The model.md needs to be written and reviewed prior to code review

**Comment by marlitas** [comment]
I did a first pass at this. Would be good to get eyes on it from @amanda-phet and @jbphet

**Comment by jbphet** [comment]
This is very nice as far as I'm concerned.  It's well structured, clearly written, and seems to be add an appropriate level of detail.  I made a few, mostly quite minor, edits in the commits above and have a few suggestions below.

Suggestions
- Consider mentioning somewhere that the "real world" representation is at the bottom of the screen and the "notepad" representation is at the top.
- I didn't quite understand what was being conveyed by the phrase, "a cup will add on with an open pipe", so I wasn't sure how to edit it to make it clearer, so I'll just say that you might want to wordsmith that part a bit.
- I modified the phrase "with  [the balance beam] becoming completely level when the data set is evenly distributed across the beam" to "...completely level when the data set is equally distributed on the left and right sides of the fulcrum".  Feel free to modify it further, I just thought it didn't quite convey what was going on as written.

**Comment by marlitas** [comment]
I went ahead and addressed the above. All that remains is review from @amanda-phet.

**Comment by amanda-phet** [comment]
I made a lot of changes, so it might be good to review again. @marlitas will you let me know if my changes are ok?

**Comment by marlitas** [comment]
The changes look great! Thank you. I updated the author credit to include you @amanda-phet. I think this is ready to close but feel free to re-open if not.
