### ISSUE TITLE
Preparatory mini code review

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#26]
@marlitas and I recommend that the sim have a code review from another developer, but to prepare it for the code review, we agreed I should take a preparatory mini-review to see if there are architectural questions or other changes to make before the code review.  I'll try to do this within a week or so.

**Comment by samreid** [comment]
I read through every file and everything seems like it is in very good shape. I added some review comments, mainly about adding documentation. Please review the change sets and let me know if you have any questions about any of the changes that were made or REVIEW comments that were requested.

**Comment by marlitas** [comment]
All review comments addressed and changes looked over. Thanks for the feedback @samreid! Closing.
