### ISSUE TITLE
implementation-note.md

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#260]
Implementation-notes.md needs to be written and reviewed prior to code review.

**Comment by marlitas** [comment]
I gave this an initial stab and I think it's ready for some additional eyes and editing. Over to @jbphet

**Comment by jbphet** [comment]
Looks very good to me!  Please review the very minor edits I made with my commits and the suggestions I have below.

Suggestions:
- There is some inconsistency in the writing around whether to refer to "the mean" or "mean".  I'm more accustomed to the former, but I don't know whether one is considered more correct.  I poked around a bit online and it seemed to me that both are used but "the mean" is perhaps a bit more common.
- I added some more about the use of the terms "table" and "notepad" in the code, please review and make sure we're good with this.

**Comment by marlitas** [comment]
I think the edits you made are good! I think this is in a good. I'll go ahead and close this as complete :-)
