### ISSUE TITLE
Review of pointer areas

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#264]
This issue will address review of pointer areas by both designers and devs.

**Comment by marlitas** [comment]
From a cursory glance the pointer areas look good to me. Over to @amanda-phet to take a look.

**Comment by amanda-phet** [comment]
These look fine to me.

**Comment by amanda-phet** [comment]
Can we expand the touch area for the triangles on the water cups? I was using it again on an iPad and they would be nice if larger. I think they can even expand to the left over the actual water level.

**Comment by marlitas** [comment]
Expanded above. The touch areas are looking like this now.

<img width="241" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/e1b9541d-c98e-42ea-a5cb-ab9624a299f3">


@amanda-phet feel free to close if this feels correct.

**Comment by amanda-phet** [comment]
Much better on the iPad now! Thank you!
