### ISSUE TITLE
Update Credits

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#265]
Once the sim has gone through testing we must make sure credits are updated to reflect all who contributed.

**Comment by amanda-phet** [comment]
While I'm thinking of it, here is my draft of updates, but we may add more people for QA. 

``` 
credits: {
    leadDesign: 'Amanda McGarry',
    softwareDevelopment: 'John Blanco, Marla Schulz, Sam Reid',
    team: 'Catherine Carter, Kelly Findley, Marilyn Hartzell, Ariel Paul, Kathy Perkins, David Webb',
    qualityAssurance: 'Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
    graphicArts: 'Mariah Hermsmeyer, Amanda McGarry'
    soundDesign: 'Emily Moore, Ashton Morris',
    thanks: 'With early input/ideas from Dor Abrahamson and the Embodied Design Research Lab'

```

@kathy-phet let me know if this looks appropriate to you (specifically the Thanks section).

**Comment by marlitas** [comment]
In slack @kathy-phet said:

Kathy Perkins
[10:27 AM](https://phetsims.slack.com/archives/C03DHH7GMH6/p1723742827197809)
Hey team, I just want to make sure that it's on the list to add a "Thanks To" the credits within the sim - (I don't see it in the prototype)
Thanks to: Dor Abrahamson and the Embodied Design Research Lab (UC Berkeley) for their early input on the pedagogical design of this sim.
Or something similar
[10:28](https://phetsims.slack.com/archives/C03DHH7GMH6/p1723742906090449)
And add Cathy Carter to in-sim design team credits

**Comment by amanda-phet** [comment]
Edit above to include Taliesin.

**Comment by amanda-phet** [comment]
@KatieWoe can you verify the QA credits before the next RC?

**Comment by KatieWoe** [comment]
Jaron Droder, Luisa Vargas, Ashton Morris, Matthew Moore were all involved in QA this go around and should be added.

**Comment by Nancy-Salpepi** [comment]
Credits look updated (Thank you, TS and QA all there). 
Closing.
