### ISSUE TITLE
Water valve design

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#27]
The current valve is a simple circle with a cutout, and doesn't necessarily look interactive: 
![image](https://user-images.githubusercontent.com/7852916/172702104-23011530-0c8c-493d-964f-fa7c9d049867.png)

@marlitas came up with an idea that is kind of like a gate valve that is pretty awesome: 
![Screen Shot 2022-06-08 at 10 24 52 AM](https://user-images.githubusercontent.com/7852916/172701063-cc7a40da-f3c8-4560-b885-668e1e14c75a.png)

@samreid and @marlitas and I brainstormed how we could build on this idea and thought about making the height difference between on and off more stark, making the pin darker, and maybe even showing no pipe between cups of water if the valve is closed. 

I still liked the idea of the ball valve inspiration where we can see water flowing between cups and tried to play with that idea some more. @ariel-phet and I met to discuss some ways to make that work and ended up with this idea: 

![image](https://user-images.githubusercontent.com/7852916/172702233-5533e9e8-8b4d-446a-af32-aaf31720e550.png)

The pipe is opaque (and has a gradient to look like metal), but when you turn (click on) the valve/handle, you can see water flowing through the pipe. That seems to solve some issues of where the water came from, since it is hidden from view. This handle also feels similar to the handles for water pipes I have in my home, so it's familiar in that sense if someone has ever seen a pipe like this before. However there are still some sizing issues (the handle seems small) to work out. But I wanted to see what the rest of the team thinks about this direction.

**Comment by amanda-phet** [comment]
@marlitas made a version to match the new mockup! It's really helpful to see it in context: 

![image](https://user-images.githubusercontent.com/7852916/173865872-f0685fdb-7944-48b0-a3e2-2941d5e4b5eb.png)

I saw some minor issues, but before we polish it I think it would be helpful to decide if we like this direction.

**Comment by amanda-phet** [comment]
Discussed again 6/15/22, and @marlitas will keep the valve with the red handle. Some tweaks: 

* reduce the overall size of the valve a bit
* reduce the length of the handle so it doesn't cover the cup 
* change the pipe color to be a gradient from white to gray (#4d4d4d) - simple linear gradient

**Comment by marlitas** [comment]
Valve redesign according to notes is done and pushed up to master. Assigning to @amanda-phet for review and feedback.

**Comment by amanda-phet** [comment]
Let's review this with the team on Thursday. A lot of discussions and design progress have happened and everyone who wants to weight in should review the latest version.

**Comment by amanda-phet** [comment]
We are considering moving the whole valve over so that it is "centered" when the valve is in the open position. 

@marlitas can you let us know when this is ready for review, and possibly add a screenshot here?

**Comment by marlitas** [comment]
Valve position has been adjusted and is ready for review. Here's a screenshot to look over before tomorrow's meeting.

![Image](https://user-images.githubusercontent.com/42476338/180101504-1c850ad5-f988-40cb-bede-e7747d2c77f8.png)

**Comment by amanda-phet** [comment]
Reviewed in 7/21/22 design meeting and everyone likes it!
