### ISSUE TITLE
Grab/Release sounds for soccer balls

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#271]
While working on the grab and release sounds for the candy bars on the "Distribute" screen (see https://github.com/phetsims/mean-share-and-balance/issues/190), I noticed that we do *not* have such sounds for grab and release of the soccer balls on the "Balance Point" screen.  This seems a little inconsistent, so I thought I'd raise the question of whether we want to add sounds for this.

Note that the code for the soccer balls comes from the soccer-common repo, which is also heavily used in the *Center and Variability* sim, which also lacks sounds for grabbing and releasing the soccer balls.  We should consider whether this behavior should also change if we add sounds for grabbing and releasing the soccer balls in *Mean: Share and Balance*.

**Comment by emily-phet** [comment]
My memory is that we specifically chose *not* to have grab and release sounds for the soccer balls, as they are intimately tied to the sound of their location. When you interact directly with the soccer balls, you should hear the sound (tone) associated with its new location, in lieu of a distinct grab/release sound. We thought that adding a release sound wasn't needed, as you already hear the tone representing the new location, and the grab sound seemed like it would clutter up the mapping we were aiming for.

**Comment by amanda-phet** [comment]
I agree with @emily-phet that additional grab/release sounds aren't useful here. The number line tone is the useful thing. Since it's discrete, I also don't think grabbing and releasing are noticeable actions.. the noticeable thing is the location where the soccer ball is sitting.

**Comment by jbphet** [comment]
Sounds good, thanks for the explanations.  Closing.
