### ISSUE TITLE
Should the drawn soccer balls be a lighter shade of grey

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#273]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1094
When the soccer balls on the note pad overlap the Total Distance label, it can be hard to read. A lighter grey, at least for balls that overlap the label, may help.
**Steps to reproduce**
1. Go to the Balance Point screen
2. Kick all 7 balls
3. Stack all the balls on the 5 or 6 point
4. Turn on the Total check box

**Visuals**
![lightergrey](https://github.com/phetsims/mean-share-and-balance/assets/41024075/e4596d9f-3e47-4029-98a9-fd1bdade8cc2)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-dev.6/phet/mean-share-and-balance_all_phet.html
Version: 1.1.0-dev.6 2024-06-11 15:27:57 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
I wonder if the issue is that we changed the opacity of the total background. 

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/341938fc-680c-49f6-b132-96be4936026c)

**Comment by marlitas** [comment]
I increased the opacity to 0.8. @amanda-phet what do you think?

![image](https://github.com/phetsims/mean-share-and-balance/assets/42476338/a75892a0-7ccb-44c6-89ad-85bc29b01522)

**Comment by amanda-phet** [comment]
That solves it. Thanks!
