### ISSUE TITLE
Update prediction line to have yellow highlight even when exactly correct

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#276]
For https://github.com/phetsims/qa/issues/1094

Discussed with @KatieWoe and @Nancy-Salpepi . There is a negative experience associated with getting the mean exactly correct, because there is no sound, and you lose the bright yellow highlight. You can reproduce this by getting your prediction in the yellow zone, then dragging the pencil until the line turns purple. It just doesn't feel like you got something "more" correct at the purple. 

To address this, I'd like to try having the yellow highlight on even with the line is purple. This way, you get the yellow highlight when you are anywhere in the range of correct, and the change when you are exactly correct is that the light turns purple.

**Comment by marlitas** [comment]
This has been applied above. @amanda-phet feel free to close if all looks good!

**Comment by amanda-phet** [comment]
@Nancy-Salpepi and @KatieWoe want to take it for a spin as well? Let me know if this feels better to you!

**Comment by KatieWoe** [comment]
Looks good to me!

**Comment by Nancy-Salpepi** [comment]
looks good to me too!
