### ISSUE TITLE
Move total readout to the right

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#278]
In https://github.com/phetsims/mean-share-and-balance/issues/215#issuecomment-2158578826 I noticed that the cueing arrow overlaps the total. @Nancy-Salpepi also noticed that the apples cover the total too (since we moved it down slightly at one point). 

![Screenshot 2024-06-11 at 2 53 40 PM](https://github.com/phetsims/mean-share-and-balance/assets/7852916/e6dfa4f7-7c14-4af6-8757-7f4cf9815067)

So, can you please move the Total readout (back) over to the right side?

**Comment by marlitas** [comment]
Moved to the right! I also reduced the top margin to give a bit more space between the stacked candy bars.

<img width="371" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/50178db6-d2c3-4ae0-b949-b98906e67b5c">

**Comment by marlitas** [comment]
@amanda-phet feel free to close if all looks good!

**Comment by amanda-phet** [comment]
Looks great! Thanks!
