### ISSUE TITLE
Increase touch area for distribution mode radio buttons?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#279]
Was just playing with the sim and thought the distribution mode radio buttons were a little hard to press. What do you think about increasing the touch area a little vertically?

![image](https://github.com/phetsims/mean-share-and-balance/assets/6396244/5792ad20-c3dd-41de-ad6d-2ddef1a3cd48)

Related to #270

**Comment by amanda-phet** [comment]
Yes! That was the one thing in my touch area review I wondered if we should change, but didn't mention it. Making them a little taller sounds great.

**Comment by marlitas** [comment]
I increased the touch area in the y-direction by 8 pixels. Over to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks great. Thanks!
