### ISSUE TITLE
Is all artwork in assets/ ?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#282]
It is difficult to tell from looking a the file names. Several resources may be in the same .ai file. But is all artwork available in the assets/ directory?

For #270

**Comment by jessegreenberg** [comment]
I noticed https://github.com/phetsims/mean-share-and-balance/issues/268 so this can probably be closed.

**Comment by marlitas** [comment]
Yes, I believe all artwork has been accounted for in assets. I will close. Thanks!
