### ISSUE TITLE
Sounds missing from assets/

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#283]
I noticed the following sounds are missing from assets/.

- runningWater.mp3
- sotSineMultiOctaveLoop.mp3

For #270

**Comment by marlitas** [comment]
These sounds were for testing and we decided not to use them. I went ahead and removed them, but would like to double check with @jbphet to make sure he didn't want to do anything else there.

**Comment by jbphet** [comment]
Looks like we have all the sound assets in place, so we can call it good and move on.  Closing.
