### ISSUE TITLE
Document and expand unit tests

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#284]
Nice to see unit tests set up in this repo! But I can't really tell what "distribute ripple" is testing. Can you please add some documentation to this file?

Are there any other unit tests that would be beneficial to add?

For #270.

**Comment by marlitas** [comment]
I added documentation to the distribute ripple test. @jbphet and I also discussed adding more unit tests and although we agree that they are beneficial, we feel like the value in adding them would have been significantly earlier in the process. We don't think it feels like a good use of our time now. We do recognize that unit tests should be more of a priority in future sim development.

Closing.
