### ISSUE TITLE
A couple colors outside of MeanShareAndBalanceColors.ts

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#285]
There are just a few colors outside of MeanShareAndBalanceColors.ts, I noticed them in 

- LabTableNode
- WaterLevelTriangleSlider

There are couple instances of 'white' and 'black' for fills and strokes. I don't think they all need to be in the colors file, but thought I would mention in case they are important and should be available as a ColorProfileProperty.

For #270

**Comment by jessegreenberg** [comment]
I asked for consult on slack and colors only need to be in this file if used in more than once place. Feel free to close if you wish.

**Comment by marlitas** [comment]
I still prefer to have all colors in the colors file, so I went ahead and moved it over. Thanks!
