### ISSUE TITLE
Various documentation improvements

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#286]
- [x] Can you please add documentation for these constructor arguments for SharingModel? The names are great, but documentation will help a maintainer quickly understand this class without inspecting the implementation.

```js
  public constructor( snackCreator: ( options: SnackOptions ) => T,
                      snackStackingFunction: ( plateXPosition: number, index: number ) => Vector2,
                      handleFraction: ( plate: Plate<T>, fraction: Fraction ) => void,
```

- [x] Also, this option in Plate.js? Documentation below makes it seem to be used for debugging, but documenation at the option declaration would be helpful.

```js
linePlacement: number;
```

- [x] Also this option in MeanCalculationPanel?

```js
zeroDataMessageProperty?: LocalizedStringProperty | null;
```

- [x] Also the options in NotepadNode?

- [x]  Also for the Properties in BalancePointSceneModel?

```js
  public readonly totalKickDistanceProperty: TReadOnlyProperty<number>;
  public readonly targetNumberOfBallsProperty: Property<number>;
  public readonly meanPredictionFulcrumValueProperty: Property<number>;
```

- [x]  What are these values in BalancePointSceneModel?

```js
        rightSkewedData: [ 0, 25, 45, 30, 18, 12, 10, 5, 4, 4, 4 ],
```

- [x]  The NumberSpinnerSoundPlayer in BalancePointControl.ts. Why do you need a custom one? Why does it play the "release" sound?

- [x]  These options in soccer-common/SoccerCommonScreenView:

```js
  physicalRange: Range;
  chartViewWidth: number;
  numberLineXMargin: number;
  groundPositionY?: number;
```

- [x]  Also `linePlacement` in Cup.ts.

- [x]  Can you please document this logic? It looks like an important design decision but difficult to understand reasoning without context. https://github.com/phetsims/mean-share-and-balance/blob/ae8f092529925c281d8f3247476dd297b2c6b759/js/level-out/model/LevelOutModel.ts#L205-L208

For #270

**Comment by marlitas** [comment]
All the above requests have been adressed. @jessegreenberg can you check and see if those documentation updates help?

**Comment by jessegreenberg** [comment]
I reviewed the above commits, the documentation is excellent. Thanks!
