### ISSUE TITLE
Logic for '≈' in MeanCalculationPanel

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#289]
This is more of a design question, I was curious why `≈` is displayed in decimal format when the representation is accurate. For example, in the following. Is this right, or should it use `=`?

![image](https://github.com/phetsims/mean-share-and-balance/assets/6396244/6961ee6c-d7b9-4ab3-a6ef-aba8aa1d63fd)

For #270.

**Comment by marlitas** [comment]
Yeah... I was wondering if this was going to come up. @amanda-phet what would you like? Should it only display when the number isn't rounded?

**Comment by amanda-phet** [comment]
I hadn't thought of this. If it's an exact value I think it would be better to show an '=' and only show '≈' when it's rounded.

**Comment by marlitas** [comment]
This was addressed when I did some refactoring in https://github.com/phetsims/mean-share-and-balance/issues/280. @amanda-phet can you review and see if the behavior feels appropriate?

**Comment by amanda-phet** [comment]
Looks good to me!
