### ISSUE TITLE
Usage of excludeInvisibleChildrenFromBounds: false

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#292]
There are a few places where I see `excludeInvisibleChildrenFromBounds: false`. Can these be removed, or can you document why they are necessary?

For #270.

**Comment by marlitas** [comment]
A couple were not necessary. I left documentation for the one used in an `HBox`. @jessegreenberg can you review and let me know if any more documentation would be helpful.

**Comment by jessegreenberg** [comment]
Great, thanks. And that will be helpful documentation in MeanPredictionFulcrumSlider. Closing.
