### ISSUE TITLE
Should isResettingProperty be moved to scenery-phet?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#294]
soccer-common has an isResettingProperty to control sounds during the reset. Would this be beneficial for other sims in scenery-phet? 

#270

**Comment by jessegreenberg** [comment]
I noticed that ResetAllButton has this:

```js
  // A flag that is true whenever any "reset all" is in progress.  This is often useful for muting sounds that shouldn't
  // be triggered by model value changes that occur due to a reset.
  public static isResettingAllProperty: TReadOnlyProperty<boolean> = isResettingAllProperty;
```

Should that be used instead of the one in soccer-common?

**Comment by marlitas** [comment]
Thanks for catching that there is a `isResettingAllProperty` we can use. I went ahead and had us point to that Property instead and removed the soccer-common specific `isResettingProperty`.

@jessegreenberg this is ready for your review.

**Comment by jessegreenberg** [comment]
Great! I did not regression test but I am happy that `isRessetingProperty` could be deleted from soccer-common. Closing.
