### ISSUE TITLE
Floating interaction cue for Distribute screen

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#297]
Steps to reproduce:

1) Load the Distribute screen
2) Click on a chocolate bar with the mouse
3) Tab to the first chocolate bar with the keyboard
4) Pick up the bar with spacebar

You will notice a floating indicator in the QuestionBar:
![image](https://github.com/phetsims/mean-share-and-balance/assets/6396244/9852710a-ec53-450b-82a8-7883c5da1798)

For #270

**Comment by marlitas** [comment]
ooh! Fun!

**Comment by marlitas** [comment]
I was looking at the wrong Group Sort Property so the position wasn't updating when it was supposed to. That is now fixed and I also introduced a couple of pixel polishes so the cueing arrow is in a better position when using keyboard. 

@jessegreenberg can you confirm this looks fixed and review? Thanks!

**Comment by jessegreenberg** [comment]
I confirmed this is fixed. Nice fix, thanks!
