### ISSUE TITLE
Add more offset to candyBarShadowRectangle?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#298]
This is a cool effect! But it is so subtle I would not have noticed it without inspecting the code. Should the offset be bigger, or size increased? Or if it is not needed anymore, perhaps removed?

If the look is working as expected, feel free to close this issue.

```js
    const candyBarShadowRectangle = new Rectangle( 0, 0,
      MeanShareAndBalanceConstants.CANDY_BAR_WIDTH, MeanShareAndBalanceConstants.CANDY_BAR_HEIGHT,
      {
        fill: 'black',
        opacity: 0.2,
        cornerRadius: 1,
        visibleProperty: candyBar.draggingProperty
      } );
```

For #270

**Comment by marlitas** [comment]
Mmmm. I'll hand this off to @amanda-phet.

**Comment by amanda-phet** [comment]
Sure, I'm up for increasing the offset. Let's look at it synchronously to find the right values.

**Comment by marlitas** [comment]
We met and got it sorted out. Ready to close!
