### ISSUE TITLE
Should 'Auto Share' be an option when there is only one cup?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#30]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
https://github.com/phetsims/qa/issues/810

When there is only one cup on the screen should the 'Auto Share' checkbox be disabled?

**Visuals**
<img width="663" alt="Screen Shot 2022-06-09 at 2 04 31 PM" src="https://user-images.githubusercontent.com/87318828/172915164-425e00c8-b330-4556-99e4-4cfe247d9ebf.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean Share And Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.4/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.4 2022-06-08 18:34:30 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
If the user's intention is to have an open pipe when the second cup is added, checking 'Auto Share' is the only way to do that.

@samreid also mentioned that if 'Auto Share' is enabled when the user has multiple cups, and then becomes disabled when a user goes down to 1 cup, that may be less than optimal behavior. 

@amanda-phet what do you think? Feel free to close if the behavior is as desired.

**Comment by marlitas** [comment]
Design Meeting 6/15/22

@amanda-phet will keep an eye on this during interviews.

**Comment by marlitas** [comment]
Auto share functionality was removed from this screen. Closing.
