### ISSUE TITLE
Hard coded cups in distributeWaterRipple

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#301]
This function may break if the number of cups ever changes, is there a way to not hard code 7?

For #270.

**Comment by jessegreenberg** [comment]
Also, I made a small change to remove the disable lint rule directive, its slightly more complicated. Feel free to revert if you disagree with that choice.

**Comment by marlitas** [comment]
Oh great catch! We definitely shouldn't hard code that. I went ahead and updated with a constant we already had. I'm fine with moving the callback definition outside of the loop. Looks good. This was really straightforward so I'm going to go ahead and just close :-)
