### ISSUE TITLE
Remove Pipe.isCurrentlyClicked?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#302]
Can this Property be removed? If not, why is it needed in addition to `pipesOpenProperty`?

For #270.

**Comment by jessegreenberg** [comment]
The only usage is in PipeNode, it is toggled to true/false but I don't see any listeners on it.
```
      pipe.isCurrentlyClickedProperty.set( true );
      pipe.isCurrentlyClickedProperty.set( false );

```

**Comment by marlitas** [comment]
Hmmm. I have a feeling this is very vestigial. Perhaps when you could individually open and close pipes? I think it can definitely be removed. This was straightforward, doesn't need review.
