### ISSUE TITLE
Can BalancePointScreenView use msabSetPDOMOrder?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#304]
Then all screen views would go through this, which would be nice. If not, can you add a line to BalancePointScreenView that describes this (around where the pdom orders are set)?

For #270.

**Comment by marlitas** [comment]
Unfortunately `BalancePointScreenView` must extend `SoccerCommonScreenView` in order to take advantage of that common code which is why it doesn't have access to `msabSetPDOMOrder`. 

I added documentation to describe that. @jessegreenberg can you review?
