### ISSUE TITLE
Sync button toggles enabled state when moving bars

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#305]
While testing #295 I noticed the following behavior with the sync button, is this expected? Feel free to close if so.

![demo](https://github.com/phetsims/mean-share-and-balance/assets/6396244/b8253453-07d7-4f51-832d-7ffd0057879b)

Also related to #270.

**Comment by jessegreenberg** [comment]
Looking at this a bit more, I think it is going in and out of sync, and so this is expected behavior. Feel free to close.

**Comment by marlitas** [comment]
Yes, this is expected. Thanks!
