### ISSUE TITLE
Add accessible names to pdom components

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#307]
@amanda-phet and I talked about adding in accessible names throughout the sim. We think this could be done quickly without much fuss (but add a lot of value), before QA testing.

**Comment by terracoda** [comment]
Great News! 

@marlitas, please make note of any implementation pain points because having accessible names on interactions is essential for several WCAG Level A and AA criteria.

**Comment by terracoda** [comment]
Also, please reach out if you get stuck or have questions.

**Comment by marlitas** [comment]
@terracoda this is great to know. I will prioritize to get your input sooner rather than later.

**Comment by terracoda** [comment]
###Screen 1
- the Pipe Switch toggle button in the notebook is missing a name. This is an interesting description challenge because you have a toggle button and a on/off switch that control the same interaction.
- the predict mean pencil is missing a name.

Any chance the values on the sliders can be rounded to two decimal places before being read out? If this is a big deal just leave it as-is.

###Screen 2
- The bar in the notebook should have a button role before it is grabbed, and the button's name should be "Grab Candy Bar" or "Grab Bar".
- The counting of the plates start at "0", but the people start at 1, so there is no direct match there which is strange.
- the Sync button's name might be more clear as "Sync Data" or "Sync to Data" or "Sync with Plates"?

...to be continued.

**Comment by marlitas** [comment]
I went ahead and applied some of the above notes. 

@terracoda I have a question about the button for `Grab Candy Bar` though. What if there are not candy bars? We can still focus on that area as was requested for GroupSortInteraction, but there are no candy bars to grab. We have this same situation in Balance Point.

**Comment by marlitas** [comment]
> The read out of the value is automatic and with no rounding, the number is read out to like 10 decimal places. Any chance the values on the sliders can be rounded to two decimal places before being read out? I realize this is not an accessible, but rather a value.

I'm not sure how comfortable I feel about doing this without messing up the rest of the model of the sim... Let me look into it.

**Comment by terracoda** [comment]
@marlitas , I realize rounding can cause issues. I have plenty of experience there. Let’s just focus on the names for now. I still need to listen to screens 2,3 and 4.

**Comment by terracoda** [comment]
@marlitas asked:
> @terracoda I have a question about the button for Grab Candy Bar though. What if there are not candy bars? We can still focus on that area as was requested for GroupSortInteraction, but there are no candy bars to grab. We have this same situation in Balance Point.

On the Balance Point screen, you have a message. I would suggest doing the same on screens 2 and 3.

**Comment by terracoda** [comment]
To Summarize these ideas, maybe this is more clear.
![Screenshot 2024-06-30 at 15 22 18](https://github.com/phetsims/mean-share-and-balance/assets/1902116/2bb6cf6f-1e74-4cee-91a3-b099d6670339)
![Screenshot 2024-06-30 at 15 22 31](https://github.com/phetsims/mean-share-and-balance/assets/1902116/c2accc05-61b9-49d2-9e0b-f26850fc6dd2)

**Comment by marlitas** [comment]
Changes to apply:
- Water Level Cup 1 => Cup 1 Water Level
- Pipe Switch => Pipe Flow
- Plate 1 => Person 1 Candy Bars
- After Grabbing Candy Bar: Grab Candy Bar => Movable Candy Bar
- Sync with Plates => Sync
- Implement radio button group with heading: "Apple Actions" (Look to ratio and proportion or molecules and light)
- Plate 1 => Person 1 Apples
- Implement radio button group with heading: "Fulcrum Options"
- Movable Fulcrum => Manual Fulcrum
- Fixed Fulcrum => Automatic Fulcrum


Take Aways:
- @amanda-phet will talk to design team about changing the checkbox label "Total" to "Total Count"

**Comment by jbphet** [comment]
Over in #227 I applied some changes that help the situation that @terracoda identified above when she said:

> With no rounding, slider values are read out to like 10 decimal places.

The water level sliders now read out to a max of 4 decimal places, and only do that in unusual circumstances.  For the most part they are now reading out to 1 or 2 decimal places.

**Comment by marlitas** [comment]
I went ahead and changed the group sort interaction for candy bars to be:
Before Grabbing: "Grab or select candy bar"
After Grabbing: "Move candy bar"

I know we were still nailing that down, but that should be pushed up it @terracoda or @amanda-phet want to take a look.

**Comment by marlitas** [comment]
- [ ] change "predict mean handle" => "Prediction Mark"
- [ ] Capitalize "candy bars" and "apples"

**Comment by marlitas** [comment]
I believe everything has been addressed as requested now. Over to @amanda-phet and @terracoda for design review.

Next up will be me moving the strings into the strings file, so please do not close quite yet.

**Comment by terracoda** [comment]
@amanda-phet and @marlitas, the "Check" button that checks the balance on screen 4 was not in my table. I suggest changing both the visual name and the accessible name to "Check Balance." I can't imagine any pedagogically harmful side-effect of adding "Balance" to that name. It just makes the action much clearer. 

I would suggest making that the accessible name regardless of whether if fits on the screen or not. Which makes me want to circle back to the "Total" check box.

**Comment by terracoda** [comment]
I am opening a separate issue for Group Sort. It is more complicated.

**Comment by marlitas** [comment]
> I am opening a separate issue for Group Sort. It is more complicated.

I do want to emphasize, though I do believe that nailing down the group sort behavior is important, I am not considering it blocking for MSaB. It may be out of scope for this particular publication. Not to say that we shouldn't do the work, it just might not be prioritized right now depending on the lift required.

**Comment by amanda-phet** [comment]
> @marlitas and @marlitas if you are ammenable, I would like the following updates:
> 
>  "Total Number of Candy Bars" for accessible name
>  "Total Number of Apples" for accessible name


That sounds good to me! 

I think "Check Balance" is too long for the button. Did you notice it also turns into "Reset" once pressed? I wonder if we should do "Check Prediction" or "Check Balance for accessible name? and "Reset Pillars" for the other button?

**Comment by marlitas** [comment]
@terracoda & @amanda-phet should I also change to accessible name in the Balance Point screen to "Total Distance"?

**Comment by marlitas** [comment]
I went ahead and changed the total on the Balance Point screen as well. It felt more consistent.

**Comment by terracoda** [comment]
@marlitas, Re "Total Distance" I forgot to put it in the list (sorry). I wanted to ask if it could be both accessible and visual names, since it wasn't confusing like the other totals. I leave that decision to you both.

@amanda-phet - re the check balance button, I have not fully played with it. I need to look at all the words to decide the check balance name, but I do like "Reset Pillars". That adds another detail to the words.

**Comment by marlitas** [comment]
> I wanted to ask if it could be both accessible and visual names, since it wasn't confusing like the other totals. I leave that decision to you both.

I think the decision was to keep it consistent between all the screens. @amanda-phet can you confirm?

**Comment by terracoda** [comment]
@amanda-phet and @marlitas, I think the list of visual and accessible names that we agreed upon are in the check list in https://github.com/phetsims/mean-share-and-balance/issues/307#issuecomment-2206803181

**Comment by terracoda** [comment]
Close this issue when all names are in except the Group Sort names. This names will be followed in https://github.com/phetsims/scenery-phet/issues/860

**Comment by marlitas** [comment]
All the accessible names have been updated. I am creating a new issue to track moving the strings to the strings file: https://github.com/phetsims/mean-share-and-balance/issues/309
