### ISSUE TITLE
Move accessibleName strings to MSAB Strings file

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#309]
From https://github.com/phetsims/mean-share-and-balance/issues/307. All strings should be in the Strings file for possible future translation.

**Comment by marlitas** [comment]
I believe this has been completed. Over to @jbphet for review.

**Comment by jbphet** [comment]
It looks like the strings are in the English string file and all correctly nested under the "a11y" key.  That should do the trick.  I'll try to remember to double check that none of the a11y strings are appearing in the translation utility once we've published the sim, but am reasonably confident that this was done correctly and we won't have that problem, so I'll go ahead and close.
