### ISSUE TITLE
Sim title incorrect

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#31]
For https://github.com/phetsims/qa/issues/810

Isn't the title of the sim:   
           Mean: Share and Balance

<img width="504" alt="Screen Shot 2022-06-10 at 1 15 30 PM" src="https://user-images.githubusercontent.com/87318828/173118238-c0ddf78d-961d-4bc4-a393-ff179268768c.png">

**Comment by marlitas** [comment]
Oops! Fixed and pushed to master branch. New dev build unnecessary. Closing.

**Comment by Nancy-Salpepi** [comment]
@marlitas I was just on master and I see that the "a" in "and" is capitalized. I believe it should be lowercase to look like this:

Mean: Share and Balance

**Comment by marlitas** [comment]
@Nancy-Salpepi Sorry for closing prematurely. "And" is now lowercased. Can be checked on phettest.

**Comment by Nancy-Salpepi** [comment]
Title looks good now 🙂 @marlitas!

**Comment by marlitas** [comment]
Closing with QA approval.
