### ISSUE TITLE
Value of `maxCupsProperty` not respected after reset

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#311]
While reviewing the `examples.md` document and trying out some of the examples contained therein, @marlitas and I found that the value of `meanShareAndBalance.levelOutScreen.model.maxCupsProperty` wasn't having any effect after the sim was reset.  Here is the sequence to reproduce:

- Open the sim in phet-io studio
- Go to the first screen ("Level Out")
- In studio, find the `meanShareAndBalance.levelOutScreen.model.maxCupsProperty` property and set its value to 4
- Increase the number of cups using the number spinner, verify that it doesn't let you go past 4
- Press the reset button
- Again increase the number of cups until it won't let you go further.  It allows up to 7 cups.

Screenshot:

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/22e8c5bb-0448-45c2-b156-fae3a1914a24)

**Comment by jbphet** [comment]
@marlitas is going to take a look at this.  During our Zoom conversation she seemed to have a good idea of what was leading to the behavior and how to potentially address it.

**Comment by marlitas** [comment]
This was a great catch on @jbphet's part. The sim should now be respecting max values on reset. This was occurring mostly on the first three screens, but the 4th screen did encounter some buggy behavior with the number spinner. That is now all taken care of and should be working well. 

Over to @jbphet to confirm and review.

**Comment by jbphet** [comment]
I tested the behavior on all three screens using phet-io Studio, and the behavior now seems correct.  The code changes look reasonable.  Closing.
