### ISSUE TITLE
Character is missing a nose

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#314]
For https://github.com/phetsims/qa/issues/1105, one of the Latin American girls is missing a nose. 
<img width="199" alt="Screenshot 2024-07-09 at 12 22 18 PM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/f4011b7d-c87c-4dda-927b-5147157f2588">

Giving the other characters a closer look now and will add to this issue if I see anything.

**Comment by Nancy-Salpepi** [comment]
I don't see any other oddities with the characters.

**Comment by amanda-phet** [comment]
Thanks for checking! If you have time, can you check Center and Variability on phettest as well, all regions, to see if there are any other oddities? MSaB is a subset of the characters in soccer-common, and the rest will be visible in Soccer Common.

**Comment by Nancy-Salpepi** [comment]
Looking in Soccer Common I see:

1. Africa kicker #2 has no nose when poised to kick: 
https://github.com/phetsims/soccer-common/blob/main/images/africa/africaKicker02PoisedToKick.svg 
2. Africa kicker #11's left foot has no color when poised to kick: 
https://github.com/phetsims/soccer-common/blob/main/images/africa/africaKicker11PoisedToKick.svg
3. Asia kicker #12 is missing the white stripe at the top of this shirt when kicking: 
https://github.com/phetsims/soccer-common/blob/main/images/asia/asiaKicker10Kicking.svg
4. Asia kicker #13 is missing some color in his hat while standing 
https://github.com/phetsims/soccer-common/blob/main/images/asia/asiaKicker13Standing.svg
5. Latin America kicker #11 has a white airplane and white trim while standing and then it changes to a light gray plane and trim. 
https://github.com/phetsims/soccer-common/blob/main/images/latinAmerica/latinAmericaKicker11Standing.svg
https://github.com/phetsims/soccer-common/blob/main/images/latinAmerica/latinAmericaKicker11PoisedToKick.svg
6. Oceania kicker #14's eyes aren't filled in when poised to kick 
https://github.com/phetsims/soccer-common/blob/main/images/oceania/oceaniaKicker14PoisedToKick.svg

Not all of these were obvious when testing CaV on main--I noticed #4 and #6 before checking in Soccer Common.

**Comment by amanda-phet** [comment]
Thank you SO much!! I'll get on these now :)

**Comment by amanda-phet** [comment]
- [ ] latin America kicker 01 standing
- [ ] Africa kicker 2 has no nose when poised to kick:
https://github.com/phetsims/soccer-common/blob/main/images/africa/africaKicker02PoisedToKick.svg
- [ ] Africa kicker 11's left foot has no color when poised to kick:
https://github.com/phetsims/soccer-common/blob/main/images/africa/africaKicker11PoisedToKick.svg
- [ ] Asia kicker 12 is missing the white stripe at the top of this shirt when kicking:
https://github.com/phetsims/soccer-common/blob/main/images/asia/asiaKicker10Kicking.svg
- [ ] Asia kicker 13 is missing some color in his hat while standing
https://github.com/phetsims/soccer-common/blob/main/images/asia/asiaKicker13Standing.svg
- [ ] Latin America kicker 11 has a white airplane and white trim while standing and then it changes to a light gray plane and trim.
https://github.com/phetsims/soccer-common/blob/main/images/latinAmerica/latinAmericaKicker11Standing.svg
https://github.com/phetsims/soccer-common/blob/main/images/latinAmerica/latinAmericaKicker11PoisedToKick.svg
- [ ] Oceania kicker 14's eyes aren't filled in when poised to kick
https://github.com/phetsims/soccer-common/blob/main/images/oceania/oceaniaKicker14PoisedToKick.svg

**Comment by amanda-phet** [comment]
@marlitas these are committed to soccer-common (see above) and ready for you to run the command to integrate them :)

**Comment by marlitas** [comment]
The svg files were updated above. This is ready for @Nancy-Salpepi to review and confirm all looks well on main. Feel free to close.

**Comment by Nancy-Salpepi** [comment]
AsiaKicker10 kicking--the image has an extra white rectangle which shows up in CaV:
<img width="239" alt="Screenshot 2024-07-12 at 9 28 57 AM" src="https://github.com/user-attachments/assets/7a65abb5-0556-420a-bcb9-ddf7cbc2f3dd"><img width="317" alt="Screenshot 2024-07-12 at 9 28 32 AM" src="https://github.com/user-attachments/assets/bf65b354-38f9-4208-8495-d9e32297bee6">

**Comment by amanda-phet** [comment]
Thanks @Nancy-Salpepi ! 

@marlitas this is ready for you.

**Comment by marlitas** [comment]
svg updated above. Ready for @Nancy-Salpepi to review and confirm all looks well on main. Feel free to close.

**Comment by Nancy-Salpepi** [comment]
Looks good. Hopefully we found all the errors!
Closing.
