### ISSUE TITLE
Suggested changes to examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#317]
For https://github.com/phetsims/qa/issues/1105, in the examples.md the current directions for hiding the kick button are incorrect (or I am interpreting them incorrectly).

<img width="928" alt="Screenshot 2024-07-09 at 2 24 41 PM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/6623ab69-2b8e-4e62-bd52-e21849e3333d">

This is what I did:
1. Kicked 3 balls 
2. Set Max Property to 3 --> the kicked balls disappear and the Kick button is still present. 

If you flip the 2 steps, then the Kick Button won't be there.

**Comment by Nancy-Salpepi** [comment]
For this section I think it would be helpful to first have a step about setting the `predictMeanVisibleProperty` to True before setting its location and hiding the pencil:
<img width="911" alt="Screenshot 2024-07-09 at 2 29 24 PM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/962d59ae-f41e-48ec-a515-e2903e2a7fac">

**Comment by Nancy-Salpepi** [comment]
This one is for @marlitas:

Please feature:
`meanShareAndBalance.distributeScreen.model.meanPredictionProperty` 
`meanShareAndBalance.distributeScreen.view.meanPredictionLine.meanPredictionHandle.visibleProperty`

They are currently listed in the examples.md, but not featured.

**Comment by Nancy-Salpepi** [comment]
In the section "Determine if the notepad is displaying the mean" for the Balance Point Screen, change `meanPropertyValue` to `meanValueProperty`

<img width="917" alt="Screenshot 2024-07-09 at 4 51 34 PM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/2d047bbd-6d71-405f-8486-8b63068c7228">
<img width="917" alt="Screenshot 2024-07-09 at 4 57 41 PM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/b1761b7c-487a-4ce3-8ef2-822109bb8540">

**Comment by amanda-phet** [comment]
Thanks @Nancy-Salpepi ! I think all of those things look good now, if you want to take a peek (looking at the commit will make it easy to see the changes). 

@marlitas can you please feature these elements: 

- `meanShareAndBalance.distributeScreen.model.meanPredictionProperty`
- `meanShareAndBalance.distributeScreen.view.meanPredictionLine.meanPredictionHandle.visibleProperty`
- `meanShareAndBalance.balancePointScreen.model.sceneModel.kickDistributionStrategy`

**Comment by marlitas** [comment]
This is ready for review by @amanda-phet and @Nancy-Salpepi

**Comment by amanda-phet** [comment]
Thanks @marlitas those look good to me. 

@Nancy-Salpepi please feel free to close after you've reviewed examples.md to be sure it looks clear to you.

**Comment by Nancy-Salpepi** [comment]
@amanda-phet just wanted to note that this can also be done by direct interaction with the sim (using the number spinner):
>**Hide the Kick button**
The visibilily of the Kick button is determined by whether there are any balls available to be kicked. The button can be hidden using `maxKicksProperty`: first set `maxKicksProperty` to the desired number, then kick all balls onto the field.
`meanShareAndBalance.balancePointScreen.model.maxKicksProperty`


Also, would an instructor still want students to be able to use the decrement button afterwards? This would make the Kick button reappear. Not sure what the learning goal is.

**Comment by Nancy-Salpepi** [comment]
Everything else looks good on main.

**Comment by amanda-phet** [comment]
I added that extra note about how to kick the balls. I don't think we need to go into hiding the number spinner. Nodes have a visibleProperty, but the kick button does not because its visibility is controlled by the last ball being kicked, so that's why it has special instructions. Thanks for your review!
