### ISSUE TITLE
keyboard help dialog missing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#32]
https://github.com/phetsims/qa/issues/810

Since there is keyboard nav in this prototype, shouldn't there be a keyboard dialog?

**Comment by marlitas** [comment]
Keyboard help content dialog added. @Nancy-Salpepi please test on Phettest.

**Comment by Nancy-Salpepi** [comment]
@marlitas 
I'm not sure if phettest is acting up, but I don't see the keyboard help dialog.

**Comment by marlitas** [comment]
@Nancy-Salpepi Phettest should be up to date now!

**Comment by Nancy-Salpepi** [comment]
Looks good @marlitas!

**Comment by marlitas** [comment]
Closing after QA approval.
