### ISSUE TITLE
Confirm accessibleName behavior for Group Sort interactions

### ISSUE THREAD

**Issue by zepumph** [phetsims/mean-share-and-balance#321]
From https://github.com/phetsims/scenery-phet/issues/860, @terracoda and I have a design we are ready to proceed with. I'll implement, but I wanted a MSAB issue to ensure everything is still working well as we move forward. Assigning to me until implementation is done. This shouldn't take long to complete, so marking as blocking this sim for general completeness.

**Comment by zepumph** [comment]
Ok. This is ready for review by @terracoda and the MSAB team. @marlitas will you please take a look at the commits here, and feel free to update anything you want. I tried to be as light-handed as possible to update the accesibleNames.

**Comment by marlitas** [comment]
The implementation looks great. No concerns here. I'll hand it over to @terracoda to confirm it's all behaving as expected. Thanks!

**Comment by terracoda** [comment]
It's awesome :-) 

I am just exploring the idea of "Meter", "Mark", or "Meter Mark" for the soccer balls to replace "Stack."

**Comment by terracoda** [comment]
I think I might arrange the name differently when we have time to look into more description for this sim, but for now, I think we should swap "Stack" for "Meter", since we are talking distance here.

It's still true that the only sortable ball is the Top Ball, so let's just keep that for now unless there is a big reason to discuss more.

**Comment by amanda-phet** [comment]
@marlitas just wanted to be clear we'd like to change the word "stack" to "meter" for soccer balls (CaV and MSaB).

**Comment by marlitas** [comment]
Done above. @amanda-phet can you review and close if all looks well?

**Comment by amanda-phet** [comment]
Looks good to me!
