### ISSUE TITLE
Should cueing arrows disappear when item isn't interactive?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#322]
**Device**
Samsung
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/1105
In studio, if you remove interactivity with the fulcrum slider (`meanShareAndBalance.balancePointScreen.view.notepadNode.balanceBeamNode.meanPredictionFulcrumSlider.enabledProperty`) the cueing arrow still appears, even though you can't drag the object anymore.
**Visuals**
![enablearrows](https://github.com/phetsims/mean-share-and-balance/assets/41024075/35cbd491-8789-4c6f-9702-d84c33c3f99a)

**Comment by amanda-phet** [comment]
I think we discussed instrumenting the cue, but I don't remember what came out of the discussion. Is this something we can instrument @marlitas ? Or should I put something in examples.md about how to turn it off? (basically if you interact with it to remove it, the lack of cue arrow seems to be saved to the state)

**Comment by marlitas** [comment]
@amanda-phet my understanding is that we shouldn't instrument keyboard and mouse cues so that users can still get the cues if the item was interacted with before the wrapper was created. This is also how our cues are working for soccer balls and candy bars. I will tie the visibility of the mouse cues to the enabled property of the fulcrum. I think that will fix the underlying problem here.

**Comment by marlitas** [comment]
The cueing arrows will now disappear if the slider has been disabled. @amanda-phet let me know if that works for you.

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/7b50bf57-df0e-4dfa-8702-a2152a0a5028">

**Comment by amanda-phet** [comment]
Reviewed with @marlitas and she also added some documentation to `meanPredictionFulcrumSlider` so I think this is all looking good!

**Comment by Nancy-Salpepi** [comment]
I also see this with the soccer balls but may be related to https://github.com/phetsims/mean-share-and-balance/issues/337
<img width="563" alt="Screenshot 2024-08-01 at 2 01 49 PM" src="https://github.com/user-attachments/assets/9febc096-9381-4b21-b455-a902a34e3625">

**Comment by marlitas** [comment]
This question is being handled in https://github.com/phetsims/mean-share-and-balance/issues/337 since it is a special use case. Closing.
