### ISSUE TITLE
Error when holding down Kick Button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#324]
**Test device**
MacBook Air M1 chip and iPad 9th Generation

**Operating System**
14.5 and 17.5

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1105, on the Balance Point Screen holding down the Kick Button with touch or the mouse results in the Number of Balls number display to show a value greater than 7. Pressing Reset All then breaks the sim. 

**Steps to reproduce**
1. On the Balance Point Screen use the mouse to press and hold the Kick button (2 kicks will happen)
2. Repeat the above step 3 more times--the Number of Balls display will say 8
3. Press Reset All
4. Try to press anything on the screen
5. Using the iPad, press and hold down the Kick button (3 kicks happen)
6. Repeat the above step 2 more times--the Number of Balls display will say 9

**Visuals**
<img width="908" alt="Screenshot 2024-07-12 at 10 13 30 AM" src="https://github.com/user-attachments/assets/4428968d-4265-4868-86bd-2bc674bf1e33">
![IMG_1503](https://github.com/user-attachments/assets/a30579d6-f628-4243-b015-f262938df94c)
<img width="548" alt="Screenshot 2024-07-12 at 9 58 48 AM" src="https://github.com/user-attachments/assets/ac0ec024-0080-4d45-9b28-2a610ea913b7">

**Comment by marlitas** [comment]
I got distracted a bit with the glitchy animation when a kicker kicks to 0, so @jbphet and I implemented a fix for that. Doesn't address this main bug at all, but does make for a better and more consistent kicking experience. Was reviewed and approved by @amanda-phet. Commit above.

**Comment by marlitas** [comment]
I have been unable to reproduce, but the `fireOnHold` behavior is inconsistent regardless. I think this will be largely dependent on how we decide to proceed for https://github.com/phetsims/mean-share-and-balance/issues/320.

If we end up deciding that `fireOnHold: false` for number spinner, then I think that should be the same for the buttons.

**Comment by jbphet** [comment]
I can reproduce this on the dev version, and just tried to do so on main and the problem is gone.  Instead, the "Kick" button now supports press-and-hold, and doing so causes the kickers to kick the max number of balls and then the button disappears (and the kicking stops).

I think this is therefore fixed, and I'll mark is as ready-for-review and have it double checked in the next QA cycle.

**Comment by Nancy-Salpepi** [comment]
This is fixed in rc.1.
Closing.
