### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#33]
From CRC: Does it adequately describe the model, in terms appropriate for teachers? Has it been reviewed by the sim designer?

**Comment by samreid** [comment]
@marlitas and I observed that the model.md file needs to be adjusted based on recent design and implementation changes, thanks!

**Comment by marlitas** [comment]
model.md has been updated to reflect the most recent changes to the intro screen. @pixelzoom, can you review the changes?

**Comment by pixelzoom** [comment]
Looks good to me. But the designer typically signs off on model.md, so assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
I made a few edits, and also commented out a paragraph that I think is a little confusing and not necessary. I'll discuss with @marlitas what to do about that paragraph.

**Comment by amanda-phet** [comment]
I made one edit to that paragraph. 

Over to @marlitas to confirm if it all looks ok.

**Comment by marlitas** [comment]
Looks great. I added a couple of commas, but other than that looks good to me. Closing.
