### ISSUE TITLE
Wrong/No sound heard when closing the info dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#330]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1121, when closing the info dialog on screens 2-4 by pressing the X, the 'open' sound is heard. Also, no sound is heard when pressing `esc` to exit the dialog. If I press the Info button to close instead of the 'X', I do hear the 'close' sound.

**Steps to reproduce**
1. Go to screens 2,3 or 4 and press the Info button
2. Press the X to close the dialog
3. Press the Info button again
4. Press `esc`

**Visuals**

https://github.com/user-attachments/assets/98666a4a-9a88-4b6a-8450-d8ccee221767

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-rc.1/phet/mean-share-and-balance_all_phet.html
Version: 1.1.0-rc.1 2024-07-23 23:49:04 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1405x714
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
I also hear the open sound when pressing the 'X' to close the dialog using alt input.

**Comment by marlitas** [comment]
It looks like this cam from a simple typo in https://github.com/phetsims/tambo/issues/195. The commit to cherry pick is there.

That commit does not resolve the sound not playing on `esc`.

**Comment by marlitas** [comment]
escape key now triggers the close button sound as needed. Ready for cherry pick.

**Comment by Nancy-Salpepi** [comment]
Sounds good in rc.2.
Closing.
