### ISSUE TITLE
Interactive highlight changes size as I move bar around notepad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#331]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1121, on the Distribute screen with interactive highlights on, moving the bar around the notepad causes the outer highlight rectangle to continually change size.

**Steps to reproduce**
1. In Preferences turn on interactive highlights
2. Use the mouse to grab a bar from the notepad and move it to the left/right as far as you can

**Visuals**

https://github.com/user-attachments/assets/197b5d67-e393-4b91-a80c-c82eefa1f267

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Media: Distribuzione e Bilanciamento‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-rc.1/phet/mean-share-and-balance_all_phet.html
Version: 1.1.0-rc.1 2024-07-23 23:49:04 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1405x714
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by JaronDroder** [comment]
I'm seeing the same issue on safari for IOS

**Comment by marlitas** [comment]
Commit pushed above. Ready for cherry pick.

**Comment by Nancy-Salpepi** [comment]
This is fixed in rc.2.
Closing.
