### ISSUE TITLE
Improper amount/stacking of notebook apples is possible

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#333]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1121, on the Fair Share screen, when a notebook apple is about to split, pressing the sync button will result in the wrong number of apples being present and the stacking will look incorrect.

**Steps to reproduce**
1. On the Fair Share screen, increase the number of apples for Person 2 to nine
2. Press the Collect button
3. Press the Share button and right after the remaining apples have made it to the top to be split, press the Sync button

**Visuals**

https://github.com/user-attachments/assets/067feaf1-3e7a-4eb6-a1b4-03f65235feca

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Media: Distribuye y Equilibra‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-rc.1/phet/mean-share-and-balance_all_phet.html
Version: 1.1.0-rc.1 2024-07-23 23:49:04 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Language: en-US
Window: 1382x683
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
Addressed above. This issue is ready for cherry-pick.

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.2.
Closing.
