### ISSUE TITLE
Index of objects off in studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#338]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/1121
When looking at a candy bar or apple on the sketch pad in studio, the number of a particular bar is different in the model section vs the view section. These elements are not featured, so this may not be very important, but may trip up someone trying to work with a particular bar/apple. It looked like part of this may be that counting starts from 0 in one case and from 1 in another, but at least one apple was off by more than one.
**Visuals**
![candynumber](https://github.com/user-attachments/assets/8f2f023a-4681-41d7-80dd-042baf7b5bbf)

**Comment by marlitas** [comment]
Oh that is odd... may be a typo. I'll take a look.

**Comment by marlitas** [comment]
Fixed above. Ready to cherry pick.

**Comment by KatieWoe** [comment]
Ctrl and Alt no longer seem to work on these elements to take you to that object, so this is a bit hard to check.

**Comment by KatieWoe** [comment]
This does seem fixed in rc.2
