### ISSUE TITLE
Recommendation to add tick marks to bottom beakers

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#34]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/810. I noticed that, when tick marks are turned on, they only appear on the top beakers. There are situations where a user may find it helpful to also have tick marks on the bottom beakers. For example, if the top beaker are set to share automatically and you want to add a specific amount, it is easier to track on the bottom beakers, while the top beakers can show the mean change in real time. If this has a design reason behind it, feel free to close, but I thought it would be useful.

**Visuals**
<img width="614" alt="lowertic" src="https://user-images.githubusercontent.com/41024075/173452124-e818127a-2b58-46db-8e99-53ce9d670850.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Mean Share And Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.4/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.4 2022-06-08 18:34:30 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
Assigning to @amanda-phet to comment on the design aspect of this.

**Comment by marlitas** [comment]
Design Meeting 6/15/22:
Decision, let's go for it.

**Comment by marlitas** [comment]
Tick marks have been added to bottom beakers when "Show Ticks" is enabled and is pushed up to master. Assigning to @amanda-phet for final approval before closing.

**Comment by marlitas** [comment]
Closing since tick marks on bottom beakers have been approved in past design meetings.

**Comment by marlitas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Screen 1 Design](https://trello.com/c/NkWVx0dJ/1-screen-1-design)
