### ISSUE TITLE
solid interactive highlight can appear when moving 2 balls with multitouch

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#347]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.6.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1134, on the Balance Point screen with interactive highlights enabled, it is possible to make the highlight a solid square instead of a dashed one while moving two balls at the same time and lifting your fingers every once in a while. It was easiest to reproduce when the balls were on top of one another, but that is not a requirement for it to happen. 
@KatieWoe is also able to reproduce

**Steps to reproduce**
It is difficult to have exact steps
1. Turn on interactive highlights
2.  Move two balls at once, releasing every once in a while so that which ball has the focus changes.

**Visuals**
Here are 2 videos but the screen recording doesn't show touches so it is hard (impossible) to tell exactly what I did.

https://github.com/user-attachments/assets/b575f89b-010d-4199-8051-78b395738863

https://github.com/user-attachments/assets/1fe8da35-edf5-4b74-bdda-b58075508451

**Comment by Nancy-Salpepi** [comment]
@KatieWoe please add any other thoughts you have on steps to reproduce.

**Comment by KatieWoe** [comment]
I'd seen this when slightly zoomed in if I slide a finger over the ball instead of directly grab it. From the videos above this does not seem necessary to the bug.

**Comment by jbphet** [comment]
I am unable to duplicate this on my Dell Windows laptop with touchscreen after about 5 minutes of testing.  This seems like a low severity bug that doesn't interfere with the use of the sim in any significant way.  @marlitas and I are thinking that this should not block the release of the sim and we should just ignore it.  If it seems to get worse (easier to reproduce or having more severe impact on the sim), we'd be happy to do more investigation.  Closing.
