### ISSUE TITLE
Toggle Checkboxes dialogue info missing from Keyboard Shortcuts Popup Menu

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/mean-share-and-balance#349]
**Test device**
MacBook Pro

**Operating System**
Monterey 12.7.6 

**Browser**
Chrome

Here is the standard keyboard shortcut menu with toggle checkboxes [Space] present.
![screenshot_2024-08-16_at_4 21 49___pm](https://github.com/user-attachments/assets/16e3ee75-8e19-47fe-b081-d646c7cabbdc)

Here is my screenshot with that info missing. 
![Screen Shot 2024-08-16 at 2 09 03 PM](https://github.com/user-attachments/assets/35052673-f44f-43ac-83f8-9180fd662223)

**Comment by Nancy-Salpepi** [comment]
Tagging https://github.com/phetsims/qa/issues/1134

**Comment by Nancy-Salpepi** [comment]
Also noting that some of the controls for the soccer balls are missing from the dialog. I'm assuming it was a spacing issue, but didn't see anything about it in https://github.com/phetsims/mean-share-and-balance/issues/266. The "jump ball to tick mark" might be a nice thing to add.

Here are the instructions from CaV:
<img width="382" alt="Screenshot 2024-08-17 at 9 33 40 AM" src="https://github.com/user-attachments/assets/53aa279a-45ab-4670-8831-84fcac5d1086">

**Comment by amanda-phet** [comment]
Let's add checkboxes to the Basic Actions! I never looked closely at that section because I thought it was generic for all sims. 

@Nancy-Salpepi I intentionally didn't include all of those soccer-ball options because we were short on space, and they aren't as useful in this sim with a range of 0-10 instead of 0-15.
