### ISSUE TITLE
"Sync" icon same/similar to "Refresh"

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#35]
While testing to ensure the ResetShape name change in common code didn't cause any bugs or breaks, I found a refresh button that looks eerily familiar to the sync icon we created.

Refresh:
<img width="113" alt="Screen Shot 2022-06-16 at 4 12 52 PM" src="https://user-images.githubusercontent.com/42476338/174185686-00fd94ba-f358-47e1-a73f-fec62d768a4c.png">

Sync:
<img width="113" alt="Screen Shot 2022-06-16 at 4 16 39 PM" src="https://user-images.githubusercontent.com/42476338/174185824-5132d708-003e-4822-90a2-b4cc71eed918.png">

I wanted to check:
- Are we okay with using a similar icon that may have a different meaning in other sims?
- Should we change the sync icon?
- Should we use refresh instead if that is more prevalent? 
- If we want to keep the "Sync" word, do we want to use the refresh icon or keep the one we currently have? (They rotate in different directions, arrow points are curved vs. pointed, etc. )

**Comment by marlitas** [comment]
@pixelzoom stated in: https://github.com/phetsims/mean-share-and-balance/issues/73

> For code review #41 ...
> 
> Re this checklist item:
> 
> > * [ ]   Is there anything that should be generalized and migrated to common code?
> 
> SyncIcon is a likely candidate. But I'd also like to see it use fontawesome fa:refresh icon, see https://fontawesome.com/v4/icon/refresh.

If designer determines we would rather use the sync icon rather than the refresh icon, sync icon will be moved to common code.

**Comment by samreid** [comment]
During the code review, @pixelzoom said:

> //REVIEW Recommended to use fontawesome fa:refresh icon here instead. See https://fontawesome.com/v4/icon/refresh

**Comment by pixelzoom** [comment]
To clarify... My main feedback in this issue is to use fontawesome icons where possible.  In this case, there's zero UX improvement to be gained by using a slightly different "sync" or "refresh" icon, and lots to be gained -- in design, development, and mainteance cost.   PhET had the same problem with the "trash" icon for awhile, and the cost to standardize (ultimately on a fontawesome icon) was not insignificant.

**Comment by ariel-phet** [comment]
I have to say I would personally be in favor of a significantly different icon. I don't think the refresh icon communicates what is going on particularly well (and I think sync icons generally refer to something like syncing data between an external hardrive or the cloud or such). Here is a font awesome that I think communicates the action occurring in this sim better:

https://ramptshirts.com/assets/vendor/font-awesome/js-packages/@fortawesome/fontawesome-free/svgs/solid/arrow-down-up-across-line.svg

![sync possible](https://user-images.githubusercontent.com/4051174/177824908-3748c36e-ae95-4707-80ea-e1f52d3d8553.png)

**Comment by amanda-phet** [comment]
@pixelzoom said

>To clarify... My main feedback in this issue is to use fontawesome icons where possible. In this case, there's zero UX improvement to be gained by using a slightly different "sync" or "refresh" icon, and lots to be gained -- in design, development, and mainteance costs. PhET had the same problem with the "trash" icon for awhile, and the cost to standardize (ultimately on a fontawesome icon) was not insignificant.

I understand, and am on board with using the same icon as I don't think the difference in icons communicates a difference in functionality. So I'd either want to use the same icon, or consider an entirely different one. 

@ariel-phet the line through those arrows looks to me like a negation. What about just two arrows?
![image](https://user-images.githubusercontent.com/7852916/177829865-e7c225ae-99e6-4e8a-944f-1820f3c0a83d.png)

**Comment by ariel-phet** [comment]
@amanda-phet yes I think that up down arrow would work great. My vote is for an entirely different one so we don't overload the meaning of the "refresh" icon which tends to so far have a specific meaning in lots of our sims (particularly in games).

**Comment by marlitas** [comment]
Conversation with @amanda-phet, I will implement, Up Down arrow icon, with "sync" text slightly larger.

**Comment by marlitas** [comment]
@amanda-phet the font-awesome icon you provided is a "pro" icon which we do not have a license for. We are going to create our own that matches as closely as possible!

**Comment by pixelzoom** [comment]
@marlitas scenes-phet `LineArrowNode` might help you with creation of that icon.

**Comment by pixelzoom** [comment]
In the above commit, I added feature to `LineArrowNode` to support the "rounded" look of the fontawesome icon. See LineArrowNodeOptions `lineJoin` and `lineCap`.  There's also a demo in the scenery-phet _Components_ screen, screenshot below:

<img width="377" alt="screenshot_1794" src="https://user-images.githubusercontent.com/3046552/180483407-bb675847-264f-4cce-bb03-290839784aeb.png">

**Comment by pixelzoom** [comment]
In the above commit, I added feature to `LineArrowNode` to support the "rounded" look of the fontawesome icon. See LineArrowNodeOptions `lineJoin` and `lineCap`.  There's also a demo in the scenery-phet _Components_ screen, screenshot below:

<img width="377" alt="screenshot_1794" src="https://user-images.githubusercontent.com/3046552/180483407-bb675847-264f-4cce-bb03-290839784aeb.png">

**Comment by marlitas** [comment]
@pixelzoom thank you for those quick option additions. Very helpful! 

Here is a screenshot of the updated sync icon:
<img width="257" alt="Screen Shot 2022-07-22 at 11 05 43 AM" src="https://user-images.githubusercontent.com/42476338/180489420-bbf9aca5-2472-4ccf-93c2-b5ac33c1fe42.png">

@samreid and I drew this out to match the font-awesome icon as much as possible. We believe some adjustments may be needed due to the exact context and sizing of the icon's use, but wanted to get designer feedback first.

**Comment by amanda-phet** [comment]
That looks good to me!

**Comment by marlitas** [comment]
Awesome! Will close. If further discussion is needed feel free to re-open!
