### ISSUE TITLE
Sound of reset all button is odd in launched sims

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#353]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/1138
I noticed that the sound of the reset all button seemed a bit cut off in a sim launched from studio compared to the sound in the base sim.
**Visuals**

https://github.com/user-attachments/assets/5e3a9c8a-fd3a-4bae-bed5-828549dca500

**Comment by Nancy-Salpepi** [comment]
This has been around for a while and not specific to MSaB.  
Here is one issue I found on it: https://github.com/phetsims/tambo/issues/159

**Comment by jbphet** [comment]
@KatieWoe - I'm starting to investigate this, and I have a couple of observations that I'd like for you (or someone on the QA team) to confirm.  First, I went back and checked the recent RC.3 and RC.4 versions for this sim, and as far as I can tell, the problem exists there too, meaning that this is not new to this RC (RC.5).  Would you agree with that?

Second, I just checked the Greenhouse Effect phet-io version, which was release a few months back, and it seems like it exists there too.  Are you hearing the same thing?

**Comment by KatieWoe** [comment]
I agree. Nancy pointed out in https://github.com/phetsims/mean-share-and-balance/issues/353#issuecomment-2312731447 that this isn't a new bug. I just hadn't noticed it until now. Sorry about that.
