### ISSUE TITLE
implementation-notes.md

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#36]
From the CRC:
- [ ] Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers?

**Comment by samreid** [comment]
@marlitas and I observed that the documentation needs to be adjusted based on recent design and implementation changes, thanks!

**Comment by pixelzoom** [comment]
Looks good. I made a few commits (see above).  In addition to a couple of typos, we typically provide links to source code, so I added those. Let me know if you have questions. Feel free to close after reviewing.

**Comment by marlitas** [comment]
Looks great. Thanks for the fixes! Closing.
