### ISSUE TITLE
Memory Leak Test

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#38]
Memory Leak Test 6/23/22
<img width="293" alt="Screen Shot 2022-06-23 at 2 35 33 PM" src="https://user-images.githubusercontent.com/42476338/175394799-6b0b2c38-44dc-43f9-8df7-99219b510ec6.png">

**Comment by marlitas** [comment]
PhET-iO brand
<img width="289" alt="Screen Shot 2022-06-23 at 3 54 15 PM" src="https://user-images.githubusercontent.com/42476338/175415767-1957d7fb-279b-444a-95e1-408d5834263e.png">

**Comment by pixelzoom** [comment]
Looks good as of 6/27 for code review https://github.com/phetsims/mean-share-and-balance/issues/41.
