### ISSUE TITLE
TypeScript error in MeanShareAndBalanceModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#4]
There's a TypeScript error in LevelingOutModel.ts, showing up in CT:

```
% cd mean-share-and-balance
% tsc -b
js/leveling-out/LevelingOutModel.ts:35:10 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'MeanShareAndBalanceModel'.

35   public reset(): void {
```

Two ways to resolve this:

(1) Add the `override` modifer, `public overridereset(): void`.

(2) Delete MeanShareAndBalanceModel `reset` method, if you don't think the base class will need to reset anything.

Also please check with @samreid to determine how it was possible to push this error.  Githooks should prevent things like this from being pushed.

**Comment by samreid** [comment]
This error was possible because we hadn't pulled the new tsconfig options yet.  I'll correct it shortly and we can discuss it further tomorrow.

**Comment by samreid** [comment]
Push fixed.  @marlitas please pull changes at your convenience.
