### ISSUE TITLE
Pointer Areas Review

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#40]
<img width="1341" alt="Screen Shot 2022-06-23 at 2 48 36 PM" src="https://user-images.githubusercontent.com/42476338/175396927-3467b78e-dc0c-4d9a-9571-ac3fa6fcb783.png">

**Comment by marlitas** [comment]
<img width="1341" alt="Screen Shot 2022-06-23 at 3 02 40 PM" src="https://user-images.githubusercontent.com/42476338/175399322-591fa5ea-29d3-43e5-975e-fbdfac4a4ed0.png">

**Comment by pixelzoom** [comment]
Looks good as of 6/27 for code review https://github.com/phetsims/mean-share-and-balance/issues/41.
