### ISSUE TITLE
MeanShareAndBalanceModel should be an interface

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#45]
For code review https://github.com/phetsims/mean-share-and-balance/issues/41 ...

`MeanShareAndBalanceModel` looks like this:

```typescript
export default class MeanShareAndBalanceModel {

  public constructor( providedOptions: MeanShareAndBalanceModelOptions ) {
    // Here for potential future use.
  }

  public syncData(): void {
    // See subclass for implementation
  }

  /**
   * Resets the model.
   */
  public reset(): void {
    // See subclass for implementation
  }

  /**
   * Steps the model.
   * @param dt - time step, in seconds
   */
  public step( dt: number ): void {
    // See subclass for implementation
  }
}
```

`MeanShareAndBalanceModel` is not meant to be instantiated directly. It provides no properties, functionality, or default behavior.  And (based on what I see in IntroModel) you're expecting the subclasses to override all of those empty methods.  So `MeanShareAndBalanceModel` should be an `interface`. 

As an interace, it would look like this:

```typescript
interface MeanShareAndBalanceModel {

  syncData(): void;

  /**
   * Resets the model.
   */
  reset(): void;

  /**
   * Steps the model.
   * @param dt - time step, in seconds
   */
  step( dt: number ): void;
}

export default MeanShareAndBalanceModel;
```

And usages would look like this:

```typescript
export default class IntroModel implements MeanShareAndBalanceModel {
```

Interfaces are sometime named with an "I" prefix, like axon's `IProperty`.  But PhET does not have a clear convention on this, so you decide whether it should be `MeanShareAndBalanceModel` or `IMeanShareAndBalanceModel`.

**Comment by pixelzoom** [comment]
By the way... If `MeanShareAndBalanceModel` had properties or provided default behavior, then I'd be recommending that you make it an `abstract` class.

**Comment by marlitas** [comment]
@samreid suggested marking MeanShareAndBalanceModel as an abstract class for now as future screens get developed. We do anticipate adding methods or properties so will make abstract for the moment.

**Comment by marlitas** [comment]
`MeanShareAndBalanceModel` is now an abstract class.
