### ISSUE TITLE
Set backgroundColorProperty and keyboardHelpNode in IntroScreen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#46]
For code review https://github.com/phetsims/mean-share-and-balance/issues/41 ...

In MeanShareAndBalanceScreen.ts:

```typescript
    const options = optionize<MeanShareAndBalanceScreenOptions, SelfOptions, ScreenOptions>()( {
      backgroundColorProperty: MeanShareAndBalanceColors.screenBackgroundColorProperty,
      keyboardHelpNode: new SliderControlsAndBasicActionsKeyboardHelpContent()
    }, providedOptions );
```

In most PhET sims, each screen has a unique color and unique keyboard-help content.  So those options feel inappropriate in this base class.  I recommend:

* Move `backgroundColorProperty` and `keyboardHelpNode` options to IntroScreenView.ts
* Rename `screenBackgroundColorProperty` to `introScreenBackgroundColorProperty`

That will put you (or the next developer) in a better position to add screens to this sim.

This also brings up the question of whether `MeanShareAndBalanceScreen` serves any purpose.  Because if you remove those options, it's not doing anything.   I would probably delete MeanShareAndBalanceScreen.ts for now, and wait to see if a base class is needed when future screens are added.

**Comment by marlitas** [comment]
MeanShareAndBalanceScreen has been deleted, and `backgroundColorProperty` and `keyboardHelpNode` options have been moved to the appropriate classes. Closing.
