### ISSUE TITLE
pdomOrder is specified incorrectly

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#47]
For code review https://github.com/phetsims/mean-share-and-balance/issues/41 ...

In https://github.com/phetsims/phet-info/blob/master/doc/alternative-input-quickstart-guide.md#traversal-order, 2 approaches are described for handling pdomOrder (aka traversal order).  

IntroScreenView.ts currently appears to be leaning towards Approach 1, because it sets ` this.pdomPlayAreaNode.pdomOrder` and `this.pdomControlAreaNode.pdomOrder`. But it does not follow the other requirement of Approach 1, which is to add children to `this.pdomPlayAreaNode` and `this.pdomControlAreaNode`, not directly to the ScreenView.

Unless "play area" and "control area" have explicity been part of the sim design, it's recommended to follow Approach 2.

**Comment by pixelzoom** [comment]
I also see that IntroScreenView extends MeanShareAndBalanceScreenView. But MeanShareAndBalanceScreenView currently ignored `pdomOrder`.  Classes are typically responsible for specifying the order of Nodes that they create, so this is a little odd.  On the other hand, it can be more straightforward for a subclass to specify the complete order for its Nodes and its superclass' Nodes.  You just have to be careful -- if you add a Node to the superclass, you'll need to change all of its subclasses.

So... You should probably investigate:

(1) setting `pdomOrder` in MeanShareAndBalanceScreenView for the Nodes that it creates
(2) adding to `pdomOrder` in IntroScreenView for the Nodes that it creates

**Comment by marlitas** [comment]
This issue is on hold until designer feedback for https://github.com/phetsims/mean-share-and-balance/issues/76 is provided

**Comment by marlitas** [comment]
I believe I corrected pdomOrder specification in the commits in: https://github.com/phetsims/mean-share-and-balance/issues/76

@pixelzoom can you review and provide feedback?

**Comment by pixelzoom** [comment]
Delete this line in MeanShareAndBalanceScreenView.ts, it looks vestigial:

> this.screenViewRootNode.pdomOrder = [ ...this.children, this.questionBar ];

Make this change in IntroScreenView.ts:

```diff
-    this.screenViewRootNode.pdomOrder = [ waterCupLayerNode, controlPanel, predictMeanSlider ];
+    this.screenViewRootNode.pdomOrder = [ ...waterCup3DNodes, ...pipeNodes, controlPanel, predictMeanSlider ];
```

**Comment by marlitas** [comment]
Fixed in above commit. Closing. Thanks @pixelzoom!
