### ISSUE TITLE
Call super.dispose after doing subclass-specific disposal

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#49]
For code review #41 ...

`super.dispose` is typically called _after_ doing any subclass-specific disposal. This sim is doing the opposite.

For example in WaterCup3DNode.ts:

```typescript
  public override dispose(): void {
    super.dispose();
    this.waterLevelTriangle.dispose();
    this.adapterProperty.dispose();
    this.introModel.isShowingTickMarksProperty.unlink( this.showTickMarksLink );
    this.cup3DModel.resetEmitter.removeAllListeners();
  }
```

Search for `super.dispose`, I think the order is reversed everywhere.

**Comment by marlitas** [comment]
Since moving everything to static allocation, disposal is no longer required for any of the elements in this screen. Closing.
