### ISSUE TITLE
Use "Listener" suffix for the name of Property listeners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#51]
For code review #41 ...

The signatures for `link` and `unlink` are:

```
public link( listener: PropertyLinkListener<T>, options?: LinkOptions ): void

public unlink( listener: PropertyListener<T> ): void
```

So the first parameter is a "listener", and (by convention) we typically name them accordingly, with a "Listener" suffix.  In WaterCup2DNode.ts and WaterCup3DNode.ts, you've used a diffferent convention, a "Link" suffix:

```js
// WaterCup2DNode.ts
  private readonly meanLink: PropertyLinkListener<number>;
  private readonly waterLevelLink: PropertyLinkListener<number>;

// WaterCup3DNode.ts
  private readonly showTickMarksLink: ( isShowingTickMarks: boolean ) => void;
```

Another reason to avoid the "Link" suffix is that there are places where's it's more appropriate, like the name of a Multilink instance.

Another convention is that the name of the listener is typically based on the name of the Property.  `showTickMarksLink` listens to `isShowingTickMarksProperty`, so it's a little "off" -- it should be named `isShowingTickMarksListener`.

So... Recommend to rename the above listeners to `meanListener`, `waterLevelListener`, and `isShowingTickMarksListener` respectively.

**Comment by marlitas** [comment]
This issue was addressed in the above commit. Closing.
