### ISSUE TITLE
Incorrect tandem name for Intro screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#54]
For code review #41 ...

In mean-share-and-balance-main.ts, this tandem name looks incorrect:

```
new IntroScreen( { tandem: Tandem.ROOT.createTandem( 'levelingOutScreen' ) } )
```

Shouldn't it be "introScreen"?

**Comment by marlitas** [comment]
This was addressed in commit: https://github.com/phetsims/mean-share-and-balance/commit/12ae38cf1909276c31b1f019484feb5aa9675af9

Closing.
