### ISSUE TITLE
Tandem name should match associated variable/field name

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#55]
For code review #41 ...

By PhET-iO convention, tandem names are typically supposed to match their associated variable/field name (with exceptions made for unusual cases).  There are at least 5 violations of that in this sim, and none of them qualifies as "unusual".

For example, in MeanShareAndBalanceScreenView.ts:

```
this.syncDataButton = new RectangularPushButton( {
...
      tandem: options.tandem.createTandem( 'syncRepresentationsButton' ),
```

I added comment "//REVIEW tandem name does not match" to all of the cases that I identified. (Not necessarily a complete list.)

**Comment by marlitas** [comment]
Did a search and fixed all the instances I was able to find. Back to @pixelzoom for re-review.

**Comment by pixelzoom** [comment]
👍🏻 closing.
