### ISSUE TITLE
CUP_RANGE_MIN and CUP_RANGE_MAX issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#56]
For code review #41 ...

In MeanShareAndBalanceConstants.js

```js
  CUP_RANGE_MIN: 0,
  CUP_RANGE_MAX: 1,
```

First, `CUP_RANGE` doesn't tell me anything.  Is this actually the level of the water in cup? If so, then `WATER_LEVEL` would be much more meaningful.  Or even `WATER_HEIGHT`, since you have this in WaterCupModel.ts:

```js
waterHeightRange: new Range( MeanShareAndBalanceConstants.CUP_RANGE_MIN, MeanShareAndBalanceConstants.CUP_RANGE_MAX )
```

Second, you have 9 places where you're creating a Range instance that involve these min/max constants:

```
new Range( MeanShareAndBalanceConstants.CUP_RANGE_MIN, MeanShareAndBalanceConstants.CUP_RANGE_MAX )
```

Why not replace `CUP_RANGE_MIN` and `CUP_RANGE_MAX` with:

```js
  CUP_RANGE: new Range( 0, 1 ),
```

**Comment by marlitas** [comment]
Renamed ranges for clarity, and added a WATER_LEVEL_RANGE to be used when possible. Closing.
