### ISSUE TITLE
Use PhET convention for naming Properties related to visibility.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#59]
For code review #41 ...

In IntroModel.ts:

```typescript
    this.isShowingPredictMeanProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'isShowingPredictMeanProperty' )
    } );
    this.isShowingMeanProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'isShowingMeanProperty' )
    } );
    this.isShowingTickMarksProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'isShowingTickMarksProperty' )
    } );
```

The "isShowing" prefix here does not match PhET/PhET-iO naming conventions. 
For Properties that control visibility, the convention is to give them names (and tandem names) of the form `{something}VisibleProperty`.  

So these should Properties and their tandems should be renamed to `predictMeanVisibleProperty`, `meanVisibleProperty`, and `tickMarksVisiblePropery`.

**Comment by marlitas** [comment]
All property names changed. Closing.

**Comment by pixelzoom** [comment]
Reopening.   I don't see any commits associated with this issue.  And I still see the "isShowing" names being used in IntroModel.ts:

```typescript
  public readonly isShowingPredictMeanProperty: BooleanProperty;
  public readonly isShowingMeanProperty: BooleanProperty;
  public readonly isShowingTickMarksProperty: BooleanProperty;
  // Property that tracks whether auto-share is enabled or not.
  public readonly isAutoSharingProperty: BooleanProperty;
```

**Comment by marlitas** [comment]
Closing. Commits now pushed up.
