### ISSUE TITLE
Changing "Auto Share" should interrupt interaction with sliders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#62]
For code review #41, and related to https://github.com/phetsims/mean-share-and-balance/issues/61 ...

If the user changes the "Auto Share" checkbox, then any in-progress interactions with the water-level sliders presumably should be cancelled.  Searching for `interruptSubtreeInput', I don't see that happening.

**Comment by marlitas** [comment]
interruptSubtreeInput implement on auto share value change. Closing.
