### ISSUE TITLE
Inconsistent checkbox labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#68]
For code review #41 ...

There's a bit of inconsistency in how the "Show Mean" and "Tick Marks" checkboxes are labeled:

<img width="167" alt="screenshot_1726" src="https://user-images.githubusercontent.com/3046552/176317494-3ccb4286-e23e-42d1-a6d2-8ad1b1c97606.png">

Consisent would be either one of these:
(1) "Show Mean" and "Show Tick Marks"
(2) "Mean" and "Tick Marks"

Personally, I'm not a fan of the word "Show", so I prefer (2).

**Comment by amanda-phet** [comment]
I think removing "Show" makes sense and is consistent with Center and Variability. Please go ahead and remove that word @marlitas .

**Comment by marlitas** [comment]
Checkbox labels have been updated accordingly. Closing
