### ISSUE TITLE
Reduce coupling to IntroModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#71]
For code review #41 ...

For this checklist item:
> - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

There is definitely some unnessary coupling in WaterCup3DNode.ts:

```
public constructor( introModel: IntroModel, ...
```

WaterCup3DNode should not know about the entire IntroModel.  It needs to know about only 2 things:

* introModel.isShowingTickMarksProperty
* introModel.changeWaterLevel

These 2 things should be provided to WaterCup3DNode via the constructor, not the entire IntroModel instance.

This is especially important if you're going to use WaterCup3DNode with other model.

**Comment by pixelzoom** [comment]
Similar problem for PredictMeanNode:

```
public constructor( model: IntroModel, modelViewTransform: ModelViewTransform2, providedOptions: PredictMeanNodeOptions )
```

There's no need to tie PredictMeanNode to IntroModel.  Pass the things that PredictMeanNode needs in via the constructor.  Or if you want to get fancier, define an interface for the things that PredictMeanNode needs, make IntroModel implement that interface, and change constructor parameter `model: IntroModel` accordingly.

**Comment by marlitas** [comment]
Went through repo to double check that coupling to IntroModel was reduced as much as seems reasonable. Sending back to @pixelzoom for final review.

**Comment by samreid** [comment]
While @marlitas and I were working on https://github.com/phetsims/mean-share-and-balance/issues/90 we found a better solution for this problem.

The original code passed in the entire model:

```ts
      const cupNode = new WaterCup3DNode( model, cupModel, modelViewTransform3DCups,
```

which is overcoupling.  The code review recommendation above was:

> These 2 things should be provided to WaterCup3DNode via the constructor, not the entire IntroModel instance.

So @marlitas made a change and made the code read like so:

```ts
      const cupNode = new WaterCup3DNode( model.tickMarksVisibleProperty, model.changeWaterLevel.bind( model ), cupModel, modelViewTransform3DCups,
```

However, this has several negative ramifications.  Most importantly, it makes it difficult in WaterCup3DNode to know where the implementation of `changeWaterLevel` lies.  WaterCup3DNode's constructor looks like:

```ts
  public constructor( tickMarksVisibleProperty: Property<boolean>,
                      changeWaterLevel: ( cup3DModel: WaterCup, waterLevel: number, oldWaterLevel: number ) => void,
                      waterCup: WaterCup, modelViewTransform: ModelViewTransform2,
                      providedOptions?: WaterCup3DNodeOptions ) {
```

And navigating to any occurrence of `changeWaterLevel` in the file dead-ends at that constructor site.  Backtracking to the implementation site is more difficult.

@pixelzoom later described another proposal for creating an interface for this.  

> Or if you want to get fancier, define an interface for the things that PredictMeanNode needs, make IntroModel implement that interface, and change constructor parameter model: IntroModel accordingly.

This solves some of the problem and helps with navigability (navigation takes you to the interface, which then you can click to find implementors of the interface), but still requires boilerplate to (a) write the interface, possibly duplicating method signatures (b) declare the model to implement the interface and (c) specify the interface at the usage site to narrow the used API.  And navigation is a 2-step process (or more, if there are more implementors of that interface).

### Proposed Improved Solution

@marlitas and I committed a different solution which has the following attributes:
* Implements decoupling
* Provides streamlined navigation
* Does not require declaring a separate interface

The call site passes the entire model:

```ts
const cupNode = new WaterCup3DNode( this.tickMarksVisibleProperty, model, 
```

But the receiving site narrows the API to the part that it is acceptable to use:

```ts
  public constructor( tickMarksVisibleProperty: Property<boolean>,
                      model: Pick<IntroModel, 'changeWaterLevel'>,
```

This protects against unnecessary coupling, while still streamlining navigation and minimizing boilerplate and duplication.  If you put the cursor on `'changeWaterLevel'` WebStorm knows to navigate to the correct implementation in 1 step.

@marlitas and I felt this solution was superior to the alternatives and wanted to raise it for discussion at dev meeting.

**Comment by pixelzoom** [comment]
👍🏻 This is a nice alternative, and a nice use of structural typing.

**Comment by marlitas** [comment]
Keeping this open for Dev Meeting PSA. Will close after.

**Comment by jessegreenberg** [comment]
8/11/22 dev meeting - 

This was shown to the team - people thought it was cool and agrees it provides the benefits of decoupling and IDE navigation. Devs will start to use this.

This example is already in the code review checklist, great!

**Comment by marlitas** [comment]
Since this issue has been discussed and I don't see any follow up steps that need to be taken I am closing. Feel free to re-open if you feel otherwise.
