### ISSUE TITLE
Consider moving visibility Properties to the view

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#72]
For code review #41 ...

These Properties are currently in IntroModel.ts:

```typescript
    this.isShowingPredictMeanProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'isShowingPredictMeanProperty' )
    } );
    this.isShowingMeanProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'isShowingMeanProperty' )
    } );
    this.isShowingTickMarksProperty = new BooleanProperty( false, {
      tandem: options.tandem.createTandem( 'isShowingTickMarksProperty' )
    } );
```

They have nothing to do with the model. And more importantly, PhET-iO clients may expect them to be in the view.  So consider moving them to IntroScreenView.  For an example, see geometric-options.VisibleProperties.

**Comment by marlitas** [comment]
Visibility properties have been moved to the view. Thanks for the suggestion!
