### ISSUE TITLE
Migrate SyncIcon to common code?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#73]
For code review #41 ...

Re this checklist item:
> - [ ]  Is there anything that should be generalized and migrated to common code?

SyncIcon is a likely candidate.  But I'd also like to see it use fontawesome fa:refresh icon, see https://fontawesome.com/v4/icon/refresh.

**Comment by marlitas** [comment]
The design portion of this question is being tracked here: https://github.com/phetsims/mean-share-and-balance/issues/35

On hold until designer feedback is provided. Adding @pixelzoom's comment to the other issue and closing to remove duplicates.
