### ISSUE TITLE
Dynamic barFill for QuestionBar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#74]
For code review #41 ...

Re this question in MeanShareAndBalanceScreenView.ts:

```typescript
    // TODO: Can QuestionBar be built in a way that allows changing barFill and labelText after construction?
    // see: https://github.com/phetsims/scenery-phet/issues/751
     this.questionBar = new QuestionBar( this.layoutBounds, this.visibleBoundsProperty, {
      tandem: options.tandem.createTandem( 'questionBar' ),
      labelText: meanShareAndBalanceStrings.introQuestion,
      barFill: '#2496D6'
    } );
```

It already supports dynamic barFill. Simply pass in a PaintColorProperty, like you can do for any scenery Node subclass that has a `fill` option.

**Comment by marlitas** [comment]
Ahhh. I've never used a color property in that way so didn't even think of it. Thanks! Will update my question in the related issue: https://github.com/phetsims/scenery-phet/issues/751

**Comment by marlitas** [comment]
Used color property to solve the above question. Closing.
