### ISSUE TITLE
meanProperty should be a DerivedProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#75]
For code review #41 ...

For this checklist item:
> - [ ] Are all dependent Properties modeled as DerivedProperty instead of Property?

This is unfortunate in IntroModel.ts, especially since it's arguable the most-important Property in the screen:

```typescript
    // This value is derived from the water levels in all the cups, but cannot be modeled as a DerivedProperty since
    // the number of cups varies
    this.meanProperty = new NumberProperty( ...
```

And this unfortunate compromise is due to https://github.com/phetsims/mean-share-and-balance/issues/60.  So to reiterate what I said in that issue, I would reconsider the decision to dynamically allocate pipes and cups.  Or investigate other ways of allowing `meanProperty` to be a DerivedProperty.

**Comment by samreid** [comment]
We also used the new feature `deriveAny` from https://github.com/phetsims/axon/issues/406.

**Comment by samreid** [comment]
@marlitas and I collaborated on this, and it seems ready for review.  Thanks for the great recommendation!

**Comment by pixelzoom** [comment]
Looks good.  A couple of nits...

*  This comment means nothing to me. Maybe say it differently or more verbosely.  Is it saying something about the internal implementatioin of  DerivedProperty? If so, what if that changes?  

```
    // map() does not preserve a property of .length required for DerivedProperty
    this.meanProperty = DerivedProperty.deriveAny( dependencies,
```

* Since it's public-facing... The `phetioDocumentation` for `meanProperty` is very difficult to read/parse, because it's contains compound adjectives that are not properly hyphenated.  (If you're not familiar with compound adjectives and when to hypenate, see https://www.gingersoftware.com/content/grammar-rules/adjectives/compound-adjectives/.) Recommended change:

```
-         phetioDocumentation: 'The ground truth water level mean.',
+         phetioDocumentation: 'The ground-truth water-level mean.',

**Comment by pixelzoom** [comment]
Maybe the comment is trying to explain why `dependencies` is an array, and not a map?  If so, the comment probably belongs on the definition of `const dependencies`.  But even then, you still need to use the spread operator (...) to combine the maps into one array.  So maybe the comment is unnecessary?

```js
    const dependencies = [
      ...this.waterCup3DArray.map( waterCup => waterCup.waterLevelProperty ),
      ...this.waterCup3DArray.map( waterCup => waterCup.isActiveProperty )
    ];

    // map() does not preserve a property of .length required for DerivedProperty
    this.meanProperty = DerivedProperty.deriveAny( dependencies,
```

**Comment by marlitas** [comment]
Documentation updated in above commit. Hopefully this clarifies the comment before meanProperty. I do not fully understand the typing restrictions on derivedProperty, I just know they exist, so if further clarification is needed I'll reach out for assistance. 

Assigning back to @pixelzoom for reaview.

**Comment by pixelzoom** [comment]
👍🏼 closing.
