### ISSUE TITLE
Check the traversal order

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#76]
For code review #41 ...

In other sims that I've worked on, things in the "play area" are typically first in the traversal order.  In this sim, the first thing is the "Predict Mean" checkbox, and I have to tab many times to get to the play area.  

I'm not sure if this is how the traversal order was designed, or whether it hasn't been done yet. So including @amanda-phet in assignees.

**Comment by marlitas** [comment]
A conversation needs to be had about suggested traversal order. Will put on docket for our next design meeting.

**Comment by amanda-phet** [comment]
We have not discussed this yet, but I think @marlitas and I can discuss it without needing the entire team. Our agenda is looking fairly packed this week.

**Comment by marlitas** [comment]
@jessegreenberg and I worked on this last week and were able to get the traversal order and focus highlighting to work as discussed in a meeting with @amanda-phet. Sending back to @amanda-phet for feedback.

**Comment by amanda-phet** [comment]
Discussed 10/17/22 and we think the predict line should be in the tab order just after the valves and just before the "predict mean" checkbox. This way, the tab order for the prediction line is in a more logical place for predicting and then opening the valves. We also think it's a good user experience to check the box, then use shift+tab to go back and interact with the new element.

**Comment by marlitas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Screen 1 Design](https://trello.com/c/NkWVx0dJ/1-screen-1-design)
