### ISSUE TITLE
Address REVIEW comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#78]
For code review #41 ...

During a code review, the reviewer has the option of either creating GitHub issues or adding REVIEW comments directly to the code.  

REVIEW comments are typically minor things that do not require a GitHub issue, and they look like this example in MeanShareAndBalanceConstants.ts:

```js
  //REVIEW These names are a little vague/incorrect. MOUSE_AREA_DILATION and TOUCH_AREA_DILATION dilation would be clearer.
  MOUSE_DILATION: 5,
  TOUCH_DILATION: 10,
```

There are currently 48 REVIEW comments, search for "REVIEW". Let me know if you have questions about any of them. Some them are suggestions, and a fine response would be "nah, not going to do that".  

You can mention this issue in related commits. And feel free to close this issue when all REVIEW comments have been deleted.

**Comment by samreid** [comment]
For `//REVIEW Needs more description - tell me about "water cup" in this sim.`, @marlitas added documentation in this commit:

https://github.com/phetsims/mean-share-and-balance/commit/a718fa82e0b8df881a14ff45fb66558cdd2880b3

Does that seem sufficient?  We weren't sure if we should add more context or detail.

**Comment by marlitas** [comment]
All review comments have been addressed. Closing.
