### ISSUE TITLE
Screen 2 Name: Leveling Out or Fair Share?

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#79]
In the design document, we noticed that the Screen 2 heading is titled "Fair Share", but in the mockups the screen is titled "Leveling Out". Screen 3 is also titled "Fair Share". 

To @samreid and I, it seems like "Leveling Out" relates more to water, and "Fair Share" relates more to chocolates and cookies. We wanted to confirm screen titles. 

Currently the screens are titled as such in some mockups and code:
Screen 1: Intro
Screen 2: Leveling Out
Screen 3: Fair Share
Screen 4: Balancing

- Is this correct?
- Does "Leveling Out" accurately describe the chocolate screen?

**Comment by amanda-phet** [comment]
These are the correct finalized titles. 

Screen 1: Intro
Screen 2: Leveling Out
Screen 3: Fair Share
Screen 4: Balance Point

"Leveling out" applies to both the continuous and discrete representations (water and chocolate bars), but we decided we wanted them on separate screens, so water is named Intro.

**Comment by marlitas** [comment]
Thanks, this answered my question. Closing!
