### ISSUE TITLE
Predict Mean Line Span

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#8]
- Should the draggable predict mean line span across the screen or just the cups? 
- Will the length of the line change depending on the number of cups?

**Comment by amanda-phet** [comment]
I was thinking the line would be a fixed width/length and span across the whole area where it can move. I'm open to discussing all of the options to see what makes the most sense, though.

**Comment by marlitas** [comment]
@amanda-phet Sam and I took a guess and currently have the predict mean line adjusting according to the amount of cups. Is very easy to change back to a static length though. Can change based on your final opinion.

**Comment by amanda-phet** [comment]
I reviewed this last week and like how it's looking with the variable length.
