### ISSUE TITLE
How to deal with PipeModel Tandem.REQUIRED option?

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#80]
In https://github.com/phetsims/mean-share-and-balance/issues/78 @marlitas and I observed this review comment:

```ts
  public constructor( providedOptions?: PipeModelOptions ) {
    const options = optionize<PipeModelOptions, SelfOptions, PhetioObjectOptions>()( {
      isOpen: false,
      phetioType: PipeModel.PipeModelIO,
      //REVIEW replace with PickRequired<PhetioObjectOptions, 'tandem'>
      tandem: Tandem.REQUIRED,
      phetioDynamicElement: true
    }, providedOptions );
```

This issue requires further discussion, so we are promoting that REVIEW comment to this issue.

We would like to add `PickRequired<PhetioObjectOptions, 'tandem'>` to the options, but we don't want to remove `tandem: Tandem.REQUIRED` until https://github.com/phetsims/tandem/issues/253 has been completed.

**Comment by marlitas** [comment]
https://github.com/phetsims/tandem/issues/253 has been closed, and this issue has been dealt with accordingly, by removing Tandem.REQUIRED and replacing with a PickRequired. Closing.
