### ISSUE TITLE
Field declarations should expose only the API needed.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#82]
Noted when reviewing #59 , and for code review https://github.com/phetsims/mean-share-and-balance/issues/41 ...

In IntroModel.ts:

```typescript
  public readonly isShowingPredictMeanProperty: BooleanProperty;
  public readonly isShowingMeanProperty: BooleanProperty;
  public readonly isShowingTickMarksProperty: BooleanProperty;
  // Property that tracks whether auto-share is enabled or not.
  public readonly isAutoSharingProperty: BooleanProperty;
```

All of the above declarations should be `Property<boolean>`.  There's nothing about the `BooleanProperty` subclass of `Property<boolean>` that needs to be exposed via the API.  Instantiation using `new BooleanProperty` is correct.

This is not isolated to IntroModel.ts.  I see this issue across many .ts files.  Sorry I missed it during code review.

In general... The type used in the declaration of a field is not always the same type used when instantiating that field. Declarations should use the most general (narrowest API) type, and instantiation may be a more specific subtype.  The same is true for method and function parameters.

Happy to discuss if this needs clarification.

**Comment by marlitas** [comment]
@pixelzoom I have tried changing the declaration of `NumberProperty` to `Property<number>` and am receiving the following type error:

```
Type 'Property<number>' is missing the following properties from type 'NumberProperty': numberType, validateNumberAndRangeProperty, rangeProperty, disposeNumberProperty, and 6 more.
```

I receive a similar error with `BooleanProperty` to `Property<boolean>` as well. I am not sure if this is user error, or the way these properties are being used in the sim that is preventing me from successfully implementing this.

**Comment by marlitas** [comment]
@zepumph helped me make sense of some of the type errors that came up when I tried this. I believe everything that could be converted has been converted, so sending over to @pixelzoom for a final look-over before closing.

**Comment by pixelzoom** [comment]
👍🏻 closing.
