### ISSUE TITLE
New starting state for Intro screen 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#83]
Discussed 7/14/22 

We'd like the sim to start with two cups, the first cup at 80% full and the second at 50% full. 

All new cups get added at 50% full.

**Comment by amanda-phet** [comment]
7/21/22 meeting 

* discussed different cup levels
* Might not want a cup at 100% since it will be at an extreme, rather than allowing someone to slide both up and down 
* We are ok with the "average" being a value that isn't easy to describe other than "halfway between two tick marks" 
* AM: If the concern is someone interpreting this question as quantitative, we might want to consider changing the question phrasing 

Decision: 75% full 1st cup

@amanda-phet can see how students interpret the question in interviews.

**Comment by marlitas** [comment]
New starting state implemented. Unassigning and leaving open for @amanda-phet if you would like to use this issue during interviews. If not, feel free to close!

**Comment by amanda-phet** [comment]
Looks good to me. Thanks!
