### ISSUE TITLE
Arrow isn't always at water level 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#86]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/821

If I change the water level in a cup and then remove that cup, when I re-add it to the scene, the water level is at half, but the arrow is in the wrong place. The arrow seems to be where the water level was before I removed that cup. 

**Steps to reproduce**
1. Add a third cup
2. Increase the water level in the 3rd cup so that it is full
3. Decrease the amount of cups to 2
4. Increase the amount of cups back to 3

**Visuals**

https://user-images.githubusercontent.com/87318828/181076653-f85022be-9a1b-4a27-b069-5d77ac807cdf.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.5/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.5 2022-07-25 15:18:20 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1204x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
not seen in dev.4

**Comment by marlitas** [comment]
Pushed a fix up to master. Will update the dev build so this does not disturb any other testing.

**Comment by marlitas** [comment]
Yay! Closing as completed.
