### ISSUE TITLE
Lag when filling empty cup

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#87]
**Test device**
MacBook Air (m1chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/821
After removing all the water from the cups, if I then fill a cup without having taken my finger off the trackpad, there is a delay. I don't see the cup filling, but instead jumps to the cup already filled. 

**Steps to reproduce**
1. Open the valve to allow water sharing
2. Empty the left cup
3. Empty the right cup and then without taking your finger off the mouse/trackpad, try to refill the cup

**Visuals**

https://user-images.githubusercontent.com/87318828/181102300-6ff97598-1a25-4b56-ab35-db19ea006276.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.6/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.6 2022-07-26 18:07:52 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1204x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
not able to reproduce in dev.4

**Comment by samreid** [comment]
@marlitas and I committed a workaround that seems to be working well.  We opened https://github.com/phetsims/kite/issues/98 for the underlying problem, which can be solved separately.

**Comment by samreid** [comment]
@Nancy-Salpepi can you please confirm this fix in phettest?

**Comment by Nancy-Salpepi** [comment]
@samreid It still looks the same to me on Master with Mac 12.5 + Safari. If I pause briefly once I empty the second cup without letting go of the mouse, and then move to fill the cup--there is still a delay and I don't see the water balancing itself. 

https://user-images.githubusercontent.com/87318828/182197950-02cf5994-88d6-47bc-bb45-ed1d4e71eb75.mp4

**Comment by marlitas** [comment]
@Nancy-Salpepi we observed on phettest that the code being run is stale, and our updates have not been pulled in yet.
![Screen Shot 2022-08-01 at 12 08 18 PM](https://user-images.githubusercontent.com/42476338/182204566-d9685a3f-8c7d-492d-acee-cc3021265ab8.png)

Can you try pulling all of the out-of-date repos and try again?

**Comment by Nancy-Salpepi** [comment]
Sorry about that @marlitas!  
It looks much better, but if I repeatedly empty/fill the cup without lifting my mouse, the issues appears. 

https://user-images.githubusercontent.com/87318828/182219980-10795143-dab0-438a-87e9-15c46d811892.mp4

**Comment by marlitas** [comment]
Mmmm. I see that. In that case I think fully fixing this problem is currently blocked by: https://github.com/phetsims/kite/issues/98

Will try to schedule time with @jonathanolson to find a fix or another workaround.

**Comment by samreid** [comment]
@marlitas and I also reached out to @Nancy-Salpepi to make sure that a cache-busting strategy was in place, to make sure it wasn't running stale, cached code on phettest.

**Comment by Nancy-Salpepi** [comment]
I'm so sorry @samreid @marlitas. I thought I had cleared my history before I pulled all but I hadn't. Your workaround is working perfectly.

**Comment by Nancy-Salpepi** [comment]
I'll check other platforms as well

**Comment by Nancy-Salpepi** [comment]
Looks good on Win10 Chrome and Firefox too! The workaround is definitely working!

**Comment by marlitas** [comment]
Perfect! I'm going to say this is done then. Closing.
