### ISSUE TITLE
Water re-balances when cups are added and removed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#88]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/821
Back in dev.4, if the cups were connected and you removed a cup, the water in the remaining cups would jump to be in sync with the lower beakers, then rebalance. When you added a cup this did not happen. In the new dev version this rebalance also happens when adding a cup.

**Visuals**
Old behavior:
![oldbehavior](https://user-images.githubusercontent.com/41024075/181109759-b520f979-ff82-4e12-8639-c8c4485ff268.gif)
New behavior: 
![newbehavior](https://user-images.githubusercontent.com/41024075/181109796-25835b2e-5381-4bb7-8cef-37a9338c5be6.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.6/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.6 2022-07-26 18:07:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
@amanda-phet, @KatieWoe brought this up to me over a zoom meeting and I wasn't sure what the preferred behavior is so I asked her to make an issue so that you could weigh in. Not sure which would be best for the pedagogical experience.

**Comment by marlitas** [comment]
Design Meeting 7/27:
- We would like to remove the re-balancing every time a cup is added.
- Remove the re-balancing any time a cup is removed where the 2D & 3D cup water levels match.
- We are going to add a query parameter that allows us to see both animated and instantaneous re-balances.
- Once we see this we can potentially brainstorm other ways to point out the change.

**Comment by marlitas** [comment]
Added logic that removes the re-balancing animation anytime a cups is added or when a cup is removed and it's 2D & 3D representation water levels match. Have not implemented Query parameters yet, but this seems like a good point for a dev build that @amanda-phet can use for interviews.

Will work on getting query parameters up and running by next week.

**Comment by marlitas** [comment]
Retracting comment above. @amanda-phet the dev build will have query parameters for turning on/off animation when cups are added or removed. The query param is: `showAnimation=false` (to turn off)

The query parameter defaults to true.

Assigning back to @amanda-phet for review and feedback.

**Comment by marlitas** [comment]
This issue no longer exists with the new pipe toggle state. Closing.
