### ISSUE TITLE
Home/End keys don't jump to min/max when valve is open

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#90]
**Test device**
MacBook Air (m1 chip)

**Operating System**
MacOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/821, when the valve is open between 2 cups, pressing the home/end keys (fn + left/right arrows on the mac) doesn't result in the cup becoming completely full or empty. When the valve is closed, the home/end keys work properly. 
This is also present in dev.4.

**Steps to reproduce**
1. Close the valve between the 2 cups
2. Press the home button
3. Press the end button

**Visuals**

https://user-images.githubusercontent.com/87318828/181136361-235cb0a8-3a37-4c98-9b16-c504687517f4.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.6/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.6 2022-07-26 18:07:52 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1204x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
the page up/down keys seem to be working correctly

**Comment by Nancy-Salpepi** [comment]
also seeing this issue with the Chromebook

**Comment by marlitas** [comment]
@Nancy-Salpepi this was a big code change to address this fix, but we think we figured it out!

Could you test on phettest to make sure home/end keys are working as expected, and do a check on behavior when dragging water between connected cups? We had to change the logic, and I want to make sure that by fixing home/end we didn't break multi-touch or mouse dragging.

Thanks!

**Comment by Nancy-Salpepi** [comment]
The home/end keys are working as they should @marlitas!
One thing I did notice is that when going from min/max values, the cup to the left of the one you are adjusting will shoot to its final value instead of changing slowly like the other cups do. 
For example, watch the cup in the middle in the video:

https://user-images.githubusercontent.com/87318828/183507135-a6fd9ae7-cd80-41ee-a8aa-290ce69f81de.mp4

**Comment by Nancy-Salpepi** [comment]
Here is a video with all 7 cups. Cups 1,2, 5, 6 & 7 are all doing the same thing as I change the value of Cup 4 from min to max. Cup 3 seems to mirror the changes I am making to cup 4--at least when I jump to max.
 




https://user-images.githubusercontent.com/87318828/183740234-975a86a4-0980-4115-ac1e-b928e59c2fba.mp4

**Comment by marlitas** [comment]
We are working on fixing the animation. This is a patch for animation that ripples outward:

<details>

```diff
Index: js/intro/model/IntroModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/intro/model/IntroModel.ts b/js/intro/model/IntroModel.ts
--- a/js/intro/model/IntroModel.ts	(revision 1b7feff0a5ea3f40a13f0687d557f2e6ed73efd9)
+++ b/js/intro/model/IntroModel.ts	(date 1660774486976)
@@ -182,16 +182,31 @@
     if ( this.arePipesOpenProperty.value ) {
       this.getActive2DCups().forEach( cup => {
         const currentWaterLevel = cup.waterLevelProperty.value;
-        const delta = this.meanProperty.value - currentWaterLevel;
+
+        const neighbors = this.waterCup2DArray.filter( cup2D => Math.abs( cup2D.linePlacement - cup.linePlacement ) === 1 );
+        const neighborValues = neighbors.map( cup => cup.waterLevelProperty.value );
+
+        const oldValue = cup.waterLevelProperty.value;
+        const localValue = calculateMean( neighborValues );
+        const globalValue = this.meanProperty.value;
+
+
+        const oldDifference = Math.abs( globalValue - oldValue );
+        const proposedDifference = Math.abs( globalValue - localValue );
 
-        let discrepancy = 4;
+        const targetValue = proposedDifference < oldDifference ? localValue : globalValue;
+
+        // the target change
+        const delta = targetValue - currentWaterLevel;
+
+        let discrepancy = 5;
 
         // Adjusts discrepancy so that water flows faster between cups when the mean is very low or very high.
-        if ( this.meanProperty.value >= 0.9 ) {
-          discrepancy = Utils.linear( 0.9, 1, 5, 50, this.meanProperty.value );
+        if ( targetValue >= 0.9 ) {
+          discrepancy = Utils.linear( 0.9, 1, 5, 50, targetValue );
         }
-        else if ( this.meanProperty.value <= 0.1 ) {
-          discrepancy = Utils.linear( 0.1, 0, 5, 50, this.meanProperty.value );
+        else if ( targetValue <= 0.1 ) {
+          discrepancy = Utils.linear( 0.1, 0, 5, 50, targetValue );
         }
 
         // Animate water non-linearly. Higher discrepancy means the water will flow faster.
@@ -199,11 +214,11 @@
         let newWaterLevel = Math.max( 0, currentWaterLevel + delta * dt * discrepancy );
 
         // Clamp newWaterLevel to ensure it is not outside the currentWaterLevel and waterMean range.
-        if ( this.meanProperty.value > currentWaterLevel ) {
-          newWaterLevel = Utils.clamp( newWaterLevel, currentWaterLevel, this.meanProperty.value );
+        if ( targetValue > currentWaterLevel ) {
+          newWaterLevel = Utils.clamp( newWaterLevel, currentWaterLevel, targetValue );
         }
         else {
-          newWaterLevel = Utils.clamp( newWaterLevel, this.meanProperty.value, currentWaterLevel );
+          newWaterLevel = Utils.clamp( newWaterLevel, targetValue, currentWaterLevel );
         }
 
         cup.waterLevelProperty.set( newWaterLevel );
```
</details>

**Comment by marlitas** [comment]
This is ready for a QA check from @Nancy-Salpepi again. Thanks!

**Comment by Nancy-Salpepi** [comment]
@marlitas the changes to the water levels in the cups on either side of the one I am emptying/filling look different than the rest of the cups. 






https://user-images.githubusercontent.com/87318828/186419047-af7238aa-4505-477d-b262-688866c3bf20.mp4

**Comment by Nancy-Salpepi** [comment]
I also noticed that keyboard nav skips over the Valve toggle and Number or Cups. Let me know if you want me to make a new issue for that or if that is on your list already 🙂.

**Comment by samreid** [comment]
> @marlitas the changes to the water levels in the cups on either side of the one I am emptying/filling look different than the rest of the cups.

We intentionally designed it to have a "ripple out" effect because we thought it would feel more physical and playful.

> I also noticed that keyboard nav skips over the Valve toggle and Number or Cups. Let me know if you want me to make a new issue for that or if that is on your list already

Will be covered in https://github.com/phetsims/mean-share-and-balance/issues/76, thanks!

@Nancy-Salpepi anything else for this issue?  Please close if all is well.

**Comment by Nancy-Salpepi** [comment]
Thanks for the explanation @samreid! Makes sense!
Nothing more here.
