### ISSUE TITLE
Pressing Sync doesn't interrupt filling/emptying cup

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#91]
**Test device**
iPad Air 2

**Operating System**
15.5

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/821, when emptying and filling the cup with one finger, pressing the Sync button with another finger doesn't interrupt the first action. In dev.4 pressing the Sync button does interrupt that action. 

**Steps to reproduce**
1. With one finger continually empty and fill a cup
2. With another finger press the Sync button

**Visuals**
 I made this video with the iPad and couldn't figure out how to show finger touches, but I think you can see what is (or isn't) happening. 

https://user-images.githubusercontent.com/87318828/181346013-fba78374-23d6-41d9-92d5-88ecfd5d3491.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.6/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.6 2022-07-26 18:07:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language: en-US
Window: 1995x1044
Pixel Ratio: 1.3333333730697632/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
@Nancy-Salpepi I just pushed a fix to master. Can you double check that this is working as expected with multi-touch?

**Comment by Nancy-Salpepi** [comment]
I wasn't sure if I should make this a separate issue or not, but I found it odd that removing the cup that I am emptying/filling doesn't interrupt the action. When I re-add the cup, my finger movement is emptying and filling that cup. 

Steps:
1. With one finger continuously empty and fill the second cup
2. With a second finger, reduce the number of cups to 1
3. Increase the number of cups to 2

**Comment by marlitas** [comment]
@Nancy-Salpepi that does seem like odd behavior for multi-touch. To me this is a reasonable enough argument to interrupt any actions when a cup is added or removed.

@amanda-phet  wanted to get your thoughts also in case you disagree or other scenarios where this could be undesirable come up. 

In the meantime I'll go ahead and implement since it's easy to remove.

**Comment by Nancy-Salpepi** [comment]
@marlitas it seems extremely odd that I would be able to empty/fill a cup that doesn't exist. I think the behavior should definitely be interrupted if the cup is no longer present. 

I'll let @amanda-phet weigh in on whether or not adding/removing a cup should interrupt all actions (For example, if I am emptying/filling cup 1 and I add a 3rd cup at the same time, should the first action be interrupted?).

https://user-images.githubusercontent.com/87318828/181356367-38d11ed5-0be3-4380-92c8-2096ae21e2af.mov

**Comment by Nancy-Salpepi** [comment]
@marlitas pressing Sync now interrupts emptying/filling action.

**Comment by marlitas** [comment]
We no longer have a sync button. Closing.
