### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#93]
We are getting close to RC and it would be good to finalize the credits.

**Comment by samreid** [comment]
@KatieWoe provided the QA credits.  @amanda-phet can you please specify the team, thanks and graphicArts, and anything else that needs help?

**Comment by amanda-phet** [comment]
team and thanks are all set. For graphicArts, we should credit Mariah Hermsmeyer.

**Comment by amanda-phet** [comment]
Done in the above commit. Closing.
