### ISSUE TITLE
Water line level doesn't match the water level, even when cups were disconnected

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#96]
In testing https://github.com/phetsims/mean-share-and-balance/issues/60, @marlitas and I observed that the water line level didn't match the water level, even when cups were disconnected:

<img width="247" alt="image" src="https://user-images.githubusercontent.com/679486/185976205-2e3835b2-d1c7-4f96-8fd3-f7f308aa82d2.png">

**Comment by marlitas** [comment]
Fixed in above commit.
