### ISSUE TITLE
In state wrapper, on reset all, it takes 2 state sets to get to the correct state

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#97]
Discovered by me and @marlitas in https://github.com/phetsims/mean-share-and-balance/issues/60, we saw that if you change the water amount in cup 1 and cup 2 in the state wrapper, then press reset all, it takes 2 state sets to get back to the initial state.  The 1st time, the 2d cups have a temporary incorrect value.

**Comment by marlitas** [comment]
Fixed in the above commit. Closing.
