### ISSUE TITLE
Predict Mean Slider style

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#98]
This issue will be used to track the design options and decisions for the `predictMeanSlider` in the Intro Screen.

**Comment by samreid** [comment]
@marlitas worked with @jonathanolson on the pattern/dash stroke.  There was a GitHub issue with adding images to comments so I added them from my side:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/679486/186456514-0a6cad4f-8552-4100-b02b-cc0dbcdfb23a.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/679486/186456621-aa7d9715-2826-40d4-9d44-92b65e70a2ef.png">

@amanda-phet can you please take a look and advise?  Close if all is well.

**Comment by marlitas** [comment]
I shortened the distance between cups to remove the pencil overlap on the controls.

It now looks like this:
<img width="915" alt="Screen Shot 2022-08-26 at 8 50 25 AM" src="https://user-images.githubusercontent.com/42476338/186932169-5eddefb7-9467-44f1-9264-62aac3d16482.png">

**Comment by amanda-phet** [comment]
I was going to suggest just that! I was thinking it would also help with the 3D cups and making that table narrower. I'll take a look and then close this.
